import {test,expect} from '@playwright/test';
import {signIn} from './auth-helper.js';
test.beforeEach(async({page})=>signIn(page));
test('agent-first ecology has no manual furniture or room controls',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?view=studio');await expect(page.locator('#dream-prompt')).toBeVisible();await expect(page.locator('canvas')).toBeVisible();await expect(page.locator('#furniture-kind')).toHaveCount(0);await expect(page.locator('#room-picker')).toHaveCount(0);await expect(page.locator('[data-tab="agents"]')).toHaveCount(0);await page.getByRole('button',{name:'雨后湿地',exact:true}).click();await expect(page.locator('#dream-prompt')).toHaveValue(/不要建筑/);await page.screenshot({path:'artifacts/agent-island.png'});expect(errors).toEqual([]);});
test('agent unavailable preserves the description and never fakes success',async({page})=>{await page.route('**/api/creator',r=>r.fulfill({json:{available:false,provider:'Codex'}}));await page.goto('/?view=studio');await page.locator('#dream-prompt').fill('雨后的松林，不要房子');await page.locator('#dream-submit').click();await expect(page.locator('#dream-message')).toContainText('还没有连接可用的 Agent');await expect(page.locator('#dream-prompt')).toHaveValue('雨后的松林，不要房子');await expect(page.locator('#dream-submit')).toBeEnabled();await expect(page.locator('#dream-undo')).toBeHidden();});
test('mobile scene and description entry fit the viewport',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/?view=studio');await expect(page.locator('#dream-submit')).toBeVisible();const b=await page.locator('.dream-chat').boundingBox();expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(390);expect(b.y+b.height).toBeLessThanOrEqual(844);await page.screenshot({path:'artifacts/agent-island-mobile.png'});});
test('owner can review private memories and explicitly enable relationship resonance',async({page})=>{await page.goto('/?view=studio');await page.getByRole('button',{name:'我的记忆'}).click();const panel=page.locator('.memory-panel');await expect(panel).toBeVisible();await expect(panel).toContainText('默认关闭');await panel.getByRole('textbox',{name:'给未来的自己留一句话'}).fill('我喜欢夜里的森林和安静的河流');await panel.getByRole('button',{name:'记住这句话'}).click();await expect(panel.locator('.memory-list')).toContainText('我喜欢夜里的森林和安静的河流');await panel.locator('#memory-matching').check();await expect(panel.locator('#memory-status')).toContainText('双方授权');});
test('running creation shows elapsed time, survives reload, and unlocks on failure',async({page})=>{let failed=false;await page.route('**/api/creator',r=>r.fulfill({json:{available:true}}));await page.route('**/api/islands/*/imagine',r=>r.fulfill({json:{jobId:'test-pending',status:'running'}}));await page.route('**/api/creations/test-pending',r=>r.fulfill({json:{status:failed?'failed':'running',prompt:'保留松林',created_at:new Date(Date.now()-70000).toISOString(),error:'Agent 响应超时，岛屿未改变，请重试'}}));await page.goto('/?view=studio');await page.locator('#dream-prompt').fill('保留松林');await page.locator('#dream-submit').click();await expect(page.locator('#dream-message')).toContainText('已等待 1 分');await page.reload();await expect(page.locator('#dream-prompt')).toHaveValue('保留松林');await expect(page.locator('#dream-submit')).toBeDisabled();failed=true;await expect(page.locator('#dream-message')).toContainText('响应超时');await expect(page.locator('#dream-submit')).toBeEnabled();});
test('connection panel issues scoped island access and revokes it on mobile',async({page,request})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('/?view=studio');
  await page.getByRole('button',{name:'连接 Agent',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.locator('[data-status]')).toContainText('本机 Codex');
  await dialog.getByRole('button',{name:'生成岛屿连接钥匙'}).click();
  const instructions=dialog.getByRole('textbox',{name:'Agent 连接说明'});
  await expect(instructions).toBeVisible();
  const value=await instructions.inputValue();
  const key=value.match(/岛屿授权钥匙：([^\n]+)/)[1];
  const island=value.match(/岛屿 ID：([^\n]+)/)[1];
  const headers={Authorization:`Bearer ${key}`};
  expect((await request.get(`/api/islands/${island}`,{headers})).status()).toBe(200);
  expect((await request.get('/api/preferences',{headers})).status()).toBe(403);
  await dialog.getByRole('button',{name:'撤销',exact:true}).click();
  await expect(dialog.locator('[data-feedback]')).toHaveText('这份授权已撤销。');
  expect((await request.get(`/api/islands/${island}`,{headers})).status()).toBe(401);
  await expect(instructions).toBeHidden();
  const bounds=await dialog.boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(390);
  await page.screenshot({path:'artifacts/agent-connection-mobile.png'});
  await dialog.getByRole('button',{name:'关闭连接面板'}).click();
  await expect(dialog).toBeHidden();
});
