import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createService} from './service.js';
import {createIslandMail,validateLetter,classifyMajorChange} from './island-mail.js';
import {worldClock,WORLD_DAY_MS} from '../src/world-clock.js';
import {applyPreferences} from './preferences.js';
import {worldProgram,worldTemplates} from './world-templates.js';
import {starterEcosystem} from './ecosystem.js';
import {runInNewContext} from 'node:vm';
import {createServer} from 'node:http';
const prefs={world:'planet',variant:4,animals:'unicorn',light:'night',home:'open',landscape:'none',growing:true};
function fixture(){const s=createService(':memory:'),a=s.register('星河'),b=s.register('潮汐'),c=s.auth(a.token),cb=s.auth(b.token);const key=s.issueAgent(c,a.islandId,['scene:write','interior:write','avatar:write','memory:read']),agent=s.auth(key.token);return {s,a,b,c,cb,key,agent};}
test('a key alone does not unlock onboarding; hello is island-scoped and revocable',()=>{const {s,a,b,c,cb,key,agent}=fixture();assert.equal(s.agentStatus(c).connected,false);assert.throws(()=>s.startJourney(c,{preferences:prefs,revision:0}),e=>e.status===409);assert.throws(()=>s.agentHello(c,a.islandId,{name:'假问候',message:'hi'}),e=>e.status===403);assert.throws(()=>s.agentHello(agent,b.islandId,{name:'跨岛',message:'hi'}),e=>e.status===403);s.agentHello(agent,a.islandId,{name:'她的 Agent',message:'Hello 星河'});assert.equal(s.agentStatus(c).hello,'Hello 星河');assert.equal(s.agentStatus(cb).connected,false);s.revoke(c,key.id);assert.equal(s.agentStatus(c).connected,false);s.db.close();});
test('journey sends original choices to own Agent and a completed program queues a private versioned letter',()=>{const {s,a,b,c,cb,agent}=fixture();s.agentHello(agent,a.islandId,{name:'她的 Agent',message:'Hello'});const job=s.startJourney(c,{preferences:prefs,expression:'三只独角兽住在极光里',revision:0});const task=s.codingTask(agent,a.islandId);assert.equal(task.task.id,job.jobId);assert.match(task.task.prompt,/三只独角兽/);assert.equal(task.preferences.expression,'三只独角兽住在极光里');assert.equal(s.mail.list(c).length,0);const program="island.mesh({id:'planet',shape:'sphere',color:'#aacccc',scale:[12,12,12]});";const saved=s.submitProgram(agent,a.islandId,job.jobId,program,'生成极光星球',{daylight:'night',objects:[]});assert.equal(saved.scene.program,program);assert.equal(saved.scene.daylight,'night');const letters=s.mail.list(c);assert.equal(letters.length,1);assert.equal(letters[0].status,'queued');assert.equal(s.mail.list(cb).length,0);const input=JSON.parse(s.db.prepare('SELECT input FROM island_letters WHERE id=?').get(letters[0].id).input);assert.equal(input.userId,a.userId);assert.equal(input.scene.program,program);assert.equal(input.revision,saved.revision);assert.equal(s.mail.changed(a.userId),letters[0].id);assert.throws(()=>s.mail.image(cb,letters[0].id,0),e=>e.status===404);s.db.close();});
test('journey rolls preferences and memory back if the creation limit is reached',()=>{const {s,a,c,agent}=fixture();s.agentHello(agent,a.islandId,{name:'Agent',message:'hello'});for(let i=0;i<10;i++){const job=s.beginCreation(c,a.islandId,'请求 '+i);s.failCreation(job.jobId,'停止');}const before=s.me(c).island;assert.throws(()=>s.startJourney(c,{preferences:prefs,revision:before.revision}),e=>e.status===429);assert.deepEqual(s.me(c).island,before);assert.equal(s.preferences(c),null);s.db.close();});
const response=input=>({title:input.islandName+'的来信',portrait:input.preferences.expression||'依据测试输入写成的报告',letter:'这是一封测试来信',themes:[],mbti:{type:null,note:'信息不足',axes:[]}});
test('a missing provider produces no report; injected analysis uses isolated snapshots and survives updates',async()=>{const {s,a,b,c,cb}=fixture();s.savePreferences(c,{...prefs,expression:'给星空的私密话'},0);s.savePreferences(cb,{...prefs,world:'ocean',expression:'只属于大海的话'},0);s.mail.changed(a.userId);s.mail.changed(b.userId);const idle=createIslandMail(s.db,{fail:(status,m)=>{throw Object.assign(Error(m),{status});},generate:async()=>null});await idle.tick();assert.equal(idle.list(c)[0].status,'waiting_provider');assert.equal(idle.list(c)[0].report,null);const seen=[];const worker=createIslandMail(s.db,{generate:async input=>{seen.push(input);return response(input);},images:async()=>[]});await worker.tick();await worker.tick();assert.equal(worker.list(c)[0].report.portrait,'给星空的私密话');assert.equal(worker.list(cb)[0].report.portrait,'只属于大海的话');assert.equal(seen.length,2);assert.ok(seen.every(i=>!JSON.stringify(i).includes(i.userId===a.userId?'只属于大海的话':'给星空的私密话')));s.mail.amend(c,s.mail.list(c)[0].id,'其实我更喜欢安静');assert.match(JSON.stringify(s.exportMemory(c)),/其实我更喜欢安静/);s.db.close();});
test('deleted letters cannot be resurrected by late results and invalid MBTI evidence is omitted',async()=>{const {s,a,c}=fixture();s.savePreferences(c,prefs,0);const id=s.mail.changed(a.userId),input=s.mail.snapshot(a.userId,'portrait');const invalid={...response(input),mbti:{type:'ENFP',note:'guess',axes:['EI','SN','TF','JP'].map((axis,i)=>({axis,choice:'ENFP'[i],evidence:['missing','also missing']}))}};assert.equal(validateLetter(invalid,input).mbti.type,null);const worker=createIslandMail(s.db,{generate:async i=>{s.mail.erase(c,id);return response(i);},images:async()=>[]});await worker.tick();assert.equal(s.mail.list(c).length,0);s.db.close();});
test('daily letters contain the prior day’s changes and are idempotent; old data is not reissued',()=>{const {s,a,c}=fixture();s.savePreferences(c,prefs,0);const id=s.mail.changed(a.userId),day='2026-09-09',eventAt=day+'T03:00:00.000Z';s.db.prepare("UPDATE settings SET value=? WHERE key='mail-started-at'").run('2026-09-09T00:00:00.000Z');s.db.prepare('UPDATE island_letters SET created_at=? WHERE id=?').run(eventAt,id);s.db.prepare('INSERT INTO memory_context VALUES(?,?,?,?,?,?,?)').run('daily-test',a.userId,a.islandId,'island_change','今天放了一盏灯','{}',eventAt);const worker=createIslandMail(s.db,{clock:()=>new Date('2026-09-10T02:00:00.000Z')});worker.daily();worker.daily();const rows=worker.list(c).filter(r=>r.kind==='daily');assert.equal(rows.length,1);const input=JSON.parse(s.db.prepare('SELECT input FROM island_letters WHERE id=?').get(rows[0].id).input);assert.equal(input.day,day);assert.ok(input.memories.some(m=>m.id==='daily-test'));s.db.close();});
test('long day and long night have different measured durations and persistent phases',()=>{for(const [mode,ratio] of [['day',.8],['night',.22],['balanced',.5]]){let day=0;for(let t=0;t<10000;t++)if(worldClock(mode,1000,1000+t/10000*WORLD_DAY_MS).day)day++;assert.ok(Math.abs(day/10000-ratio)<.001);assert.deepEqual(worldClock(mode,1000,32100),worldClock(mode,1000,32100));}assert.equal(worldClock('night',1000,1000).daylight,0);assert.equal(worldClock('day',1000,1000).daylight,1);});
test('all new world programs generate bounded geometry and preserve chosen animals',()=>{for(const {id} of worldTemplates)for(const variant of [0,4,9999]){const meshes=[],moves=[];const island={mesh:m=>meshes.push(m),onFrame:fn=>moves.push(fn),move(){},onClick(){}};runInNewContext(worldProgram(id,variant),{island},{timeout:500});assert.ok(meshes.length<=150);let vertices=0;for(const m of meshes){assert.ok(m.scale.every(s=>s>0&&s<=20));vertices+=m.shape==='custom'?m.vertices.length/3:m.shape==='sphere'?(m.detail==='high'?1189:221):m.shape==='cylinder'?246:60;assert.ok(m.position.every(Number.isFinite));}assert.ok(vertices<=18000,`${id}: ${vertices}`);for(const fn of moves)for(const t of [0,10,1000])fn(t);const scene=applyPreferences(starterEcosystem(),{...prefs,world:id,variant});assert.equal(scene.objects.filter(o=>o.kind==='unicorn').length,3,id);}});

test('major change rules trigger reanalysis while ordinary decoration does not',()=>{const base=starterEcosystem(),flower={id:'small-flower',kind:'flowers',roomId:null,x:1,y:0,z:1,rotation:0,color:'rose'};assert.equal(classifyMajorChange({beforeScene:base,currentScene:{...base,objects:[...base.objects,flower]}}).major,false);const climate=classifyMajorChange({beforeScene:base,currentScene:{...base,weather:'rain'}});assert.equal(climate.major,true);assert.deepEqual(climate.affectedDimensions,['emotional_stability']);const boundary=classifyMajorChange({actions:[{type:'object.upsert',value:{kind:'house'}}]});assert.equal(boundary.major,true);assert.ok(boundary.affectedDimensions.includes('need_for_control'));const visitors=classifyMajorChange({prompt:'把来访规则改成只有收到邀请的人可以进入'});assert.equal(visitors.major,true);assert.ok(visitors.affectedDimensions.includes('extraversion'));});

test('scene commits queue only major profile versions',()=>{const {s,a,c}=fixture();try{s.savePreferences(c,prefs,0);s.mail.changed(a.userId);let island=s.me(c).island;s.patch(c,a.islandId,island.revision,[{type:'object.upsert',value:{id:'small-flower',kind:'flowers',roomId:null,x:1,y:0,z:1,rotation:0,color:'rose'}}]);assert.equal(s.mail.list(c).length,1);island=s.me(c).island;s.patch(c,a.islandId,island.revision,[{type:'environment.set',value:{weather:'rain'}}]);const rows=s.mail.list(c);assert.equal(rows.length,2);assert.equal(rows[0].kind,'change');const input=JSON.parse(s.db.prepare('SELECT input FROM island_letters WHERE id=?').get(rows[0].id).input);assert.deepEqual(input.affectedDimensions,['emotional_stability']);}finally{s.db.close();}});

test('change reports update only affected dimensions and preserve prior evidence',()=>{const facts=[{id:'a',content:'雨',source:'user-choice'},{id:'b',content:'夜',source:'user-choice'}],previousPortrait={profile:{openness:{value:.8,evidence:['old-a','old-b']},emotional_stability:{value:.7,evidence:['old-c','old-d']}}},input={kind:'change',facts,affectedDimensions:['emotional_stability'],previousPortrait},raw={title:'变化',portrait:'我注意到岛上的天气变了。',letter:'变化由你解释。',themes:[],profile:{openness:{value:.1,evidence:['a','b']},emotional_stability:{value:.4,evidence:['a','b']}},mbti:{type:null,note:'信息不足',axes:[]}},report=validateLetter(raw,input);assert.deepEqual(report.profile.openness,previousPortrait.profile.openness);assert.deepEqual(report.profile.emotional_stability,{value:.4,evidence:['a','b']});assert.equal(report.profile.conscientiousness,null);});

test('onboarding report stores grounded structured evidence and self-reported MBTI wins',async()=>{const {s,a,c}=fixture();try{s.savePreferences(c,prefs,0);s.mail.changed(a.userId);const worker=createIslandMail(s.db,{generate:async input=>{const ids=input.facts.slice(0,2).map(f=>f.id);return {title:'我理解的你',portrait:'你选择了星球与独角兽；放在一起，也许说明你愿意给想象留出真实位置。',letter:'这只是我读到的一种可能。',themes:[{title:'想象的住处',text:'你让两种选择彼此照亮。',evidence:ids,imagePrompt:'星球上的独角兽'}],profile:{openness:{value:.8,evidence:ids}},mbti:{type:null,note:'证据不足',axes:[]}};},images:async()=>[]});await worker.tick();let report=worker.list(c)[0].report;assert.deepEqual(report.profile.openness.evidence.length,2);assert.equal(report.profile.conscientiousness,null);worker.mbti(c,'ISTJ');report=worker.list(c)[0].report;assert.equal(report.mbti.type,'ISTJ');assert.equal(report.mbti.source,'self_report');}finally{s.db.close();}});

test('analysis failure never rolls back the saved island',async()=>{const {s,a,c}=fixture();try{s.savePreferences(c,prefs,0);const revision=s.me(c).island.revision;s.mail.changed(a.userId);const worker=createIslandMail(s.db,{generate:async()=>{throw Error('model down');}});await worker.tick();assert.equal(worker.list(c)[0].status,'failed');assert.equal(s.me(c).island.revision,revision);}finally{s.db.close();}});

test('text and image HTTP adapters persist a private illustration without leaking keys into snapshots',async()=>{
 const {s,a,c,cb}=fixture();s.savePreferences(c,{...prefs,expression:'只属于星河的极光'},0);const id=s.mail.changed(a.userId),requests=[];
 const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aB1sAAAAASUVORK5CYII=';
 const upstream=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const data=JSON.parse(body);requests.push({url:req.url,body:data});res.setHeader('Content-Type','application/json');if(req.url==='/chat/completions'){const input=JSON.parse(data.messages[1].content);res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(response(input))}}]}));}else res.end(JSON.stringify({data:[{b64_json:png}]}));});
 await new Promise(resolve=>upstream.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+upstream.address().port,values={ISLAND_ANALYSIS_BASE_URL:base,ISLAND_ANALYSIS_API_KEY:'test-analysis-key',ISLAND_ANALYSIS_MODEL:'test-text',ISLAND_IMAGE_BASE_URL:base,ISLAND_IMAGE_API_KEY:'test-image-key',ISLAND_IMAGE_MODEL:'test-image'},previous=Object.fromEntries(Object.keys(values).map(k=>[k,process.env[k]]));Object.assign(process.env,values);
 try{await s.mail.tick();const row=s.mail.list(c)[0];assert.equal(row.status,'delivered');assert.deepEqual(row.images,[0]);assert.equal(row.report.illustrationStatus,'ready');assert.equal(s.mail.image(c,id,0).mime,'image/png');assert.throws(()=>s.mail.image(cb,id,0),e=>e.status===404);assert.match(requests.find(r=>r.url==='/images/generations').body.prompt,/只属于星河的极光/);assert.doesNotMatch(s.db.prepare('SELECT input FROM island_letters WHERE id=?').get(id).input,/test-analysis-key|test-image-key/);}
 finally{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}await new Promise(resolve=>upstream.close(resolve));s.db.close();}
});
