import {randomUUID,createHash} from 'node:crypto';
export const REFLECTION_VERSION='island-reflection-v1';
export {TYPES,PROMPTS} from '../src/reflection-prompts.js';
import {TYPES,PROMPTS} from '../src/reflection-prompts.js';
import {preferenceDescription} from './preferences.js';
export function validateAnswers(input,fail){if(!input||typeof input!=='object'||Array.isArray(input))fail(400,'请先留下你的想法');const answers={};for(const q of PROMPTS){const v=input[q.key];if(typeof v!=='string'||!v.trim()||v.length>400)fail(400,'每个回答需为 1–400 字');answers[q.key]=v.trim();}return answers;}
export function baseMirror(answers){return {engine:'observations',lines:[{evidence:['space','firstObject'],text:`你为自己想象了「${answers.space}」，第一件想带来的，是「${answers.firstObject}」。这座岛，正在从你亲自选下的事物开始。`},{evidence:['weather','time','music'],text:`你把「${answers.weather}」和「${answers.time}」留给这里，也为它选了「${answers.music}」。这是你此刻愿意停留的风景。`},{evidence:['visitors','boundary'],text:`关于相遇，你写下「${answers.visitors}」；关于边界，你说「${answers.boundary}」。这两句话，可以同时被好好记住。`},{evidence:[],text:'你可以改变主意，也可以纠正我。这座岛会继续生长，而你不必被这一次选择定义。'}]};}
export function baseIslandMirror(design){
 const keys=Object.keys(design).filter(key=>key!=='scene');
 const first=keys.slice(0,2),second=keys.slice(2,4),third=keys.slice(4);
 const describe=chosen=>chosen.map(key=>`「${design[key]}」`).join('、');
 return {engine:'observations',interpretationVersion:'island-design-v1',lines:[
  {evidence:first,text:`你让这座岛从${describe(first)}开始生长。这些是你亲手留下的生活线索。`},
  {evidence:second,text:`岛上还有${describe(second)}。它们放在一起，形成了只属于此刻的你的风景。`},
  {evidence:third.length?third:['scene'],text:third.length?`你也留下了${describe(third)}。它们为什么重要，仍由你来告诉我。`:`你没有急着填满这里；岛现在的样子，也是一种完整的表达。`},
  {evidence:[],text:'这是我从岛上读到的一种可能。哪里不对，你可以改写；你的解释永远比我的猜测更重要。'}
 ]};
}
const MBTI_AXES=[
 {axis:'E / I',positive:'E',positiveName:'向外连接',negative:'I',negativeName:'向内停留',positiveWords:/热闹|邻居|一起|分享|欢迎|任何人|社会|街道|开放|不要房子|动物|陪伴/,negativeWords:/安静|独处|私密|深夜|慢慢熟悉|留白|封闭|薄雾|森林/},
 {axis:'S / N',positive:'N',positiveName:'想象与可能',negative:'S',negativeName:'具体与现实',positiveWords:/幻想|独角兽|龙|漂浮|星球|宇宙|梦|魔法|未命名|从天|瀑布|未来/,negativeWords:/现实|日常|小屋|床|街道|草甸|池塘|猫|狗|兔|熊|狐狸/},
 {axis:'T / F',positive:'F',positiveName:'感受与价值',negative:'T',negativeName:'结构与逻辑',positiveWords:/喜欢|愿望|陪伴|分享|故事|花|音乐|灯|生命|温柔|水|看海/,negativeWords:/科技|规则|功能|效率|结构|规划|城市|档案|系统|秩序/},
 {axis:'J / P',positive:'P',positiveName:'自由与生长',negative:'J',negativeName:'确定与安排',positiveWords:/不要房子|开放|随地|留白|自由|探索|流动|河|溪|瀑布|海|生长|平衡/,negativeWords:/小屋|房子|建筑|规划|安排|规则|秩序|正午|城市|社会/},
];
export function predictMbti(answers){
 const entries=Object.entries(answers||{}).filter(([key,value])=>key!=='scene'&&typeof value==='string'&&value.trim()).map(([key,value])=>({key,value:value.trim()}));
 const dimensions=MBTI_AXES.map(def=>{const positive=entries.filter(item=>def.positiveWords.test(item.value)),negative=entries.filter(item=>def.negativeWords.test(item.value)),chosen=positive.length>=2&&positive.length>negative.length?positive:negative.length>=2&&negative.length>positive.length?negative:[];if(!chosen.length)return {axis:def.axis,letter:null,label:'信息不足',evidence:[]};const choosePositive=chosen===positive;return {axis:def.axis,letter:choosePositive?def.positive:def.negative,label:choosePositive?def.positiveName:def.negativeName,evidence:chosen.slice(0,3).map(item=>item.key)};});
 const complete=dimensions.every(item=>item.letter),type=complete?dimensions.map(item=>item.letter).join(''):null,evidenceCount=new Set(dimensions.flatMap(item=>item.evidence)).size,confidence=complete?Math.min(.82,.48+Math.min(evidenceCount,8)*.035):null;
 const labels=dimensions.filter(item=>item.letter).map(item=>item.label);return {type,confidence:confidence===null?null:Number(confidence.toFixed(2)),basis:'island_design',summary:type?`目前的多项岛屿选择共同指向${labels.join('、')}；这仍只是可由你修正的猜测。`:'至少一个维度缺少两条相互支持的选择，因此暂不猜测完整类型。',dimensions:dimensions.map(({axis,letter,label,evidence})=>({axis,letter,label,evidence}))};
}
export function tasteProfile(a){const prediction=predictMbti(a);if(!('space' in a))return islandTasteProfile(a,prediction);const dimensions={};for(const key of ['space','weather','time','visitors','music']){const q=PROMPTS.find(q=>q.key===key);dimensions[key]={value:a[key],basis:'user_choice',category:q.options.indexOf(a[key])};}return {mbti:null,mbti_predicted:prediction.type,mbti_prediction:prediction,mbti_confirmed:false,introversion:null,openness:null,emotional_stability:null,aesthetic_sensitivity:null,need_for_control:null,attachment_style:null,psychometricStatus:'not_assessed',taste:dimensions};}
function islandTasteProfile(design,prediction=predictMbti(design)){return {mbti:null,mbti_predicted:prediction.type,mbti_prediction:prediction,mbti_confirmed:false,introversion:null,openness:null,emotional_stability:null,aesthetic_sensitivity:null,need_for_control:null,attachment_style:null,psychometricStatus:'not_assessed',taste:{space:{value:design.world||null,basis:'island_design',category:-1},weather:{value:null,basis:'not_observed',category:-1},time:{value:design.light||null,basis:'island_design',category:-1},visitors:{value:null,basis:'not_observed',category:-1},music:{value:null,basis:'not_observed',category:-1}}};}
export function createReflectionStore(db,{fail,recordMemory}){
 const get=(sql,...p)=>db.prepare(sql).get(...p),all=(sql,...p)=>db.prepare(sql).all(...p),run=(sql,...p)=>db.prepare(sql).run(...p),now=()=>new Date().toISOString();
 const human=c=>{if(c.kind!=='human')fail(403,'这项理解需要由你亲自确认');};
 const row=u=>get('SELECT * FROM island_profiles WHERE user_id=?',u);
 function own(c,userId=c.user_id){human(c);if(userId!==c.user_id)fail(403,'画像和日签仅本人可见');return row(c.user_id);}
 function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
 function view(r){if(!r)return null;const answers=JSON.parse(r.answers),profile=JSON.parse(r.profile),mirror=JSON.parse(r.mirror),prediction=profile.mbti_prediction||predictMbti(answers);profile.mbti_predicted=profile.mbti_predicted||prediction.type;profile.mbti_prediction=prediction;if(mirror.analysis){mirror.analysis.measurement={...(mirror.analysis.measurement||{}),status:'inferred_from_island',mbti:prediction,note:'这是依据岛屿设计形成的 MBTI 倾向推测，不是标准化心理测评结果。'};}return {...r,answers,profile,mirror,analysisConsent:!!r.analysis_consent,matchingConsent:!!r.matching_consent,confirmed:!!r.confirmed};}
 function snapshot(user){const i=get('SELECT scene,revision FROM islands WHERE owner_id=?',user);if(!i)return null;const s=JSON.parse(i.scene),counts={};for(const o of s.objects)counts[o.kind]=(counts[o.kind]||0)+1;return {revision:i.revision,weather:s.weather,time:s.time,music:s.music,listening:get('SELECT track FROM island_listening WHERE user_id=?',user)?.track||'chan-ming',counts};}
 function islandDesign(user,expression=''){
  if(typeof expression!=='string'||expression.length>1000)fail(400,'补充描述最多 1000 字');
  const stored=get('SELECT payload FROM user_preferences WHERE user_id=?',user),islandRow=get('SELECT name,scene FROM islands WHERE owner_id=?',user);
  if(!stored||!islandRow)fail(409,'请先完成岛屿设计');
  const p=JSON.parse(stored.payload),scene=JSON.parse(islandRow.scene),lines=preferenceDescription(p).split('\n');
  const design={};
  for(const line of lines){const split=line.indexOf('：');if(split<0)continue;const keyByLabel={世界:'world',水:'water','陪伴我的生命':'animals','光与时间':'light',住所:'home',风景:'landscape'};const key=keyByLabel[line.slice(0,split)];if(key)design[key]=line.slice(split+1).replace(/。$/,'');}
  if(expression.trim())design.expression=expression.trim();
  const counts={};for(const object of scene.objects||[])counts[object.kind]=(counts[object.kind]||0)+1;
  design.scene=`岛名「${islandRow.name}」；生态 ${scene.ecosystem?.biome||'未命名'}；实际场景包含 ${Object.entries(counts).map(([kind,n])=>`${n} 个 ${kind}`).join('、')||'一片留白'}`;
  return design;
 }
 function observe(user){const r=row(user);if(!r?.analysis_consent||!r.confirmed)return {triggered:false};const current=snapshot(user),previous=JSON.parse(r.snapshot||'null');if(!previous||JSON.stringify(current)===JSON.stringify(previous))return {triggered:false};run('UPDATE island_profiles SET snapshot=? WHERE user_id=?',JSON.stringify(current),user);const evidence=[];for(const [key,label] of [['weather','天气'],['time','时光'],['music','声音'],['listening','音乐']])if(previous[key]!==current[key])evidence.push({key,before:previous[key],after:current[key],label});for(const [kind,label] of [['flowers','花草'],['tree','树'],['house','住处'],['recordPlayer','唱片机'],['rabbit','小兔子'],['cat','猫'],['dog','小狗'],['bird','鸟']]){const delta=(current.counts[kind]||0)-(previous.counts[kind]||0);if(Math.abs(delta)>=(['flowers','tree'].includes(kind)?3:1))evidence.push({key:kind,before:previous.counts[kind]||0,after:current.counts[kind]||0,label});}if(!evidence.length)return {triggered:false};const day=now().slice(0,10);if(get('SELECT 1 FROM island_daily_cards WHERE user_id=? AND day=?',user,day))return {triggered:false,reason:'daily_limit'};const e=evidence[0],text=['weather','time','music','listening'].includes(e.key)?`岛上的${e.label}变了。旧的风景曾陪过你，现在，你又为这里留下一种新的可能。`:`岛上的${e.label}${e.after>e.before?'多了一些':'少了一些'}。我看见了这个变化；它对你意味着什么，仍由你来说。`;const id=randomUUID();run('INSERT INTO island_daily_cards VALUES(?,?,?,?,?,?,?,?)',id,user,day,text,JSON.stringify(evidence),0,null,now());recordMemory(user,get('SELECT id FROM islands WHERE owner_id=?',user).id,{source:'island_change',type:'reflection',content:text,gesture:'岛屿变化观察',context:JSON.stringify(evidence),direction:'只记录可见改变，不据此推断心理状态',tags:['岛屿日签'],meta:{reflectionCardId:id}});return {triggered:true,card:{id,text,evidence}};}
 return {
 get(c,id){return view(own(c,id));},
 export(c){human(c);return {format:'island-reflection',version:1,exportedAt:now(),profile:view(row(c.user_id)),history:all('SELECT revision,payload,created_at FROM island_profile_history WHERE user_id=? ORDER BY revision',c.user_id).map(r=>({...r,payload:JSON.parse(r.payload)})),cards:this.timeline(c)};},
 brief(user){const r=row(user);if(!r?.confirmed||!r.analysis_consent)return null;const m=JSON.parse(r.mirror);return {userChoices:JSON.parse(r.answers),userCorrection:m.correction||'',instruction:'These are user-stated preferences, not inferred psychology. New explicit requests override them.'};},
 listening(c,track){human(c);if(track===undefined)return {track:get('SELECT track FROM island_listening WHERE user_id=?',c.user_id)?.track||'chan-ming'};if(!['chan-ming','original','local'].includes(track))fail(400,'音乐选项无效');return tx(()=>{run('INSERT INTO island_listening VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET track=excluded.track,updated_at=excluded.updated_at',c.user_id,track,now());observe(c.user_id);return {track};});},
 discard(c,revision){human(c);return tx(()=>{const r=row(c.user_id);if(!r||r.revision!==revision||r.confirmed)fail(409,'草稿已改变，请刷新');const previous=get('SELECT payload FROM island_profile_history WHERE user_id=? ORDER BY revision DESC LIMIT 1',c.user_id);if(previous){const p=JSON.parse(previous.payload);run('UPDATE island_profiles SET answers=?,profile=?,mirror=?,confirmed=1,matching_consent=0,revision=revision+1,updated_at=? WHERE user_id=?',JSON.stringify(p.answers),JSON.stringify(p.profile),JSON.stringify(p.mirror),now(),c.user_id);}else run('DELETE FROM island_profiles WHERE user_id=?',c.user_id);return {discarded:true};});},
  draft(c,answers,revision,consent){human(c);if(consent!==true)fail(400,'请先同意为你整理这段理解');answers=validateAnswers(answers,fail);const r=row(c.user_id);if((r?.revision||0)!==revision)fail(409,'你的理解已更新，请刷新后再试');const fingerprint=createHash('sha256').update(JSON.stringify(answers)).digest('hex'),nonce=randomUUID();tx(()=>{const job=get('SELECT expires_at FROM island_reflection_jobs WHERE user_id=?',c.user_id);if(job&&job.expires_at>now())fail(429,'这封信还在整理，请稍后');run('INSERT INTO island_reflection_jobs VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET nonce=excluded.nonce,expires_at=excluded.expires_at',c.user_id,nonce,new Date(Date.now()+60000).toISOString());});return {answers,revision,fingerprint,nonce};},
  draftIsland(c,expression=''){human(c);const answers=islandDesign(c.user_id,expression),r=row(c.user_id),revision=r?.revision||0,fingerprint=createHash('sha256').update(JSON.stringify(answers)).digest('hex'),nonce=randomUUID();tx(()=>{const job=get('SELECT expires_at FROM island_reflection_jobs WHERE user_id=?',c.user_id);if(job&&job.expires_at>now())fail(429,'这封信还在整理，请稍后');run('INSERT INTO island_reflection_jobs VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET nonce=excluded.nonce,expires_at=excluded.expires_at',c.user_id,nonce,new Date(Date.now()+60000).toISOString());});return {answers,revision,fingerprint,nonce,mode:'island-design'};},
 cancelDraft(c,nonce){run('DELETE FROM island_reflection_jobs WHERE user_id=? AND nonce=?',c.user_id,nonce);},
 saveDraft(c,draft,mirror){human(c);return tx(()=>{const lease=get('SELECT * FROM island_reflection_jobs WHERE user_id=?',c.user_id);if(!lease||lease.nonce!==draft.nonce||lease.expires_at<now())fail(409,'这次生成已经取消或过期');const credential=get('SELECT revoked_at,expires_at FROM credentials WHERE id=?',c.id);if(!credential||credential.revoked_at||credential.expires_at<now())fail(401,'登录已失效');const old=row(c.user_id);if((old?.revision||0)!==draft.revision)fail(409,'已有新的理解，本次结果未覆盖');const profile=tasteProfile(draft.answers);run('INSERT INTO island_profiles(user_id,revision,answers,profile,mirror,confirmed,analysis_consent,matching_consent,snapshot,created_at,updated_at) VALUES(?,?,?,?,?,0,1,0,?,?,?) ON CONFLICT(user_id) DO UPDATE SET revision=excluded.revision,answers=excluded.answers,profile=excluded.profile,mirror=excluded.mirror,confirmed=0,analysis_consent=1,matching_consent=0,snapshot=excluded.snapshot,updated_at=excluded.updated_at',c.user_id,draft.revision+1,JSON.stringify(draft.answers),JSON.stringify(profile),JSON.stringify(mirror),JSON.stringify(snapshot(c.user_id)),old?.created_at||now(),now());run('DELETE FROM island_reflection_jobs WHERE user_id=? AND nonce=?',c.user_id,draft.nonce);return view(row(c.user_id));});},
 confirm(c,input){human(c);return tx(()=>{const r=row(c.user_id);if(!r||r.revision!==input.revision)fail(409,'理解已更新，请重新打开');if(!['accepted','corrected'].includes(input.verdict)||typeof input.matchingConsent!=='boolean')fail(400,'请确认你的选择');if(input.mbti!==null&&!TYPES.includes(input.mbti))fail(400,'性格类型无效');if(typeof input.correction!=='string'||input.correction.length>1000)fail(400,'修正文字最多 1000 字');if(input.verdict==='corrected'&&!input.correction.trim())fail(400,'请告诉我哪里需要改');const p=JSON.parse(r.profile);p.mbti=input.mbti;p.mbti_confirmed=!!input.mbti;p.mbti_source=input.mbti?'self_report':null;if(input.verdict==='corrected'){for(const item of Object.values(p.taste)){item.category=-1;item.basis='needs_reconfirmation';}}const mirror=JSON.parse(r.mirror);mirror.verdict=input.verdict;mirror.correction=input.correction.trim();run('UPDATE island_profiles SET profile=?,mirror=?,confirmed=1,matching_consent=?,revision=revision+1,updated_at=? WHERE user_id=?',JSON.stringify(p),JSON.stringify(mirror),Number(input.matchingConsent),now(),c.user_id);run('INSERT INTO island_profile_history VALUES(?,?,?,?,?)',randomUUID(),c.user_id,JSON.stringify({answers:JSON.parse(r.answers),profile:p,mirror}),r.revision+1,now());recordMemory(c.user_id,get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id,{source:'user_note',type:'reflection',content:JSON.stringify({answers:JSON.parse(r.answers),mbti:input.mbti,correction:input.correction}),gesture:input.verdict==='corrected'?'用户修正了对自己的理解':'用户确认了这次自我表达',context:'岛屿镜像；MBTI 仅为本人提供，未进行心理测评',direction:input.correction.slice(0,500)||'以用户亲自选择的风景为依据',tags:['用户确认','岛屿镜像'],meta:{profileRevision:r.revision+1}});return view(row(c.user_id));});},
 observe,
 detect(c){human(c);return tx(()=>observe(c.user_id));},
 timeline(c,id){own(c,id);return all('SELECT * FROM island_daily_cards WHERE user_id=? ORDER BY created_at DESC LIMIT 100',c.user_id).map(r=>({...r,evidence:JSON.parse(r.evidence),favorite:!!r.favorite}));},
 card(c,id,input){human(c);const r=get('SELECT * FROM island_daily_cards WHERE id=? AND user_id=?',id,c.user_id);if(!r)fail(404,'日签不存在');if(typeof input.favorite!=='boolean'||(input.response!==null&&(typeof input.response!=='string'||input.response.length>500)))fail(400,'日签反馈无效');run('UPDATE island_daily_cards SET favorite=?,response=? WHERE id=?',Number(input.favorite),input.response,id);return {saved:true};},
 settings(c,input){human(c);if(typeof input.analysisConsent!=='boolean'||typeof input.matchingConsent!=='boolean')fail(400,'设置无效');run('DELETE FROM island_reflection_jobs WHERE user_id=?',c.user_id);run('UPDATE island_profiles SET analysis_consent=?,matching_consent=?,revision=revision+1,updated_at=? WHERE user_id=?',Number(input.analysisConsent),Number(input.analysisConsent&&input.matchingConsent),now(),c.user_id);return view(row(c.user_id));},
 erase(c){human(c);return tx(()=>{run('DELETE FROM island_reflection_jobs WHERE user_id=?',c.user_id);run('DELETE FROM island_profiles WHERE user_id=?',c.user_id);run('DELETE FROM island_profile_history WHERE user_id=?',c.user_id);run('DELETE FROM island_daily_cards WHERE user_id=?',c.user_id);const notes=all("SELECT id,source_links FROM memory_narratives WHERE user_id=? AND (tags LIKE '%岛屿镜像%' OR tags LIKE '%岛屿日签%')",c.user_id);for(const n of notes){run('DELETE FROM memory_narratives WHERE id=?',n.id);for(const id of JSON.parse(n.source_links))run('DELETE FROM memory_context WHERE id=? AND user_id=?',id,c.user_id);}return {deleted:true};});},
 resonance(a,b){const ra=row(a),rb=row(b);if(!ra?.confirmed||!rb?.confirmed||!ra.analysis_consent||!rb.analysis_consent||!ra.matching_consent||!rb.matching_consent)return null;const pa=JSON.parse(ra.profile).taste,pb=JSON.parse(rb.profile).taste;let equal=0,known=0;for(const k of ['space','weather','time','visitors','music']){if(pa[k].category<0||pb[k].category<0)continue;known++;if(pa[k].value===pb[k].value)equal++;}return known>=3?{score:equal/known,compared:known}:null;},
 match(c,a,b){human(c);if(![a,b].includes(c.user_id)||a===b)fail(403,'只能查看与你有关的相遇');const ia=get('SELECT id,discoverable FROM islands WHERE owner_id=?',a),ib=get('SELECT id,discoverable FROM islands WHERE owner_id=?',b);if(!ia?.discoverable||!ib?.discoverable||get('SELECT 1 FROM blocks WHERE (user_id=? AND blocked_user_id=?) OR (user_id=? AND blocked_user_id=?)',a,b,b,a))fail(404,'这次相遇暂不可用');const value=this.resonance(a,b);if(!value)fail(409,'双方需确认画像、允许品味匹配，并有至少三项可比较的选择');return {compatibility:Math.round(value.score*100),algorithm:REFLECTION_VERSION,interpretation:value.score>=.6?'你们为生活选下了一些相似的风景。可以从彼此喜欢的事物开始认识。':'你们为生活留下了不同的风景。能否相处，需要在真实交流中慢慢了解。',basis:'双方确认的品味选择相似度；不是相爱概率或心理测评',compared:value.compared};}
 };
}
