import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createService} from './service.js';
import {baseMirror,baseIslandMirror,PROMPTS,predictMbti} from './reflection.js';
const answers=Object.fromEntries(PROMPTS.map(q=>[q.key,q.options[0]]));
const reject=(fn,status)=>assert.throws(fn,e=>e.status===status);
function fixture(path=':memory:'){const s=createService(path),a=s.register('甲'),b=s.register('乙');return {s,a,b,c:s.auth(a.token),d:s.auth(b.token)};}
function create(s,c,a=answers){const draft=s.reflection.draft(c,a,0,true);return s.reflection.saveDraft(c,draft,baseMirror(a));}
function confirm(s,c,r,matchingConsent=false,correction=''){return s.reflection.confirm(c,{revision:r.revision,verdict:correction?'corrected':'accepted',correction,mbti:'INFP',matchingConsent});}
test('island reflection is derived from the saved design instead of a second questionnaire',()=>{const {s,c}=fixture();try{const island=s.me(c).island;s.savePreferences(c,{growing:true,world:'ocean',variant:2,animals:'cat',light:'night',home:'floating',landscape:'flowers'},island.revision,true);const draft=s.reflection.draftIsland(c,'我想给猫留一扇看海的窗');assert.equal(draft.mode,'island-design');assert.match(draft.answers.world,/海/);assert.match(draft.answers.animals,/猫/);assert.match(draft.answers.expression,/看海的窗/);assert.match(draft.answers.scene,/cat/);assert.equal('space' in draft.answers,false);const saved=s.reflection.saveDraft(c,draft,baseIslandMirror(draft.answers));assert.equal(saved.confirmed,false);assert.equal(saved.profile.mbti_predicted,null);assert.equal(saved.profile.mbti_prediction.basis,'island_design');assert(saved.profile.mbti_prediction.dimensions.every(item=>item.letter===null||item.evidence.length>=2));assert.equal(saved.profile.psychometricStatus,'not_assessed');}finally{s.db.close();}});
test('reflection needs consent, keeps the MBTI guess separate from self-report and only confirmation writes memory',()=>{const {s,c,d,a}=fixture();try{reject(()=>s.reflection.draft(c,answers,0,false),400);reject(()=>s.reflection.draft(c,{...answers,time:''},0,true),400);const r=create(s,c);assert.equal(r.confirmed,false);assert.equal(r.profile.mbti_predicted,null);assert.equal(r.profile.emotional_stability,null);assert.equal(s.memory(c).total,0);reject(()=>s.reflection.get(d,a.userId),403);const agent=s.auth(s.issueAgent(c,a.islandId,['memory:read']).token);reject(()=>s.reflection.get(agent),403);const p=confirm(s,c,r,false,'雨只是我喜欢的声音，不能代表我的心情');assert.equal(p.profile.mbti,'INFP');assert.equal(p.profile.mbti_source,'self_report');assert.equal(p.profile.mbti_predicted,r.profile.mbti_predicted);assert.equal(s.memory(c).total,1);assert.match(s.memory(c).narratives[0].originals[0].content,/不能代表我的心情/);reject(()=>confirm(s,c,r),409);}finally{s.db.close();}});
test('MBTI prediction uses multiple island details for each axis',()=>{const prediction=predictMbti({world:'漂浮在宇宙里的梦境',water:'从天而降的瀑布',animals:'三只独角兽',light:'夜晚更长',home:'不要房子，完全开放',landscape:'会自由生长的花园',expression:'欢迎朋友来实现愿望'});assert.equal(prediction.type,'ENFP');assert(prediction.dimensions.every(item=>item.evidence.length>=2));assert(prediction.confidence>=.48&&prediction.confidence<=.82);});
test('late model results cannot replace a newer draft or a logged-out user profile',()=>{const {s,c}=fixture();try{const draft=s.reflection.draft(c,answers,0,true);s.reflection.saveDraft(c,draft,baseMirror(answers));reject(()=>s.reflection.saveDraft(c,draft,baseMirror(answers)),409);const newer=s.reflection.draft(c,answers,1,true);s.logout(c);reject(()=>s.reflection.saveDraft(c,newer,baseMirror(answers)),401);}finally{s.db.close();}});
test('actual scene commits trigger a daily card once, favorite survives reopening, consent stops observation',()=>{const dir=mkdtempSync(join(tmpdir(),'reflection-test-'));let s;try{const f=fixture(join(dir,'db.sqlite'));s=f.s;const {c,a,d}=f;confirm(s,c,create(s,c));let i=s.me(c).island;i=s.patch(c,a.islandId,i.revision,[{type:'environment.set',value:{weather:i.scene.weather==='rain'?'clear':'rain'}}]);const cards=s.reflection.timeline(c);assert.equal(cards.length,1);assert.equal(cards[0].evidence[0].key,'weather');assert.equal(s.reflection.detect(c).triggered,false);i=s.patch(c,a.islandId,i.revision,[{type:'environment.set',value:{time:i.scene.time==='night'?'sunset':'night'}}]);assert.equal(s.reflection.timeline(c).length,1);reject(()=>s.reflection.card(d,cards[0].id,{favorite:true,response:null}),404);s.reflection.card(c,cards[0].id,{favorite:true,response:'只是想换一种天气'});s.db.close();s=createService(join(dir,'db.sqlite'));const restored=s.auth(a.token);assert.equal(s.reflection.timeline(restored)[0].favorite,true);assert.equal(s.reflection.timeline(restored)[0].response,'只是想换一种天气');s.reflection.settings(restored,{analysisConsent:false,matchingConsent:true});assert.equal(s.reflection.get(restored).matchingConsent,false);assert.equal(s.reflection.detect(restored).triggered,false);s.reflection.erase(restored);assert.equal(s.reflection.get(restored),null);assert.equal(s.reflection.timeline(restored).length,0);assert.equal(s.memory(restored).total,0);}finally{s?.db.close();rmSync(dir,{recursive:true,force:true});}});
test('taste matching requires both users opt in and discovery, never exports answers or guessed psychology',()=>{const {s,c,d,a,b}=fixture();try{const ra=create(s,c),rb=create(s,d);confirm(s,c,ra,true);confirm(s,d,rb,false);assert.equal(s.reflection.resonance(a.userId,b.userId),null);s.reflection.settings(d,{analysisConsent:true,matchingConsent:true});reject(()=>s.reflection.match(c,a.userId,b.userId),404);s.visibility(c,a.islandId,true);s.visibility(d,b.islandId,true);const result=s.reflection.match(c,a.userId,b.userId);assert.equal(result.compatibility,100);assert(!JSON.stringify(result).includes('boundary'));const world=s.world(c)[0];assert.equal(world.explanation.tasteUsed,true);s.reflection.settings(d,{analysisConsent:true,matchingConsent:false});assert.equal(s.world(c)[0].explanation.tasteUsed,false);s.block(d,a.userId);reject(()=>s.reflection.match(c,a.userId,b.userId),404);}finally{s.db.close();}});
test('music changes persist and trigger observations, corrected traits are excluded, discarded draft preserves history',()=>{const {s,c,d,a}=fixture();try{let r=create(s,c);r=confirm(s,c,r,true);s.reflection.listening(c,'original');assert.equal(s.reflection.listening(c).track,'original');assert.equal(s.reflection.timeline(c)[0].evidence[0].key,'listening');let draft=s.reflection.draft(c,{...answers,space:'一片海'},r.revision,true);let newer=s.reflection.saveDraft(c,draft,baseMirror(draft.answers));s.reflection.discard(c,newer.revision);assert.equal(s.reflection.get(c).confirmed,true);assert.equal(s.reflection.get(c).answers.space,answers.space);assert.equal(s.reflection.timeline(c).length,1);r=s.reflection.get(c);draft=s.reflection.draft(c,answers,r.revision,true);newer=s.reflection.saveDraft(c,draft,baseMirror(answers));confirm(s,c,newer,true,'我的品味变了');assert.equal(s.reflection.get(c).profile.taste.space.category,-1);assert.equal(s.reflection.brief(a.userId).userCorrection,'我的品味变了');s.reflection.settings(c,{analysisConsent:false,matchingConsent:false});assert.equal(s.reflection.brief(a.userId),null);}finally{s.db.close();}});
test('deleting or withdrawing while the model runs invalidates its response',()=>{const {s,c}=fixture();try{let draft=s.reflection.draft(c,answers,0,true);s.reflection.erase(c);reject(()=>s.reflection.saveDraft(c,draft,baseMirror(answers)),409);assert.equal(s.reflection.get(c),null);draft=s.reflection.draft(c,answers,0,true);s.reflection.settings(c,{analysisConsent:false,matchingConsent:false});reject(()=>s.reflection.saveDraft(c,draft,baseMirror(answers)),409);assert.equal(s.reflection.get(c),null);}finally{s.db.close();}});
