import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createService} from './service.js';
const obj=(id,roomId='room-main')=>({id,kind:'plant',roomId,x:1,y:0,z:1,rotation:0,color:'sage'});
function fixture(){const s=createService(':memory:');const a=s.register('A'),b=s.register('B');for(const person of [a,b]){const row=s.db.prepare('SELECT scene FROM islands WHERE id=?').get(person.islandId);const scene=JSON.parse(row.scene);scene.rooms=[{id:'room-main',name:'测试房间',width:8,depth:8,height:3}];s.db.prepare('UPDATE islands SET scene=? WHERE id=?').run(JSON.stringify(scene),person.islandId);}return {s,a,b,ca:s.auth(a.token),cb:s.auth(b.token)};}
const rejects=(fn,status)=>assert.throws(fn,e=>e.status===status);
function encounter(s,a,b){const pair=[a.islandId,b.islandId].sort();s.db.prepare('INSERT INTO encounters VALUES(?,?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),...pair,'2026-01-01',.3,99,.1,1,'{}',new Date().toISOString());}
test('credentials are scoped, hashed, revocable and expiring',()=>{const {s,a,b,ca}=fixture();const key=s.issueAgent(ca,a.islandId,['interior:write'],1),agent=s.auth(key.token);assert.notEqual(s.db.prepare('SELECT token_hash FROM credentials WHERE id=?').get(key.id).token_hash,key.token);rejects(()=>s.patch(agent,b.islandId,0,[{type:'object.upsert',value:obj('foreign')}]),403);rejects(()=>s.issueAgent(agent,a.islandId),403);rejects(()=>s.visibility(agent,a.islandId,true),403);rejects(()=>s.propose(agent,b.islandId),403);rejects(()=>s.round(agent),403);s.revoke(ca,key.id);rejects(()=>s.auth(key.token),401);const expired=s.issueAgent(ca,a.islandId);s.db.prepare('UPDATE credentials SET expires_at=? WHERE id=?').run('2000-01-01',expired.id);rejects(()=>s.auth(expired.token),401);s.db.close();});
test('email accounts sign in to the same island and onboarding is server-backed',()=>{
 const s=createService(':memory:'),created=s.registerAccount('小满','XIAOMAN@example.com','a-long-password');assert.equal(created.email,'xiaoman@example.com');assert.equal(created.onboardingComplete,false);assert.equal(s.db.prepare('SELECT password_hash FROM account_logins WHERE user_id=?').get(created.userId).password_hash.includes('a-long-password'),false);
 const session=s.session(s.auth(created.token));assert.equal(session.user.email,'xiaoman@example.com');assert.equal(session.onboardingComplete,false);rejects(()=>s.loginAccount('xiaoman@example.com','wrong-password'),401);rejects(()=>s.registerAccount('另一个','xiaoman@example.com','another-password'),409);
 const logged=s.loginAccount('XIAOMAN@example.com','a-long-password');assert.equal(logged.islandId,created.islandId);const c=s.auth(logged.token),i=s.me(c).island;s.savePreferences(c,{growing:true,water:'none',animals:'none',light:'balanced',home:'open',landscape:'none'},i.revision,false);assert.equal(s.session(c).onboardingComplete,true);assert.equal(s.preferences(c),null);
 s.logout(c);rejects(()=>s.auth(logged.token),401);s.db.close();
});
test('an existing prototype island can be claimed by a new login',()=>{
 const s=createService(':memory:'),legacy=s.register('旧岛主'),before=s.me(s.auth(legacy.token)).island;rejects(()=>s.session(s.auth(legacy.token)),401);
 const claimed=s.claimAccount(s.auth(legacy.token),'岛主的新名字','owner@example.com','claim-this-island');assert.equal(claimed.islandId,before.id);rejects(()=>s.auth(legacy.token),401);
 const logged=s.loginAccount('owner@example.com','claim-this-island');assert.equal(logged.islandId,before.id);assert.equal(s.me(s.auth(logged.token)).user.name,'岛主的新名字');s.db.close();
});
test('scene validation is atomic, uses optimistic versions and protects area permissions',()=>{const {s,a,ca}=fixture();const agent=s.auth(s.issueAgent(ca,a.islandId,['interior:write']).token);let r=s.patch(agent,a.islandId,0,[{type:'object.upsert',value:obj('one')}]);assert.equal(r.revision,1);rejects(()=>s.patch(agent,a.islandId,0,[{type:'object.remove',id:'one'}]),409);rejects(()=>s.patch(agent,a.islandId,1,[{type:'object.upsert',value:obj('one',null)}]),403);rejects(()=>s.patch(agent,a.islandId,1,[{type:'object.upsert',value:obj('valid')},{type:'object.upsert',value:{...obj('bad'),x:900}}]),400);assert.equal(s.read(ca,a.islandId).revision,1);assert(!s.read(ca,a.islandId).scene.objects.some(o=>o.id==='valid'));rejects(()=>s.patch(ca,a.islandId,1,[{type:'execute',code:'process.exit()'}]),400);rejects(()=>s.patch(ca,a.islandId,1,[{type:'object.upsert',value:{...obj('evil'),script:'fetch()'}}]),400);rejects(()=>s.patch(agent,a.islandId,1,[{type:'room.remove',id:'room-main'}]),400);s.db.close();});
test('rooms and furniture survive reopening the SQLite database',()=>{const dir=mkdtempSync(join(tmpdir(),'island-'));try{const path=join(dir,'db.sqlite');let s=createService(path);const a=s.register('持久化'),c=s.auth(a.token);s.patch(c,a.islandId,0,[{type:'room.upsert',value:{id:'library',name:'书房',width:10,depth:8,height:3}},{type:'object.upsert',value:obj('saved','library')}]);s.db.close();s=createService(path);const r=s.read(s.auth(a.token),a.islandId);assert.equal(r.revision,1);assert(r.scene.objects.some(o=>o.id==='saved'));s.db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('discovery is opt-in, probability bounded, and daily draws cannot be rerolled',()=>{const {s,a,b,ca,cb}=fixture();assert.equal(s.world(ca).length,0);s.visibility(cb,b.islandId,true);assert.equal(s.world(ca)[0].probability,0);s.visibility(ca,a.islandId,true);const f=s.world(ca)[0];assert(f.probability>=.03&&f.probability<=.3);const r=s.round(ca);assert.equal(r.alreadyRun,false);const first=s.db.prepare('SELECT * FROM encounters').all();assert.equal(first.length,1);assert.equal(s.round(cb).alreadyRun,true);assert.deepEqual(s.db.prepare('SELECT * FROM encounters').all(),first);s.db.close();});
test('merge requires a prior encounter and independent consent, with no ownership changes',()=>{const {s,a,b,ca,cb}=fixture();s.visibility(ca,a.islandId,true);s.visibility(cb,b.islandId,true);rejects(()=>s.propose(ca,b.islandId),409);encounter(s,a,b);const bond=s.propose(ca,b.islandId);rejects(()=>s.respond(ca,bond.id,true),403);rejects(()=>s.propose(cb,a.islandId),409);assert.equal(s.respond(cb,bond.id,true).status,'active');assert.equal(s.read(ca,a.islandId).owner_id,a.userId);assert.equal(s.read(cb,b.islandId).owner_id,b.userId);assert(s.space(ca,bond.id).id);rejects(()=>s.respond(cb,bond.id,true),409);s.db.close();});
test('separation returns every shared asset to its creator and preserves both personal islands',()=>{const {s,a,b,ca,cb}=fixture();s.visibility(ca,a.islandId,true);s.visibility(cb,b.islandId,true);encounter(s,a,b);const bond=s.propose(ca,b.islandId);s.respond(cb,bond.id,true);const originalA=s.read(ca,a.islandId).scene,originalB=s.read(cb,b.islandId).scene;let space=s.putShared(ca,bond.id,0,obj('a-shared',null));rejects(()=>s.putShared(cb,bond.id,space.revision,obj('a-shared',null)),403);space=s.putShared(cb,bond.id,space.revision,obj('b-shared',null));s.separate(cb,bond.id);assert.equal(s.me(ca).inventory.length,1);assert.equal(s.me(cb).inventory.length,1);assert.equal(s.space(ca,bond.id).objects.length,0);assert.equal(s.space(ca,bond.id).archived,1);assert.deepEqual(s.read(ca,a.islandId).scene,originalA);assert.deepEqual(s.read(cb,b.islandId).scene,originalB);rejects(()=>s.putShared(ca,bond.id,space.revision,obj('late',null)),409);rejects(()=>s.separate(ca,bond.id),409);const returned=s.me(ca).inventory[0];rejects(()=>s.restore(cb,returned.id,0,{roomId:'room-main',x:0,y:0,z:0,rotation:0}),404);rejects(()=>s.restore(ca,returned.id,0,{roomId:'room-main',x:100,y:0,z:0,rotation:0}),400);assert.equal(s.me(ca).inventory.length,1);s.restore(ca,returned.id,0,{roomId:'room-main',x:0,y:0,z:0,rotation:0});assert.equal(s.me(ca).inventory.length,0);assert.equal(s.read(ca,a.islandId).scene.objects.length,originalA.objects.length+1);s.db.close();});
test('blocking hides discovery and terminates a bond, including pending invitations',()=>{const {s,a,b,ca,cb}=fixture();s.visibility(ca,a.islandId,true);s.visibility(cb,b.islandId,true);encounter(s,a,b);const bond=s.propose(ca,b.islandId);s.block(cb,a.userId);assert.equal(s.world(ca).length,0);assert.equal(s.me(ca).bonds[0].status,'separated');rejects(()=>s.respond(cb,bond.id,true),409);rejects(()=>s.propose(ca,b.islandId),403);s.db.close();});
test('agent daily write quota is enforced without consuming extra versions',()=>{const {s,a,ca}=fixture();const agent=s.auth(s.issueAgent(ca,a.islandId,['interior:write']).token);for(let i=0;i<100;i++)s.patch(agent,a.islandId,i,[{type:'object.upsert',value:obj('quota')}]);rejects(()=>s.patch(agent,a.islandId,100,[{type:'object.remove',id:'quota'}]),429);assert.equal(s.read(ca,a.islandId).revision,100);s.db.close();});
test('new islands start as ecosystems without a house or room',()=>{const s=createService(':memory:');const a=s.register('森林');const scene=s.read(s.auth(a.token),a.islandId).scene;assert.equal(scene.rooms.length,0);assert(scene.objects.some(o=>o.kind==='river'));assert(!scene.objects.some(o=>o.kind==='house'));s.db.close();});
test('agent creation validates the entire scene, saves atomically and can be undone',()=>{const {s,a,ca}=fixture();const original=s.read(ca,a.islandId).scene;const job=s.beginCreation(ca,a.islandId,'变成湿地');rejects(()=>s.beginCreation(ca,a.islandId,'再改一次'),409);const scene=structuredClone(original);scene.ecosystem={biome:'wetland',season:'spring'};scene.objects.push(obj('ecology-agent',null));s.completeCreation(job.credential,job.jobId,scene,'湿地已生长');assert.equal(s.creation(ca,job.jobId).status,'completed');rejects(()=>s.completeCreation(job.credential,job.jobId,scene,'重复'),409);s.undoCreation(ca,a.islandId);assert.deepEqual(s.read(ca,a.islandId).scene,original);s.db.close();});
test('out-of-bounds or stale agent results cannot overwrite the island',()=>{const {s,a,ca}=fixture();const job=s.beginCreation(ca,a.islandId,'更多植物');const bad=structuredClone(job.scene);bad.objects.push({...obj('bad',null),x:200});rejects(()=>s.completeCreation(job.credential,job.jobId,bad,'坏结果'),400);assert.equal(s.read(ca,a.islandId).revision,0);s.patch(ca,a.islandId,0,[{type:'environment.set',value:{time:'night'}}]);rejects(()=>s.completeCreation(job.credential,job.jobId,job.scene,'旧结果'),409);s.failCreation(job.jobId,'旧版本');assert.equal(s.creation(ca,job.jobId).status,'failed');assert.equal(s.read(ca,a.islandId).scene.time,'night');s.db.close();});
test('guided preferences are private, explicit, revision-checked and removable',()=>{const {s,a,b,ca,cb}=fixture();const p={animals:'cat',light:'night',home:'floating',landscape:'flowers'};const saved=s.savePreferences(ca,p,0,true);assert.equal(saved.scene.daylight,'night');assert.equal(saved.scene.objects.filter(o=>o.kind==='cat').length,3);assert.equal(s.preferences(cb),null);assert.deepEqual(s.preferences(ca).payload,p);rejects(()=>s.savePreferences(ca,p,0,true),409);const agent=s.auth(s.issueAgent(ca,a.islandId).token);rejects(()=>s.preferences(agent),403);rejects(()=>s.savePreferences(ca,{...p,diagnosis:'insecure'},1,true),400);s.forgetPreferences(ca);assert.equal(s.preferences(ca),null);assert.deepEqual(s.read(ca,a.islandId).scene,saved.scene);s.db.close();});
test('external coding credentials isolate jobs, validate source, preserve versions and undo code',()=>{
 const {s,a,b,ca,cb}=fixture();const agent=s.auth(s.issueAgent(ca,a.islandId,['scene:write']).token);const indoor=s.auth(s.issueAgent(ca,a.islandId,['interior:write']).token);
 const job=s.beginCreation(ca,a.islandId,'write a moving boat');
 rejects(()=>s.codingTask(agent,b.islandId),403);rejects(()=>s.codingTask(indoor,a.islandId),403);
 assert.equal(s.codingTask(agent,a.islandId).task.id,job.jobId);
 rejects(()=>s.submitProgram(agent,a.islandId,job.jobId,'function {','bad'),400);assert.equal(s.read(ca,a.islandId).revision,0);
 const source="island.mesh({id:'boat',shape:'box',color:'#aaccdd'});";
 s.submitProgram(agent,a.islandId,job.jobId,source,'boat');assert.equal(s.read(ca,a.islandId).scene.program,source);
 rejects(()=>s.submitProgram(agent,a.islandId,job.jobId,source,'again'),404);
 s.undoCreation(ca,a.islandId);assert.equal(s.read(ca,a.islandId).scene.program,undefined);
 const stale=s.beginCreation(ca,a.islandId,'new code');s.patch(ca,a.islandId,s.read(ca,a.islandId).revision,[{type:'environment.set',value:{weather:'rain'}}]);
 rejects(()=>s.submitProgram(agent,a.islandId,stale.jobId,source,'stale'),409);s.db.close();
});
test('world starters save reproducible variants and can restore previous code',()=>{
 const {s,a,ca}=fixture();const before=s.read(ca,a.islandId).scene;
 for(const world of ['planet','ocean','desert','plain','forest','alpine','society']){
  const current=s.read(ca,a.islandId);const p={world,variant:42,animals:'cat',light:'night',home:'floating',landscape:'flowers'};
  const saved=s.savePreferences(ca,p,current.revision,true);assert.equal(saved.scene.worldTemplate,world);assert.equal(saved.scene.worldVariant,42);assert(saved.scene.program.includes('buildWorld'));assert.equal(s.preferences(ca).payload.world,world);
  s.undoCreation(ca,a.islandId);assert.deepEqual(s.read(ca,a.islandId).scene,before);
 }
 const revision=s.read(ca,a.islandId).revision;rejects(()=>s.savePreferences(ca,{world:'bad',variant:42,animals:'cat',light:'night',home:'floating',landscape:'flowers'},revision),400);s.db.close();
});
test('custom preferences preserve user text without inventing preset animals',()=>{
 const {s,a,ca}=fixture();const p={world:'custom',animals:'custom',light:'custom',home:'custom',landscape:'custom',custom:{world:'水母城',animals:'会发光的龙',light:'三次黄昏',home:'云里的住所',landscape:'天空的河'}};
 const result=s.savePreferences(ca,p,0,true);assert.equal(s.preferences(ca).payload.custom.animals,'会发光的龙');assert(!result.scene.objects.some(o=>['rabbit','cat','house'].includes(o.kind)));
 rejects(()=>s.savePreferences(ca,{...p,custom:{...p.custom,animals:''}},result.revision),400);
 rejects(()=>s.savePreferences(ca,{...p,custom:{...p.custom,animals:'x'.repeat(241)}},result.revision),400);
 s.forgetPreferences(ca);assert.equal(s.preferences(ca),null);s.db.close();
});
test('guided growth starts bare and only adds the chosen water and life',()=>{
 const {s,a,ca}=fixture();const p={growing:true,water:'none',animals:'none',light:'balanced',home:'open',landscape:'none'};
 let i=s.savePreferences(ca,p,0);assert.equal(i.scene.growing,true);assert.equal(i.scene.objects.length,0);assert.equal(i.scene.program,undefined);
 i=s.savePreferences(ca,{...p,water:'waterfall'},i.revision);assert.deepEqual(i.scene.objects.map(o=>o.kind).sort(),['river','waterfall']);
 i=s.savePreferences(ca,{...p,water:'pond',animals:'rabbit'},i.revision);assert.equal(i.scene.objects.filter(o=>o.kind==='rabbit').length,3);assert(i.scene.objects.some(o=>o.kind==='pond'));assert(!i.scene.objects.some(o=>o.kind==='house'||o.kind==='tree'));
 s.db.close();
});

test('account memory is structured, weighted, amendable, deletable and isolated',()=>{
 const {s,a,b,ca,cb}=fixture(),p={growing:true,water:'river',animals:'cat',light:'night',home:'open',landscape:'forest'};
 s.savePreferences(ca,p,0,true);const own=s.memory(ca);assert.equal(own.settings.matchingEnabled,false);assert.equal(own.narratives.length,1);assert.equal(own.narratives[0].ntype,'preference');assert.equal(own.narratives[0].weight,.66);assert(own.narratives[0].source_links.length===1);assert.equal(s.memory(cb).narratives.length,0);
 const added=s.writeMemory(ca,{content:'我喜欢夜里的森林和河流',tags:['森林','夜','河流'],importance:5,emotional:4,recurrence:3,unresolved:1});assert.equal(added.weight,.73);
 const amendment=s.amendMemory(ca,added.id,'现在也愿意邀请别人来散步','对陪伴的理解改变了');assert.equal(amendment.narrativeId,added.id);assert.equal(s.memory(ca).narratives.find(x=>x.id===added.id).amendments.length,1);
 rejects(()=>s.deleteMemory(cb,added.id),404);const agent=s.auth(s.issueAgent(ca,a.islandId).token);rejects(()=>s.memory(agent),403);s.deleteMemory(ca,added.id);assert(!s.memory(ca).narratives.some(x=>x.id===added.id));s.db.close();
});

test('relationship calculation uses memory only after both accounts opt in and never exposes raw text',()=>{
 const {s,a,b,ca,cb}=fixture();s.visibility(ca,a.islandId,true);s.visibility(cb,b.islandId,true);
 s.writeMemory(ca,{content:'只属于 A 的秘密原文',gesture:'喜欢在夜里的森林散步',tags:['森林','夜','陪伴']});s.writeMemory(cb,{content:'只属于 B 的秘密原文',gesture:'喜欢在在星夜的树林散步',tags:['森林','夜','陪伴']});
 let score=s.world(ca)[0];assert.equal(score.explanation.memoryUsed,false);assert.equal(score.explanation.authorizedMemories,0);
 s.memoryMatching(ca,true);score=s.world(ca)[0];assert.equal(score.explanation.memoryUsed,false);
 s.memoryMatching(cb,true);score=s.world(ca)[0];assert.equal(score.explanation.memoryUsed,true);assert.equal(score.explanation.authorizedMemories,2);assert(score.explanation.memoryResonance>=90);assert(!JSON.stringify(score).includes('秘密原文'));
 s.round(ca);const saved=s.db.prepare('SELECT components,algorithm_version FROM relationship_scores').get();assert.equal(saved.algorithm_version,'island-memory-v2');assert.equal(JSON.parse(saved.components).memoryUsed,true);s.db.close();
});

test('existing account preferences are backfilled once without enabling matching',()=>{const dir=mkdtempSync(join(tmpdir(),'island-memory-'));try{const path=join(dir,'db.sqlite');let s=createService(path),a=s.register('旧账号'),c=s.auth(a.token),p={growing:true,water:'pond',animals:'bird',light:'day',home:'open',landscape:'meadow'};s.savePreferences(c,p,0,true);s.db.exec('DELETE FROM memory_narratives; DELETE FROM memory_context;');s.db.close();s=createService(path);c=s.auth(a.token);assert.equal(s.memory(c).narratives.length,1);assert.equal(s.memory(c).settings.matchingEnabled,false);s.db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
