import {validateProgram,PROGRAM_GUIDE} from './island-program.js';
import {validPreferences,applyPreferences,preferenceDescription} from './preferences.js';
import {ecologyKinds,starterEcosystem} from './ecosystem.js';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomUUID,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
const uid=()=>randomUUID(),now=()=>new Date().toISOString(),hash=s=>createHash('sha256').update(s).digest('hex');
export class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,m)=>{throw new ApiError(status,m);};
const assert=(v,m)=>{if(!v)fail(400,m);};
const text=(s,n=80)=>typeof s==='string'&&s.trim().length>0&&s.length<=n;
const emailOf=value=>typeof value==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim())?value.trim().toLowerCase():null;
function passwordDigest(password,salt){return scryptSync(password,salt,64).toString('hex');}
const kinds=['cat','tree','pine','bench','lamp','house','rock','bed','desk','bookshelf','plant','sofa','piano',...ecologyKinds];
const colors=['sage','cream','rose','blue','wood'];
const memorySources=['onboarding','agent_dialogue','island_change','relationship','user_note'];
const memoryTypes=['preference','creation','relationship','reflection','general'];
const memoryDimensions={nature:['森林','树','草','花','自然','woodland','forest','meadow','landscape:forest','landscape:flowers','landscape:meadow'],water:['水','河','溪','湖','海','雨','瀑布','water','river','pond','waterfall','ocean'],night:['夜','星','月','黄昏','night','light:night'],home:['家','住所','房子','小屋','安稳','home:cottage','home:floating'],animals:['动物','猫','兔','鸟','生命','cat','rabbit','bird'],exploration:['旅行','探索','远方','冒险','宇宙','天空','漂浮','planet'],creativity:['创造','想象','音乐','书','艺术','发光','奇怪','独特'],connection:['陪伴','相遇','共同','一起','关系','拥抱','爱','来访']};
function memoryWeight({importance=3,emotional=3,recurrence=3,unresolved=1}={}){for(const value of [importance,emotional,recurrence,unresolved])assert(Number.isInteger(value)&&value>=1&&value<=5,'记忆权重需为 1–5');return Math.round(((importance*.35+emotional*.25+recurrence*.25+unresolved*.15)/5)*1000)/1000;}
function safeStringArray(value,max=20){assert(Array.isArray(value)&&value.length<=max&&value.every(v=>text(v,80)),'记忆标签格式无效');return [...new Set(value.map(v=>v.trim()))];}
export const RULES={version:1,maxRooms:8,maxObjects:200,islandRadius:10,maxHeight:12,roomMaxSize:12,maxBatchActions:30,agentDailyWrites:100,agentMaxDays:30,objectKinds:kinds,palette:colors,programSDK:PROGRAM_GUIDE,codeExecution:'isolated-browser-worker',ownership:'个人岛及物件始终属于原主人；合岛只创建可分离的共同空间。'};
const initialScene=()=>({weather:'clear',time:'sunset',music:'forest',rooms:[{id:'room-main',name:'我的小屋',width:8,depth:8,height:3}],objects:[{id:uid(),kind:'bed',roomId:'room-main',x:-2,y:0,z:-2,rotation:0,color:'cream'},{id:uid(),kind:'desk',roomId:'room-main',x:2,y:0,z:-2,rotation:0,color:'wood'},{id:uid(),kind:'plant',roomId:'room-main',x:2,y:0,z:2,rotation:0,color:'sage'}]});
function validateScene(s){assert(s&&typeof s==='object','场景格式无效');assert(Object.keys(s).every(k=>['weather','time','music','rooms','objects','ecosystem','daylight','program','worldTemplate','worldVariant','growing'].includes(k)),'场景包含未知字段');if(s.growing!==undefined)assert(typeof s.growing==='boolean','地形模式无效');if(s.worldTemplate!==undefined)assert(['planet','ocean','forest','society'].includes(s.worldTemplate),'世界类型无效');if(s.worldVariant!==undefined)assert(Number.isInteger(s.worldVariant)&&s.worldVariant>=0&&s.worldVariant<=9999,'世界变体无效');if(s.program!==undefined)validateProgram(s.program);if(s.daylight!==undefined)assert(['day','night','balanced'].includes(s.daylight),'昼夜偏好无效');if(s.ecosystem)assert(Object.keys(s.ecosystem).every(k=>['biome','season'].includes(k))&&['woodland','meadow','wetland','alpine'].includes(s.ecosystem.biome)&&['spring','summer','autumn','winter'].includes(s.ecosystem.season),'生态设置无效');assert(['clear','rain','rainbow'].includes(s.weather)&&['sunset','night'].includes(s.time)&&['forest','piano','ambient'].includes(s.music),'环境设置不在允许范围内');assert(Array.isArray(s.rooms)&&s.rooms.length<=8&&Array.isArray(s.objects)&&s.objects.length<=200,'房间或物件数量超限');const ids=new Set();for(const r of s.rooms){assert(text(r.id)&&!ids.has(r.id)&&text(r.name),'房间编号或名称无效');ids.add(r.id);assert(['width','depth','height'].every(k=>Number.isFinite(r[k])&&r[k]>=2&&r[k]<=(k==='height'?6:12)),'房间尺寸超限');assert(Object.keys(r).every(k=>['id','name','width','depth','height'].includes(k)),'房间含未授权属性');}const objects=new Set();for(const o of s.objects){assert(text(o.id)&&!objects.has(o.id)&&kinds.includes(o.kind)&&colors.includes(o.color),'物件类型、颜色或编号无效');objects.add(o.id);assert(Object.keys(o).every(k=>['id','kind','roomId','x','y','z','rotation','color'].includes(k)),'物件含未授权属性');assert(['x','y','z','rotation'].every(k=>Number.isFinite(o[k])),'物件坐标无效');const room=o.roomId?s.rooms.find(r=>r.id===o.roomId):null;assert(!o.roomId||room,'物件所在房间不存在');assert(o.y>=0&&o.y<=(room?room.height-1:12),'物件高度越界');assert(room?(Math.abs(o.x)<=room.width/2-.6&&Math.abs(o.z)<=room.depth/2-.6):Math.hypot(o.x,o.z)<=9,'物件超出地皮或房间边界');}return s;}
export function createService(path='data/islands.sqlite'){
if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});const db=new DatabaseSync(path);db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));db.prepare('INSERT OR IGNORE INTO settings VALUES (?,?)').run('encounter-secret',randomBytes(32).toString('hex'));
for(const row of db.prepare('SELECT id,scene FROM islands').all()){const scene=JSON.parse(row.scene);if(!scene.ecosystem){scene.ecosystem={biome:'woodland',season:'spring'};if(!scene.objects.some(o=>!o.roomId))scene.objects.push(...starterEcosystem().objects.slice(0,Math.max(0,200-scene.objects.length)));db.prepare('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?').run(JSON.stringify(scene),row.id);}}
const get=(sql,...p)=>db.prepare(sql).get(...p),all=(sql,...p)=>db.prepare(sql).all(...p),run=(sql,...p)=>db.prepare(sql).run(...p);
function tx(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}
function issue(user,island,kind,scopes,days){const token=randomBytes(32).toString('base64url'),id=uid();run('INSERT INTO credentials VALUES (?,?,?,?,?,?,?,?,?)',id,user,island,kind,hash(token),JSON.stringify(scopes),new Date(Date.now()+days*86400000).toISOString(),null,now());return {id,token,expiresInDays:days};}
function auth(token){if(typeof token!=='string')fail(401,'缺少访问凭证');const c=get('SELECT * FROM credentials WHERE token_hash=?',hash(token));if(!c||c.revoked_at||c.expires_at<now())fail(401,'凭证无效、已撤销或已过期');c.scopes=JSON.parse(c.scopes);return c;}
function human(c){if(c.kind!=='human')fail(403,'这项操作只能由岛主本人执行，Agent 无权操作社交关系');}
function island(id){const i=get('SELECT * FROM islands WHERE id=?',id);if(!i)fail(404,'岛屿不存在');return {...i,scene:JSON.parse(i.scene),discoverable:!!i.discoverable};}
function own(c,id){const i=island(id);if(i.owner_id!==c.user_id||(c.kind==='agent'&&c.island_id!==id))fail(403,'只能修改授权的个人岛屿');return i;}
function audit(c,id,action,detail={}){run('INSERT INTO audit(actor_id,credential_id,island_id,action,detail,created_at) VALUES(?,?,?,?,?,?)',c.user_id,c.id,id,action,JSON.stringify(detail),now());}
function member(c,id){human(c);const b=get('SELECT * FROM bonds WHERE id=?',id);if(!b)fail(404,'关系不存在');if(![island(b.island_a).owner_id,island(b.island_b).owner_id].includes(c.user_id))fail(403,'你不是这段关系的参与者');return b;}
function blocked(a,b){return !!get('SELECT 1 FROM blocks WHERE (user_id=? AND blocked_user_id=?) OR (user_id=? AND blocked_user_id=?)',a,b,b,a);}
function recordMemory(userId,islandId,input){
 assert(input&&typeof input==='object','记忆格式无效');assert(memorySources.includes(input.source),'记忆来源无效');assert(memoryTypes.includes(input.type),'记忆类型无效');
 assert(text(input.content,4000)&&text(input.gesture,500)&&text(input.context,1200)&&text(input.direction,500),'记忆内容为空或过长');
 const tags=safeStringArray(input.tags||[]),entities=safeStringArray(input.relatedEntities||[],12),contextId=uid(),narrativeId=uid();
 const scores={importance:input.importance??3,emotional:input.emotional??3,recurrence:input.recurrence??2,unresolved:input.unresolved??1},weight=memoryWeight(scores);
 run('INSERT INTO memory_context VALUES(?,?,?,?,?,?,?)',contextId,userId,islandId,input.source,input.content,JSON.stringify(input.meta||{}),now());
 run('INSERT INTO memory_narratives VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',narrativeId,userId,islandId,input.type,input.gesture,input.context,input.direction,JSON.stringify(tags),JSON.stringify(entities),JSON.stringify([contextId]),scores.importance,scores.emotional,scores.recurrence,scores.unresolved,weight,now());
 return {id:narrativeId,weight,sourceLink:contextId};
}
function matchingMemory(userId){
 const enabled=!!get('SELECT matching_enabled FROM memory_settings WHERE user_id=?',userId)?.matching_enabled;if(!enabled)return {enabled:false,count:0,vector:null};
 const rows=all('SELECT gesture,context_layer,cognition_direction,tags,weight FROM memory_narratives WHERE user_id=? ORDER BY created_at DESC LIMIT 200',userId),keys=Object.keys(memoryDimensions),vector=keys.map(()=>.05);
 for(const row of rows){const corpus=`${row.gesture} ${row.context_layer} ${row.cognition_direction} ${JSON.parse(row.tags).join(' ')}`.toLowerCase();keys.forEach((key,index)=>{const hits=memoryDimensions[key].filter(word=>corpus.includes(word)).length;if(hits)vector[index]+=row.weight*Math.min(2,hits);});}
 return {enabled:true,count:rows.length,vector};
}
function cosine(a,b){return a.reduce((sum,value,index)=>sum+value*b[index],0)/(Math.hypot(...a)*Math.hypot(...b));}
function endBond(c,b){run("UPDATE bonds SET status='separated',ended_at=? WHERE id=?",now(),b.id);const ia=island(b.island_a),ib=island(b.island_b),space=get('SELECT * FROM shared_spaces WHERE bond_id=?',b.id);if(space){for(const o of all('SELECT * FROM shared_objects WHERE space_id=?',space.id))run('INSERT INTO returned_objects VALUES(?,?,?,?,?)',uid(),o.owner_id,space.id,o.payload,now());run('DELETE FROM shared_objects WHERE space_id=?',space.id);run('UPDATE shared_spaces SET archived=1 WHERE id=?',space.id);}for(const [self,other] of [[ia,ib],[ib,ia]])recordMemory(self.owner_id,self.id,{source:'relationship',type:'relationship',content:`与「${other.name}」结束共同生活，个人岛与个人记忆保持独立。`,gesture:'两座岛结束合并，各自带回属于自己的事物',context:'双方共同空间已经归档',direction:'保留经历，但重新拥有完整的个人边界',tags:['关系','分开','边界'],relatedEntities:[other.owner_id],importance:5,emotional:5,recurrence:2,unresolved:3});audit(c,null,'bond.separated',{bondId:b.id});}
function profile(i){const s=i.scene,objects=s.objects,n=objects.length||1;return [objects.filter(o=>['tree','pine','plant','rock','flowers','grass','mushroom','bird','rabbit','pond','river'].includes(o.kind)).length/n,objects.filter(o=>['bed','sofa','house','lamp'].includes(o.kind)).length/n,objects.filter(o=>['bookshelf','desk','piano'].includes(o.kind)).length/n,s.weather==='rain'?1:.2,s.time==='night'?1:.2,s.music==='piano'?1:s.music==='ambient'?.6:.2].map(x=>x+.1);}
function forecast(a,b){const va=profile(a),vb=profile(b),ecology=cosine(va,vb),ma=matchingMemory(a.owner_id),mb=matchingMemory(b.owner_id),memory=ma.vector&&mb.vector?cosine(ma.vector,mb.vector):null,combined=memory===null?ecology:ecology*.65+memory*.35,last=get('SELECT day FROM encounters WHERE island_a=? AND island_b=? AND occurred=1 ORDER BY day DESC LIMIT 1',...[a.id,b.id].sort()),cooling=last&&(Date.now()-new Date(last.day).getTime())<7*86400000,probability=cooling?0:Math.round((.03+.27*combined**3)*1000)/1000,compatibility=Math.round(combined*100);return {compatibility,probability,distance:Math.round(20+80*(1-combined)),explanation:{algorithm:'island-memory-v2',ecology:Math.round(ecology*100),memoryResonance:memory===null?null:Math.round(memory*100),authorizedMemories:memory===null?0:ma.count+mb.count,memoryUsed:memory!==null,baseChance:.03,maxChance:.3,cooldownDays:7,cooling:!!cooling,privacy:'只计算双方明确授权的记忆主题权重，不向对方公开记忆原文',unit:'每个 UTC 日一次世界轮次；同一对岛当天仅抽签一次'}};}
for(const row of all("SELECT p.user_id,p.payload,i.id island_id FROM user_preferences p JOIN islands i ON i.owner_id=p.user_id WHERE NOT EXISTS(SELECT 1 FROM memory_narratives m WHERE m.user_id=p.user_id AND m.ntype='preference')")){try{const p=JSON.parse(row.payload),tags=Object.entries(p).filter(([key,value])=>key!=='custom'&&['string','number','boolean'].includes(typeof value)).map(([key,value])=>`${key}:${value}`);recordMemory(row.user_id,row.island_id,{source:'onboarding',type:'preference',content:preferenceDescription(p),gesture:'为自己的岛选择了第一批水、生命、光和风景',context:'从已有账号偏好回填的 onboarding 记忆',direction:'从一座空岛开始，把喜欢逐渐变成可见的生态',tags,importance:4,emotional:3,recurrence:4,unresolved:1});}catch{}}
return {db,rules:RULES,
register(name){assert(text(name,30),'名字需为 1–30 字');return tx(()=>{const user=uid(),id=uid();run('INSERT INTO users VALUES(?,?,?)',user,name.trim(),now());run('INSERT INTO islands VALUES(?,?,?,?,?,?,?)',id,user,`${name.trim()}的岛`,0,0,JSON.stringify(starterEcosystem()),now());return {userId:user,islandId:id,...issue(user,id,'human',['owner'],365)};});},
registerAccount(name,email,password){
 const normalized=emailOf(email);assert(text(name,30),'名字需为 1–30 字');assert(normalized,'请输入有效邮箱');assert(typeof password==='string'&&password.length>=8&&password.length<=128,'密码需为 8–128 个字符');
 if(get('SELECT 1 FROM account_logins WHERE email=?',normalized))fail(409,'这个邮箱已经注册，请直接登录');
 return tx(()=>{const user=uid(),id=uid(),salt=randomBytes(16).toString('hex');run('INSERT INTO users VALUES(?,?,?)',user,name.trim(),now());run('INSERT INTO islands VALUES(?,?,?,?,?,?,?)',id,user,`${name.trim()}的岛`,0,0,JSON.stringify(starterEcosystem()),now());run('INSERT INTO account_logins VALUES(?,?,?,?,?)',user,normalized,salt,passwordDigest(password,salt),now());const session=issue(user,id,'human',['owner'],30);return {userId:user,islandId:id,name:name.trim(),email:normalized,onboardingComplete:false,...session};});
 },
 loginAccount(email,password){
 const normalized=emailOf(email);assert(normalized&&typeof password==='string','邮箱或密码不正确');const row=get('SELECT l.*,u.name,i.id island_id FROM account_logins l JOIN users u ON u.id=l.user_id JOIN islands i ON i.owner_id=l.user_id WHERE l.email=?',normalized);
 const candidate=passwordDigest(password,row?.password_salt||'00000000000000000000000000000000'),expected=Buffer.from(row?.password_hash||'00'.repeat(64),'hex'),actual=Buffer.from(candidate,'hex');if(!row||expected.length!==actual.length||!timingSafeEqual(expected,actual))fail(401,'邮箱或密码不正确');
 const session=issue(row.user_id,row.island_id,'human',['owner'],30);return {userId:row.user_id,islandId:row.island_id,name:row.name,email:normalized,onboardingComplete:!!get("SELECT 1 FROM audit WHERE actor_id=? AND action='preferences.saved'",row.user_id),...session};
 },
 claimAccount(c,name,email,password){
 human(c);const normalized=emailOf(email);assert(text(name,30),'名字需为 1–30 字');assert(normalized,'请输入有效邮箱');assert(typeof password==='string'&&password.length>=8&&password.length<=128,'密码需为 8–128 个字符');
 if(get('SELECT 1 FROM account_logins WHERE user_id=?',c.user_id))fail(409,'这座岛已经绑定账号');if(get('SELECT 1 FROM account_logins WHERE email=?',normalized))fail(409,'这个邮箱已经注册，请直接登录');
 const islandId=get('SELECT id FROM islands WHERE owner_id=?',c.user_id)?.id;if(!islandId)fail(404,'找不到需要继承的岛');
 return tx(()=>{const salt=randomBytes(16).toString('hex');run('UPDATE users SET name=? WHERE id=?',name.trim(),c.user_id);run('INSERT INTO account_logins VALUES(?,?,?,?,?)',c.user_id,normalized,salt,passwordDigest(password,salt),now());run('UPDATE credentials SET revoked_at=? WHERE id=?',now(),c.id);const next=issue(c.user_id,islandId,'human',['owner'],30);return {userId:c.user_id,islandId,name:name.trim(),email:normalized,onboardingComplete:!!get("SELECT 1 FROM audit WHERE actor_id=? AND action='preferences.saved'",c.user_id),...next};});
 },
 session(c){human(c);const login=get('SELECT email FROM account_logins WHERE user_id=?',c.user_id);if(!login)fail(401,'请重新登录');const user=get('SELECT id,name FROM users WHERE id=?',c.user_id);return {user:{...user,email:login.email},onboardingComplete:!!get("SELECT 1 FROM audit WHERE actor_id=? AND action='preferences.saved'",c.user_id)};},
 logout(c){human(c);run('UPDATE credentials SET revoked_at=? WHERE id=?',now(),c.id);return {loggedOut:true};},
auth,
memory(c){human(c);const rows=all('SELECT * FROM memory_narratives WHERE user_id=? ORDER BY created_at DESC LIMIT 200',c.user_id).map(row=>({...row,tags:JSON.parse(row.tags),related_entities:JSON.parse(row.related_entities),source_links:JSON.parse(row.source_links),amendments:all('SELECT id,content,reason,created_at FROM memory_amendments WHERE narrative_id=? AND user_id=? ORDER BY created_at',row.id,c.user_id)}));return {settings:{matchingEnabled:!!get('SELECT matching_enabled FROM memory_settings WHERE user_id=?',c.user_id)?.matching_enabled},narratives:rows,selfConcept:all('SELECT field,content,updated_at FROM memory_self_concept WHERE user_id=?',c.user_id)};},
writeMemory(c,input){human(c);const islandId=get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id;return tx(()=>{const result=recordMemory(c.user_id,islandId,{source:'user_note',type:input?.type||'general',content:input?.content,gesture:input?.gesture||input?.content,context:input?.context||'用户主动写下的岛屿记忆',direction:input?.direction||'把当下的感受留给未来的自己',tags:input?.tags||[],relatedEntities:input?.relatedEntities||[],importance:input?.importance,emotional:input?.emotional,recurrence:input?.recurrence,unresolved:input?.unresolved});audit(c,islandId,'memory.written',{memoryId:result.id});return result;});},
amendMemory(c,id,content,reason=''){human(c);assert(text(content,1000)&&(!reason||text(reason,500)),'修订内容无效');const memory=get('SELECT id FROM memory_narratives WHERE id=? AND user_id=?',id,c.user_id);if(!memory)fail(404,'记忆不存在');const amendmentId=uid();run('INSERT INTO memory_amendments VALUES(?,?,?,?,?,?)',amendmentId,id,c.user_id,content.trim(),String(reason||'').trim(),now());return {id:amendmentId,narrativeId:id};},
deleteMemory(c,id){human(c);const memory=get('SELECT source_links FROM memory_narratives WHERE id=? AND user_id=?',id,c.user_id);if(!memory)fail(404,'记忆不存在');return tx(()=>{run('DELETE FROM memory_narratives WHERE id=? AND user_id=?',id,c.user_id);for(const link of JSON.parse(memory.source_links))run('DELETE FROM memory_context WHERE id=? AND user_id=?',link,c.user_id);audit(c,null,'memory.deleted',{memoryId:id});return {deleted:true};});},
memoryMatching(c,enabled){human(c);assert(typeof enabled==='boolean','记忆匹配设置无效');run('INSERT INTO memory_settings VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET matching_enabled=excluded.matching_enabled,updated_at=excluded.updated_at',c.user_id,Number(enabled),now());audit(c,null,'memory.matching',{enabled});return {matchingEnabled:enabled};},
preferences(c){human(c);const row=get('SELECT payload,source,updated_at FROM user_preferences WHERE user_id=?',c.user_id);return row?{...row,payload:JSON.parse(row.payload)}:null;},
savePreferences(c,p,revision,remember=true){human(c);assert(validPreferences(p),'偏好选项无效');assert(typeof remember==='boolean','记忆设置无效');return tx(()=>{const i=island(get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id);if(i.revision!==revision)fail(409,'岛屿已改变，请刷新后再保存');const scene=applyPreferences(i.scene,p);validateScene(scene);if(remember){run("INSERT INTO user_preferences(user_id,payload,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at",c.user_id,JSON.stringify(p),now());const tags=Object.entries(p).filter(([key,value])=>key!=='custom'&&['string','number','boolean'].includes(typeof value)).map(([key,value])=>`${key}:${value}`);recordMemory(c.user_id,i.id,{source:'onboarding',type:'preference',content:preferenceDescription(p),gesture:'为自己的岛选择了第一批水、生命、光和风景',context:'账号 onboarding 中由用户亲自确认的选择',direction:'从一座空岛开始，把喜欢逐渐变成可见的生态',tags,importance:4,emotional:3,recurrence:4,unresolved:1});}else run('DELETE FROM user_preferences WHERE user_id=?',c.user_id);run('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?',JSON.stringify(scene),i.id);if(p.world||p.growing)run('INSERT INTO creations VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',uid(),i.id,c.user_id,c.id,i.revision,'选择世界起点','completed','已保存新的世界起点，可撤回本次替换。',null,JSON.stringify(i.scene),now(),now());audit(c,i.id,'preferences.saved',{remember});return island(i.id);});},
forgetPreferences(c){human(c);run('DELETE FROM user_preferences WHERE user_id=?',c.user_id);return {forgotten:true};},
me(c){human(c);const i=get('SELECT id FROM islands WHERE owner_id=?',c.user_id);return {latestCreation:get("SELECT x.id,x.status,x.summary,x.error FROM creations x JOIN credentials c ON c.id=x.credential_id WHERE x.owner_id=? AND c.kind='agent' ORDER BY x.created_at DESC,x.rowid DESC LIMIT 1",c.user_id)||null,user:get('SELECT * FROM users WHERE id=?',c.user_id),island:island(i.id),rules:RULES,agents:all("SELECT id,scopes,expires_at,revoked_at FROM credentials WHERE user_id=? AND kind='agent'",c.user_id),bonds:all('SELECT * FROM bonds WHERE island_a=? OR island_b=?',i.id,i.id),inventory:all('SELECT * FROM returned_objects WHERE owner_id=?',c.user_id)};},
read(c,id){const i=island(id);if(i.owner_id!==c.user_id&&!i.discoverable)fail(403,'这座岛未开放发现');if(blocked(c.user_id,i.owner_id))fail(403,'双方已屏蔽');return i;},
issueAgent(c,id,scopes=['scene:write','interior:write'],days=7){human(c);own(c,id);assert(Array.isArray(scopes)&&scopes.length>0&&scopes.every(s=>['scene:write','interior:write'].includes(s)),'无效的 Agent 权限');assert(Number.isInteger(days)&&days>=1&&days<=30,'授权有效期为 1–30 天');return tx(()=>{const key=issue(c.user_id,id,'agent',scopes,days);audit(c,id,'agent.issued',{credentialId:key.id,scopes,days});return key;});},
revoke(c,id){human(c);const key=get("SELECT * FROM credentials WHERE id=? AND user_id=? AND kind='agent'",id,c.user_id);if(!key)fail(404,'授权不存在');run('UPDATE credentials SET revoked_at=? WHERE id=?',now(),id);audit(c,key.island_id,'agent.revoked',{credentialId:id});return {revoked:true};},
patch(c,id,revision,actions){return tx(()=>{const i=own(c,id);if(i.revision!==revision)fail(409,'版本冲突，请重新读取岛屿后再修改');assert(Array.isArray(actions)&&actions.length>0&&actions.length<=30,'每批操作需为 1–30 项');if(c.kind==='agent'){const count=get("SELECT COUNT(*) n FROM audit WHERE credential_id=? AND action='scene.patch' AND created_at>=?",c.id,new Date().toISOString().slice(0,10)).n;if(count>=100)fail(429,'Agent 今日写入次数已达到上限');}const scene=structuredClone(i.scene);for(const a of actions){assert(a&&['object.upsert','object.remove','room.upsert','room.remove','environment.set'].includes(a.type),'操作不在授权规则内');const existing=scene.objects.find(o=>o.id===a.id||o.id===a.value?.id);const scopes=a.type.startsWith('room.')?['interior:write']:a.type==='environment.set'?['scene:write']:[...(existing?[existing.roomId?'interior:write':'scene:write']:[]),...(a.value?[a.value.roomId?'interior:write':'scene:write']:[])];if(c.kind==='agent'&&scopes.some(s=>!c.scopes.includes(s)))fail(403,'Agent 没有修改该区域的权限');if(a.type==='environment.set'){assert(a.value&&Object.keys(a.value).every(k=>['weather','time','music'].includes(k)),'环境含未授权属性');Object.assign(scene,a.value);}else{const list=a.type.startsWith('room.')?'rooms':'objects';if(a.type.endsWith('remove')){assert(text(a.id),'缺少目标编号');scene[list]=scene[list].filter(o=>o.id!==a.id);}else{assert(a.value&&text(a.value.id),'缺少物件或房间编号');scene[list]=scene[list].filter(o=>o.id!==a.value.id);scene[list].push(a.value);}}}validateScene(scene);run('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?',JSON.stringify(scene),id);audit(c,id,'scene.patch',{revision:revision+1,actions});return island(id);});},
visibility(c,id,value){human(c);own(c,id);assert(typeof value==='boolean','发现设置无效');run('UPDATE islands SET discoverable=? WHERE id=?',Number(value),id);audit(c,id,'discoverability',{value});return island(id);},
world(c){human(c);const ownIsland=island(get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id);return all('SELECT id FROM islands WHERE discoverable=1 AND owner_id<>?',c.user_id).map(r=>island(r.id)).filter(i=>!blocked(c.user_id,i.owner_id)).map(i=>({id:i.id,name:i.name,ownerId:i.owner_id,...forecast(ownIsland,i),...(!ownIsland.discoverable?{probability:0,explanation:{eligible:false,reason:'你的岛尚未开放发现'}}:{})}));},
round(c){human(c);return tx(()=>{const day=now().slice(0,10);if(get('SELECT day FROM encounter_rounds WHERE day=?',day))return {day,alreadyRun:true};const items=all('SELECT id FROM islands WHERE discoverable=1 ORDER BY id').map(i=>island(i.id));assert(items.length<=200,'当前本地版每轮最多支持 200 座开放岛屿');run('INSERT INTO encounter_rounds VALUES(?,?)',day,now());const secret=get('SELECT value FROM settings WHERE key=?','encounter-secret').value;let count=0;for(let a=0;a<items.length;a++)for(let b=a+1;b<items.length;b++){const i=items[a],j=items[b];if(blocked(i.owner_id,j.owner_id))continue;const f=forecast(i,j),users=[i.owner_id,j.owner_id].sort();run('INSERT INTO relationship_scores VALUES(?,?,?,?,?,?,?)',uid(),users[0],users[1],f.compatibility,JSON.stringify(f.explanation),'island-memory-v2',now());const draw=parseInt(hash(`${secret}:${day}:${i.id}:${j.id}`).slice(0,12),16)/0x1000000000000,happened=draw<f.probability;run('INSERT INTO encounters VALUES(?,?,?,?,?,?,?,?,?,?)',uid(),i.id,j.id,day,f.probability,f.compatibility,draw,Number(happened),JSON.stringify(f.explanation),now());if(happened)count++;}audit(c,null,'world.round',{day,count});return {day,occurred:count,alreadyRun:false};});},
encounters(c){human(c);const id=get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id;return all('SELECT id,island_a,island_b,day,probability,compatibility,occurred,explanation FROM encounters WHERE (island_a=? OR island_b=?) AND occurred=1 ORDER BY day DESC',id,id).filter(e=>!blocked(island(e.island_a).owner_id,island(e.island_b).owner_id)).map(e=>({...e,event:'两岛进入可拜访距离；双方收到相遇记录，可主动提出合岛。不会自动建立恋爱关系。'}));},
propose(c,target){human(c);const a=island(get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id),b=island(target);assert(a.id!==b.id,'不能与自己合岛');if(!a.discoverable||!b.discoverable||blocked(a.owner_id,b.owner_id))fail(403,'双方需开放发现且未屏蔽');return tx(()=>{if(get("SELECT 1 FROM bonds WHERE status IN ('pending','active') AND (island_a IN (?,?) OR island_b IN (?,?))",a.id,b.id,a.id,b.id))fail(409,'其中一座岛已有待处理邀请或合岛关系');const pair=[a.id,b.id].sort();if(!get('SELECT 1 FROM encounters WHERE island_a=? AND island_b=? AND occurred=1',...pair))fail(409,'双方需要先产生一次相遇记录');const id=uid();run('INSERT INTO bonds VALUES(?,?,?,?,?,?,?,?)',id,...pair,c.user_id,null,'pending',now(),null);audit(c,a.id,'bond.proposed',{bondId:id});return get('SELECT * FROM bonds WHERE id=?',id);});},
respond(c,id,accept){assert(typeof accept==='boolean','需要明确接受或拒绝');return tx(()=>{const b=member(c,id);if(b.status!=='pending')fail(409,'邀请已处理');if(b.proposed_by===c.user_id)fail(403,'不能代替对方同意');const ia=island(b.island_a),ib=island(b.island_b);if(blocked(ia.owner_id,ib.owner_id))fail(403,'双方已屏蔽');run('UPDATE bonds SET status=?,accepted_by=? WHERE id=?',accept?'active':'declined',c.user_id,id);if(accept){run('INSERT INTO shared_spaces VALUES(?,?,0,0)',uid(),id);for(const [self,other] of [[ia,ib],[ib,ia]])recordMemory(self.owner_id,self.id,{source:'relationship',type:'relationship',content:`与「${other.name}」共同建立了一座可以一起照料的岛。`,gesture:'两座岛在双方同意后开始共同生活',context:'保留各自个人岛的所有权，同时创建可分离的共同空间',direction:'两个人一起面对世界，也继续保有各自完整的内在地形',tags:['关系','共同','陪伴','合岛'],relatedEntities:[other.owner_id],importance:5,emotional:5,recurrence:4,unresolved:2});}audit(c,null,accept?'bond.accepted':'bond.declined',{bondId:id});return get('SELECT * FROM bonds WHERE id=?',id);});},
separate(c,id){return tx(()=>{const b=member(c,id);if(!['pending','active'].includes(b.status))fail(409,'关系已结束');endBond(c,b);return {separated:true,assets:'共同空间物件已按创作者归还个人收纳箱；原岛未改动'};});},
space(c,id){const b=member(c,id);const s=get('SELECT * FROM shared_spaces WHERE bond_id=?',b.id);if(!s)fail(404,'共同空间尚未创建');return {...s,objects:all('SELECT id,owner_id,payload FROM shared_objects WHERE space_id=?',s.id)};},
putShared(c,id,revision,object){return tx(()=>{const b=member(c,id);if(b.status!=='active')fail(409,'共同空间已关闭');const s=get('SELECT * FROM shared_spaces WHERE bond_id=?',id);if(s.revision!==revision)fail(409,'共同空间版本冲突');validateScene({...initialScene(),rooms:[],objects:[object]});assert(!object.roomId,'共同空间当前仅支持室外物件');const old=get('SELECT * FROM shared_objects WHERE id=?',object.id);if(old&&(old.owner_id!==c.user_id||old.space_id!==s.id))fail(403,'不能修改或覆盖他人的共同物件');assert(old||get('SELECT COUNT(*) n FROM shared_objects WHERE space_id=?',s.id).n<200,'共同空间物件已达上限');run('INSERT INTO shared_objects VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload',object.id,s.id,c.user_id,JSON.stringify(object));run('UPDATE shared_spaces SET revision=revision+1 WHERE id=?',s.id);audit(c,null,'shared.object',{spaceId:s.id,objectId:object.id});return this.space(c,id);});},
block(c,target){human(c);assert(target!==c.user_id&&get('SELECT id FROM users WHERE id=?',target),'用户不存在');return tx(()=>{run('INSERT OR IGNORE INTO blocks VALUES(?,?)',c.user_id,target);for(const b of all("SELECT b.* FROM bonds b JOIN islands a ON a.id=b.island_a JOIN islands z ON z.id=b.island_b WHERE b.status IN ('pending','active') AND ((a.owner_id=? AND z.owner_id=?) OR (a.owner_id=? AND z.owner_id=?))",c.user_id,target,target,c.user_id))endBond(c,b);audit(c,null,'user.blocked',{userId:target});return {blocked:true};});},
codingTask(c,id){own(c,id);if(c.kind!=='agent'||!c.scopes.includes('scene:write'))fail(403,'需要岛屿创作授权');const job=get("SELECT id,prompt,revision,created_at FROM creations WHERE island_id=? AND status='running' ORDER BY created_at LIMIT 1",id);if(!job)return {task:null};if(Date.now()-Date.parse(job.created_at)>1800000){this.failCreation(job.id,'Agent 未在 30 分钟内提交代码，请重新发起创作');return {task:null};}return {task:job,scene:island(id).scene,sdk:PROGRAM_GUIDE};},
submitProgram(c,id,jobId,source,summary){own(c,id);if(c.kind!=='agent'||!c.scopes.includes('scene:write'))fail(403,'需要岛屿创作授权');validateProgram(source);const job=get("SELECT * FROM creations WHERE id=? AND island_id=? AND status='running'",jobId,id);if(!job)fail(404,'找不到等待中的创作');const credential=get('SELECT * FROM credentials WHERE id=?',job.credential_id);credential.scopes=JSON.parse(credential.scopes);return this.completeCreation(credential,jobId,{...island(id).scene,program:source},summary);},
beginCreation(c,id,prompt){human(c);const i=own(c,id);assert(text(prompt,3000),'请用 1–3000 字描述想要的岛');return tx(()=>{if(get("SELECT 1 FROM creations WHERE island_id=? AND status='running'",id))fail(409,'Agent 正在修改这座岛，请稍候');if(get('SELECT COUNT(*) n FROM creations WHERE owner_id=? AND created_at>=?',c.user_id,now().slice(0,10)).n>=10)fail(429,'今日已完成 10 次创作请求');const key=issue(c.user_id,id,'agent',['scene:write','interior:write'],1),job=uid();run('INSERT INTO creations VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',job,id,c.user_id,key.id,i.revision,prompt,'running',null,null,JSON.stringify(i.scene),now(),now());recordMemory(c.user_id,id,{source:'agent_dialogue',type:'creation',content:prompt,gesture:'向 Agent 描述了希望岛屿发生的变化',context:'岛屿创作对话',direction:'把内在想象转译成可进入的世界',tags:['agent','creation'],importance:3,emotional:3,recurrence:3,unresolved:4});audit(c,id,'creation.requested',{jobId:job});return {jobId:job,credential:auth(key.token),scene:i.scene,preferences:this.preferences(c)?.payload||null,revision:i.revision};});},
creation(c,id){human(c);const r=get('SELECT id,island_id,status,summary,error,created_at,prompt FROM creations WHERE id=? AND owner_id=?',id,c.user_id);if(!r)fail(404,'创作不存在');if(r.status==='running'&&Date.now()-new Date(r.created_at).getTime()>1800000){this.failCreation(id,'创作连接已中断，岛屿未改变，请重试');r.status='failed';r.error='创作连接已中断，岛屿未改变，请重试';}return r;},
completeCreation(c,jobId,scene,summary){return tx(()=>{const job=get('SELECT * FROM creations WHERE id=? AND credential_id=?',jobId,c.id);if(!job||job.status!=='running')fail(409,'创作任务已结束');const valid=get('SELECT revoked_at,expires_at FROM credentials WHERE id=?',c.id);if(!valid||valid.revoked_at||valid.expires_at<now())fail(403,'创作授权已失效');const i=own(c,job.island_id);if(i.revision!==job.revision)fail(409,'岛屿已发生变化，本次结果未覆盖新版本');validateScene(scene);assert(text(summary,500),'Agent 摘要无效');run('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?',JSON.stringify(scene),i.id);run("UPDATE creations SET status='completed',summary=?,updated_at=? WHERE id=?",summary,now(),jobId);run('UPDATE credentials SET revoked_at=? WHERE id=?',now(),c.id);recordMemory(c.user_id,i.id,{source:'island_change',type:'creation',content:`${job.prompt}\n结果：${summary}`,gesture:summary,context:'Agent 完成了一次岛屿创作',direction:'这次改变成为岛屿持续生长的一部分',tags:['agent','island-change'],importance:3,emotional:3,recurrence:3,unresolved:1});audit(c,i.id,'creation.applied',{jobId,revision:i.revision+1});return island(i.id);});},
failCreation(jobId,message){const j=get('SELECT credential_id FROM creations WHERE id=?',jobId);if(j){run("UPDATE creations SET status='failed',error=?,updated_at=? WHERE id=? AND status='running'",message.slice(0,500),now(),jobId);run('UPDATE credentials SET revoked_at=? WHERE id=?',now(),j.credential_id);}},
undoCreation(c,id){human(c);return tx(()=>{const i=own(c,id),j=get("SELECT * FROM creations WHERE island_id=? AND status='completed' ORDER BY created_at DESC,rowid DESC LIMIT 1",id);if(!j||i.revision!==j.revision+1)fail(409,'当前版本无法撤回，请让 Agent 继续调整');run('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?',j.before_scene,id);run("UPDATE creations SET status='undone' WHERE id=?",j.id);audit(c,id,'creation.undone',{jobId:j.id});return island(id);});},
restore(c,id,revision,placement){human(c);return tx(()=>{const item=get('SELECT * FROM returned_objects WHERE id=? AND owner_id=?',id,c.user_id);if(!item)fail(404,'收纳物件不存在或不属于你');const current=island(get('SELECT id FROM islands WHERE owner_id=?',c.user_id).id);if(current.revision!==revision)fail(409,'版本冲突，请重新读取岛屿');assert(placement&&Object.keys(placement).every(k=>['roomId','x','y','z','rotation'].includes(k)),'放置参数无效');const scene=structuredClone(current.scene);const object={...JSON.parse(item.payload),...placement,id:uid()};scene.objects.push(object);validateScene(scene);run('UPDATE islands SET scene=?,revision=revision+1 WHERE id=?',JSON.stringify(scene),current.id);run('DELETE FROM returned_objects WHERE id=?',id);audit(c,current.id,'inventory.restored',{inventoryId:id,objectId:object.id});return island(current.id);});},
audit(c){human(c);return all('SELECT action,detail,created_at FROM audit WHERE actor_id=? ORDER BY id DESC LIMIT 100',c.user_id);}
};}
