import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {modelObject,updateModels,MODEL_SIZES} from './model-library.js';
const names={cat:'猫',dog:'小狗',bird:'小鸟',rabbit:'兔子',bear:'熊猫',fox:'狐狸',unicorn:'独角兽'};
document.querySelector('#app').innerHTML=`<style>body{margin:0;background:#f5f4e9;color:#395c4c;font-family:'PingFang SC',system-ui}header{padding:25px 5vw;display:flex;justify-content:space-between}a{color:inherit;text-decoration:none}main{max-width:1100px;margin:30px auto;padding:0 25px}h1{font-size:36px;font-weight:500;margin:15px 0}p{color:#7d8e7a;font-size:14px}#animal-stage{height:58vh;min-height:340px;border-radius:32px;overflow:hidden;background:#e8eee1}nav{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}button{font:inherit;color:inherit;border:1px solid #c5d5be;background:#faf9ef;padding:10px 22px;border-radius:25px;cursor:pointer}button[aria-pressed=true]{background:#60836c;color:white}#animal-stage canvas{display:block;touch-action:none}small{color:#8a9986}@media(max-width:600px){h1{font-size:28px}main{margin-top:8px}#animal-stage{height:48vh}nav{gap:7px}button{padding:8px 15px}}</style><header><a href="/?view=studio">← 回到我的岛</a><a href="/models/credits.html">模型鸣谢</a></header><main><small>岛上的小小邻居</small><h1>每一种陪伴，都有自己的样子。</h1><p>拖动看看它，滚轮拉近一点。选好后，可以告诉 Agent 邀请它来到岛上。</p><div id="animal-stage"></div><nav aria-label="动物模型库"></nav><p id="animal-status" role="status">正在加载…</p></main>`;
const container=document.querySelector('#animal-stage'),scene=new THREE.Scene();scene.background=new THREE.Color('#e8eee1');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;container.append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(38,1,.01,50);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=.5;controls.maxDistance=8;controls.maxPolarAngle=Math.PI*.49;
scene.add(new THREE.HemisphereLight('#fff7e2','#91ac98',2.3));const light=new THREE.DirectionalLight('#fff3de',3);light.position.set(-3,6,4);light.castShadow=true;light.shadow.mapSize.set(1024,1024);light.shadow.normalBias=.025;scene.add(light);
const floor=new THREE.Mesh(new THREE.CylinderGeometry(2,2,.12,64),new THREE.MeshStandardMaterial({color:'#d5dfc9',roughness:1}));floor.position.y=-.075;floor.receiveShadow=true;scene.add(floor);let current;
function select(kind){current?.removeFromParent();current=modelObject(kind);scene.add(current);const height=MODEL_SIZES[kind][1];camera.position.set(height*1.5,height*1.15,height*2.5);controls.target.set(0,height*.45,0);controls.update();document.querySelectorAll('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));document.querySelector('#animal-status').textContent=names[kind]+' · 正在加载模型…';current.userData.label=names[kind];}
for(const [kind,name] of Object.entries(names)){const b=document.createElement('button');b.textContent=name;b.dataset.kind=kind;b.onclick=()=>select(kind);document.querySelector('nav').append(b);}
const resize=()=>{renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(container);resize();select('cat');let before=performance.now();renderer.setAnimationLoop(time=>{const dt=Math.min((time-before)/1000,.05);before=time;updateModels(scene,dt);controls.update();renderer.render(scene,camera);if(current&&!current.userData.loading)document.querySelector('#animal-status').textContent=current.userData.error||current.userData.label+' · 模型已加载'+(current.userData.animations?' · 带骨骼动画':'');});addEventListener('pagehide',()=>{renderer.setAnimationLoop(null);renderer.dispose();controls.dispose();});
