import './auth.css';
import './brand.css';
import {brandMark} from './brand.js';
import {createWorld} from './world.js';
import {starterEcosystem} from '../server/ecosystem.js';

const root=document.querySelector('#app');
root.innerHTML=`<main class="auth-page"><div id="auth-world" role="img" aria-label="云海中缓慢漂浮的三维岛屿"></div><div class="auth-world-hint" aria-hidden="true">拖动云海，看看岛的另一面。</div><header><span>我们的岛</span><small>SOMEWHERE, TOGETHER</small></header><section class="auth-card" aria-labelledby="auth-title"><small>先认出彼此，再抵达你的世界。</small><h1 id="auth-title">回来，继续照料<br>属于你的岛。</h1><div class="auth-tabs" role="tablist"><button role="tab" aria-selected="true" data-mode="login">登录</button><button role="tab" aria-selected="false" data-mode="register">创建账号</button></div><form id="auth-form"><label data-name hidden>怎么称呼你<input name="name" maxlength="30" autocomplete="name" placeholder="你的名字"></label><label>邮箱<input name="email" type="email" maxlength="254" autocomplete="email" placeholder="you@example.com" required></label><label>密码<input name="password" type="password" minlength="8" maxlength="128" autocomplete="current-password" placeholder="至少 8 个字符" required></label><button class="auth-submit" type="submit">登录并回到我的岛 →</button><p id="auth-message" role="status"></p></form><p class="auth-footnote">每个账号对应一座独立的岛。你的偏好、岛屿代码与 Agent 授权不会与其他人混在一起。</p></section></main>`;
const authHeader=document.querySelector('.auth-page header');authHeader.querySelector('span').insertAdjacentHTML('beforebegin',brandMark());
try{const scene={...starterEcosystem(),growing:true,daylight:'balanced',program:null};const authWorld=createWorld(document.querySelector('#auth-world'),{...scene,rooms:[],expansions:0},()=>{},()=>{},{ecosystemOnly:true});authWorld.setEcology(scene);}catch(error){document.querySelector('.auth-page').classList.add('auth-world-fallback');console.error(error);}
let mode='login',busy=false;const legacy=window.__legacyIsland;
const form=document.querySelector('#auth-form'),message=document.querySelector('#auth-message'),submit=document.querySelector('.auth-submit'),nameLabel=document.querySelector('[data-name]');
function setMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.mode===mode)));nameLabel.hidden=mode!=='register';form.name.required=mode==='register';form.password.autocomplete=mode==='register'?'new-password':'current-password';submit.textContent=mode==='register'?(legacy?'创建账号，继续照料这座岛 →':'创建账号，开始认识我的岛 →'):'登录并回到我的岛 →';message.textContent='';}
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>setMode(button.dataset.mode));
form.onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;submit.disabled=true;message.textContent=mode==='register'?(legacy?'正在把这座岛交还给你…':'正在为你留出一座岛…'):'正在寻找你的岛…';try{const body={email:form.email.value.trim(),password:form.password.value,...(mode==='register'?{name:form.name.value.trim()}:{})},claim=mode==='register'&&legacy;const response=await fetch(claim?'/api/auth/claim':`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json',...(claim?{Authorization:`Bearer ${legacy.token}`}:{})},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'暂时无法登录');localStorage.setItem('our-island-owner-token',data.token);localStorage.removeItem('island-onboarding-complete');location.href=data.onboardingComplete?'/?view=studio':'/?view=connect';}catch(error){message.textContent=error.message;submit.disabled=false;busy=false;}};
if(legacy){document.querySelector('#auth-title').innerHTML='给这座岛一个名字，<br>以后从任何地方回来。';form.name.value=legacy.name||'';setMode('register');}
