import {seasonalEnvironment} from './seasons.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
export function cosmosScene(root,onSelect){
const scene=new T.Scene();scene.background=new T.Color('#d7e0d6');scene.fog=new T.FogExp2('#d7e0d6',.0027);
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;root.append(renderer.domElement);
const camera=new T.PerspectiveCamera(innerWidth<700?65:42,innerWidth/innerHeight,.1,750);const home=new T.Vector3(65,55,87);camera.position.copy(home);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,-7);controls.enableDamping=true;controls.minDistance=14;controls.maxDistance=180;controls.maxPolarAngle=1.43;controls.minPolarAngle=.2;controls.enablePan=false;controls.autoRotate=true;controls.autoRotateSpeed=.07;
scene.add(new T.HemisphereLight('#fff4dc','#779e91',1.35));const sun=new T.DirectionalLight('#fff0cd',2.6);sun.position.set(-35,60,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:180});sun.shadow.normalBias=.08;sun.shadow.bias=-.0003;scene.add(sun);const warm=new T.DirectionalLight('#c2e0d4',1.2);warm.position.set(20,10,30);scene.add(warm);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.2,.55,1.3);composer.addPass(bloom);composer.addPass(new OutputPass());
let seed=149;const random=()=>{seed=(seed*16807)%2147483647;return (seed-1)/2147483646;};const geo={box:new T.BoxGeometry(1,1,1),rock:new T.IcosahedronGeometry(1,0),ball:new T.IcosahedronGeometry(1,1),cone:new T.ConeGeometry(1,1,6),cylinder:new T.CylinderGeometry(1,1,1,8)};const materials=new Map();
const mat=(c,emit=0)=>{const key=c+emit;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color:c,roughness:.75,metalness:0,emissive:c,emissiveIntensity:emit}));return materials.get(key);};
function mesh(g,c,p,s,parent,emit=0){const m=new T.Mesh(geo[g],mat(c,emit));m.position.set(...p);m.scale.set(...s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function line(points,color,opacity,parent=scene){const l=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color,transparent:true,opacity}));parent.add(l);return l;}
const clouds=[];for(let i=0;i<36;i++){const cloud=new T.Group();const a=i*2.399;const rr=45+random()*145;cloud.position.set(Math.cos(a)*rr,-7-random()*9,Math.sin(a)*rr*.6-20);for(let j=0;j<5;j++){const puff=new T.Mesh(geo.ball,new T.MeshStandardMaterial({color:'#f4efdf',roughness:1,transparent:true,opacity:.52,depthWrite:false}));puff.position.set((j-2)*2.5,Math.sin(j)*.8,0);puff.scale.set(3,1.2+random(),2);cloud.add(puff);}scene.add(cloud);clouds.push(cloud);}
const islands=[],hitTargets=[],animations=[];
const themes=[{name:'雾森图书馆',owner:'lin',agent:'Codex',color:'#94b895',type:0,description:'把读过的书，种成一片会呼吸的森林。'},{name:'月面档案馆',owner:'yue',agent:'Claude Code',color:'#c5cbd1',type:1,description:'月球背面，收藏一些尚未抵达的未来。'},{name:'落日温室',owner:'summer',agent:'Codex',color:'#e0b091',type:2,description:'在永不落幕的黄昏里，等待一朵花开。'},{name:'悬空神殿',owner:'echo',agent:'Claude Code',color:'#a4c3b3',type:3,description:'没有道路。只有风，和漂浮着的建筑。'},{name:'星际信号站',owner:'nova',agent:'Codex',color:'#82b8cc',type:4,description:'向虚空发出信号，等另一个世界回应。'}];
function buildIsland(x,y,z,r,type,active=true,meta=null){const group=new T.Group();group.position.set(x,y,z);scene.add(group);const top=active?'#b3c79f':'#b9c5b2';
mesh('cylinder',top,[0,0,0],[r,.42,r],group);const rock=mesh('cone',active?'#67978e':'#98afa3',[0,-r*.48,0],[r*.99,r*1.15,r*.99],group);rock.rotation.z=Math.PI;rock.rotation.y=.3;
for(let i=0;i<7;i++){const a=i/7*Math.PI*2;mesh('rock',active?'#8eae98':'#abbba8',[Math.cos(a)*r*.72,-.7,Math.sin(a)*r*.72],[r*.4,.8,r*.35],group);}
const theme=themes[type%5];const inner=new T.Group();group.add(inner);
if(active){if(type===0){for(let i=0;i<11;i++){const a=i*2.399,rr=(.42+Math.sqrt(i/11)*.38)*r;const px=Math.cos(a)*rr,pz=Math.sin(a)*rr,h=r*.26+random()*r*.4;mesh('cylinder','#34514b',[px,h*.4,pz],[.08,h,.08],inner);mesh('ball',i%3===0?'#dfad9f':theme.color,[px,h,pz],[r*.25,h*.55,r*.23],inner);mesh('ball',i%3===0?'#e8bdb0':'#adc3a1',[px+.35,h+.25,pz],[r*.2,r*.22,r*.2],inner);}
mesh('box','#f0e2c2',[r*.22,r*.17,r*.22],[r*.55,r*.34,r*.4],inner);const roof=mesh('cone','#6c9690',[r*.22,r*.42,r*.22],[r*.48,r*.25,r*.36],inner);roof.rotation.y=Math.PI/4;mesh('box','#eac989',[r*.22,r*.2,r*.425],[r*.3,r*.13,.03],inner,.35);
}else if(type===1){mesh('cylinder','#91a5b5',[0,.4,0],[r*.65,.5,r*.65],inner);for(let i=0;i<5;i++){const a=i*1.256;const h=1.2+i*.6;mesh('box','#a9bdc5',[Math.cos(a)*r*.38,h*.5,Math.sin(a)*r*.38],[.7,h,.7],inner);mesh('box','#b5e2ef',[Math.cos(a)*r*.38,h,Math.sin(a)*r*.38],[.74,.08,.74],inner,.45);}
}else if(type===2){mesh('box','#768f81',[0,.22,0],[r*1.2,.3,r],inner);for(let i=0;i<6;i++){const xx=(i%3-1)*r*.43,zz=i<3?-.6:.65;mesh('cylinder','#5f7563',[xx,.4,zz],[.16,.7,.16],inner);mesh('ball',i%2?'#c99279':'#98bba0',[xx,1.35,zz],[.7,.85,.7],inner);}mesh('box','#edc994',[0,.4,r*.56],[r*.9,.12,.04],inner,.4);
}else if(type===3){for(let i=0;i<8;i++){const a=i*Math.PI/4;mesh('cylinder','#90b1ad',[Math.cos(a)*r*.55,1.5,Math.sin(a)*r*.55],[.19,3,.19],inner);}mesh('cylinder','#7c9c9b',[0,3,0],[r*.74,.28,r*.74],inner);mesh('cone','#3c7376',[0,3.7,0],[r*.78,1.2,r*.78],inner);mesh('ball','#b8fff0',[0,1.7,0],[.3,.3,.3],inner,.8);
}else{mesh('cylinder','#648f9c',[0,.75,0],[r*.45,1.5,r*.45],inner);mesh('cylinder','#a0cbd5',[0,2.3,0],[.11,2,.11],inner);const ring=new T.Mesh(new T.TorusGeometry(r*.5,.08,6,32),mat('#d8d2b1',.4));ring.position.y=2.1;ring.rotation.x=.4;inner.add(ring);mesh('ball','#c7f2ed',[0,3.4,0],[.25,.25,.25],inner,.8);}
for(let i=0;i<5;i++){const a=i/5*6.28;mesh('box','#eac69a',[Math.cos(a)*r*.87,.3,Math.sin(a)*r*.87],[.08,.12,.08],inner,.45);}
const waterfall=mesh('box','#63a8a5',[r*.72,-r*.75,r*.32],[r*.13,r*1.6,.05],inner,.4);waterfall.material=new T.MeshStandardMaterial({color:'#83c4bf',emissive:'#458480',emissiveIntensity:.3,transparent:true,opacity:.5});
}else{const ring=new T.Mesh(new T.RingGeometry(r*.5,r*.52,48),new T.MeshBasicMaterial({color:'#91a995',side:T.DoubleSide,transparent:true,opacity:.5}));ring.rotation.x=-Math.PI/2;ring.position.y=.25;inner.add(ring);}
const item={id:islands.length,group,r,type,active,meta:meta||theme,baseY:y};islands.push(item);group.traverse(m=>{if(m.isMesh){m.userData.islandId=item.id;hitTargets.push(m);}});return item;}
// A sprawling archipelago, following the curve of an invisible continent.
for(let i=0;i<58;i++){const a=i*2.39996,rr=10+Math.sqrt(i/58)*49;const x=Math.cos(a)*rr,z=Math.sin(a)*rr*.7-12;const r=i<8?2.8+random()*1.5:1.25+random()*1.5;buildIsland(x,(random()-.5)*9,z,r,i%5,i%7!==0);}
const hero=buildIsland(8,2,17,7.5,0,true,{...themes[0],name:'风栖之地',owner:'mori'});
const ownSlot=buildIsland(-8,-1,18,4.3,0,false,{name:'你的世界',owner:'你',agent:'尚未连接',description:'一座尚未亮起的岛，正在等待你的 Agent。'});
// Distant islands are instanced: hundreds of worlds in a handful of draw calls.
const far=new T.InstancedMesh(new T.ConeGeometry(1,1,5),mat('#87aa9e'),420);const beacons=new T.InstancedMesh(new T.OctahedronGeometry(1),mat('#c3d5b4',.2),420);const d=new T.Object3D();
for(let i=0;i<420;i++){const a=random()*Math.PI*2,r=60+random()*160;d.position.set((random()-.5)*350,(random()-.5)*15-4,-75-random()*180);d.rotation.z=Math.PI;d.scale.set(1+random()*1.4,2+random()*3,1+random());d.updateMatrix();far.setMatrixAt(i,d.matrix);d.position.y+=d.scale.y*.5;d.scale.set(.12,.35,.12);d.rotation.z=0;d.updateMatrix();beacons.setMatrixAt(i,d.matrix);}scene.add(far,beacons);
const starPositions=[];for(let i=0;i<6000;i++){const a=random()*Math.PI*2,r=30+random()*270;starPositions.push(Math.cos(a)*r,(random()-.5)*170,Math.sin(a)*r);}const starGeo=new T.BufferGeometry();starGeo.setAttribute('position',new T.Float32BufferAttribute(starPositions,3));const stars=new T.Points(starGeo,new T.PointsMaterial({color:'#fff7d6',size:.1,transparent:true,opacity:.25,sizeAttenuation:true}));scene.add(stars);
// Fine orbital contours expose the shape of the otherwise invisible land.
for(let i=0;i<7;i++){const p=[];for(let j=0;j<=180;j++){const a=j/180*6.28;p.push(new T.Vector3(Math.cos(a)*(28+i*9),-8-i*.18,Math.sin(a)*(20+i*6)-12));}line(p,'#91aa96',.13);}
for(let i=0;i<islands.length-2;i+=3){const a=islands[i],b=islands[i+2];if(!a.active||!b.active)continue;const curve=new T.QuadraticBezierCurve3(a.group.position,new T.Vector3((a.group.position.x+b.group.position.x)/2,-7,(a.group.position.z+b.group.position.z)/2),b.group.position);line(curve.getPoints(24),'#90ad97',.17);}
const selectRing=new T.Mesh(new T.RingGeometry(5.9,5.95,100),new T.MeshBasicMaterial({color:'#c29f68',side:T.DoubleSide,transparent:true,opacity:.75}));selectRing.rotation.x=-Math.PI/2;selectRing.position.copy(hero.group.position);selectRing.position.y+=.3;scene.add(selectRing);
let target=null,targetLook=null,selectedId=hero.id;const mouse=new T.Vector2(),ray=new T.Raycaster();let down;
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(mouse,camera);const h=ray.intersectObjects(hitTargets);if(h.length){const item=islands[h[0].object.userData.islandId];if(item){select(item.id);onSelect(item);}}});
function select(id){selectedId=id;const item=islands[id];selectRing.position.copy(item.group.position);selectRing.position.y+=.3;selectRing.scale.setScalar(item.r/5.5);}
let t=0,last=performance.now();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)controls.autoRotate=false;
const seasons=seasonalEnvironment(scene,{wide:true,onSeason(season,blend){const skies={spring:"#d7e0d6",summer:"#cbdedb",autumn:"#e3d9c8",winter:"#d9e3e8"};scene.background.set(skies[blend.from]).lerp(new T.Color(skies[blend.to]),blend.amount);scene.fog.color.copy(scene.background);}});
renderer.setAnimationLoop(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.05);last=now;t+=dt;seasons.update(dt);if(!reduced)clouds.forEach(c=>{c.position.x+=dt*.13;if(c.position.x>190)c.position.x=-190;});for(const item of islands){if(!reduced)item.group.position.y=item.baseY+Math.sin(t*.4+item.id)*.26;}selectRing.position.y=islands[selectedId].group.position.y+.32;if(target){camera.position.lerp(target,.035);controls.target.lerp(targetLook,.035);if(camera.position.distanceTo(target)<.1)target=null;}for(let i=animations.length-1;i>=0;i--){const a=animations[i];a.age+=dt;a.group.scale.setScalar(Math.min(1,a.age/1.7));a.beam.material.opacity=Math.max(0,(1-a.age/4)*.25);a.ring.scale.setScalar(1+a.age*4);a.ring.material.opacity=Math.max(0,1-a.age/4);if(a.age>4){scene.remove(a.beam,a.ring);a.beam.geometry.dispose();a.beam.material.dispose();a.ring.geometry.dispose();a.ring.material.dispose();animations.splice(i,1);}}controls.update();composer.render();});
function lightIsland(type=0,meta=null){const inactive=islands.find(i=>!i.active&&i.id===ownSlot.id)||islands.find(i=>!i.active);if(!inactive)return null;inactive.active=true;inactive.retired=true;const p=inactive.group.position.clone();scene.remove(inactive.group);for(let i=hitTargets.length-1;i>=0;i--)if(hitTargets[i].userData.islandId===inactive.id)hitTargets.splice(i,1);const item=buildIsland(p.x,p.y,p.z,inactive.r,type,true,meta);item.group.scale.setScalar(.01);
const beam=new T.Mesh(new T.CylinderGeometry(.07,.7,55,16,1,true),new T.MeshBasicMaterial({color:'#ffdf99',transparent:true,opacity:.25,side:T.DoubleSide,depthWrite:false}));beam.position.copy(p);beam.position.y+=27;scene.add(beam);const ring=new T.Mesh(new T.RingGeometry(.95,1,64),new T.MeshBasicMaterial({color:'#fff1c1',transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(p);ring.position.y+=.4;scene.add(ring);animations.push({age:0,group:item.group,beam,ring});select(item.id);onSelect(item);return item;}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.fov=innerWidth<700?65:42;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});
return {islands,hero,ownSlot,select,lightIsland,focus(id){const item=islands[id];select(id);targetLook=item.group.position.clone();target=item.group.position.clone().add(new T.Vector3(item.r*3.5,item.r*2.5,item.r*4.5));controls.autoRotate=false;},overview(){target=home.clone();targetLook=new T.Vector3(0,0,-7);controls.autoRotate=!reduced;},zoom(f){camera.position.sub(controls.target).multiplyScalar(f).clampLength(14,180).add(controls.target);},stats(){return {drawCalls:renderer.info.render.calls,worlds:islands.filter(i=>i.active&&!i.retired).length+420};}};
}
