import './cosmos.css';
import './brand.css';
import '@phosphor-icons/web/regular';
import {cosmosScene} from './cosmos-scene.js';
import {brandMark} from './brand.js';
const icon=n=>`<i class="ph ph-${n}" aria-hidden="true"></i>`;
const session=window.__islandSession,journeyPath=session?(session.onboardingComplete?'/?view=studio':'/?view=onboarding'):'/?view=auth';
document.querySelector('#app').innerHTML=`<main id="universe" aria-label="虚空大陆 3D 群岛视图"></main><div id="ui"><div class="vignette"></div><header class="u-header"><a class="logo" href="/" aria-label="我们的岛首页">${brandMark()}<div><strong>我们的岛</strong><small>WORLDS, WRITTEN BY YOU</small></div></a><nav class="u-nav"><a href="${journeyPath}">${session?`${session.user.name}的岛`:'进入我的岛'}</a><span>每座岛，都是一个人的宇宙</span><button id="signal-control" hidden></button><button id="preview-info"><b></b>群岛状态</button></nav></header><section class="u-intro"><div class="u-kicker">THE WORLD BEGINS WITH YOU</div><h1>喜欢自己，<br>比喜欢世界<em>更重要。</em></h1><p>把自己慢慢打磨成一座岛。<br>当你愿意发出独属于你的信号，世界会循光而来。</p><div class="small-rule"></div></section><div class="world-meta"><div><strong id="lit-count">472</strong><span id="world-count-label">云海中已点亮</span></div><div class="sep"></div><div><strong id="nearby-count">∞</strong><span>与你同在的岛</span></div></div><aside class="inspector" id="inspector"></aside><div class="u-tools"><button class="wide" id="simulate">${icon('sparkle')} 演示新岛加入</button><button id="u-zoom-in" aria-label="放大">${icon('plus')}</button><button id="u-zoom-out" aria-label="缩小">${icon('minus')}</button><button id="overview" aria-label="返回大陆全景">${icon('arrows-out')}</button></div><div class="join-dock"><div class="agent-icons">${icon('terminal-window')}${icon('asterisk')}</div><button class="gold-button" id="join">${icon('arrow-right')} ${session?'回到我的岛':'进入，点亮我的岛'} ${icon('arrow-up-right')}</button></div><div class="join-caption" id="join-caption">先认识这片群岛，再开始书写你的世界</div><footer class="u-footer"><small>VOID ATLAS &nbsp; / &nbsp; 虚空大陆<br>每一处亮光，都始于一个想法。</small><div class="legend"><span><i></i>已点亮</span><span><i class="off"></i>等待加入</span></div><small>拖动探索 · 滚轮缩放 · 点击岛屿查看</small></footer><div class="world-event" role="status" id="world-event"></div><div id="modal-root"></div><div id="workspace-root"></div></div><div class="u-loading">正在展开虚空大陆<small>每一座岛，都是一个尚未说完的故事。</small></div>`;
let world,selected,own=null,agent='Codex',busy=false,noticeTimer,ownRecord=null,realNeighbors=[];const renderedNeighbors=new Map();
function notify(text){const el=document.querySelector('#world-event');el.textContent=text;el.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove('visible'),4300);}
async function api(path,method='GET',body){const token=localStorage.getItem('our-island-owner-token');const response=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw Error(data.error||'暂时无法连接云海');return data;}
function inspect(item){selected=item;const real=!!item.meta.realIslandId;const el=document.querySelector('#inspector');el.innerHTML=`<div class="label">${real?'A REAL ISLAND':item.active?'A WORLD BY AN AGENT':'AN UNWRITTEN WORLD'}</div><h2></h2><p></p><div class="by"><span class="owner"></span><span class="agent"></span></div><button class="inspect-button" id="inspect-action">${real?'着陆探访':item.active?'靠近这座岛':'点亮我的世界'} ${icon('arrow-up-right')}</button>`;el.querySelector('h2').textContent=item.meta.name;el.querySelector('p').textContent=item.meta.description;el.querySelector('.owner').textContent=real?'已开放发现':`@${item.meta.owner}`;el.querySelector('.agent').textContent=item.meta.agent;el.querySelector('#inspect-action').onclick=()=>item.active?focus(item):beginJourney();}
function beginJourney(){location.href=journeyPath;}
function staticWorld(){const root=document.querySelector('#universe');root.replaceChildren();root.classList.add('cosmos-fallback');root.dataset.renderMode='static';const items=[{name:'风栖之地',owner:'mori',agent:'Codex',description:'把读过的书，种成一片会呼吸的森林。',type:0,active:true},{name:'月面档案馆',owner:'yue',agent:'Claude Code',description:'月球背面，收藏一些尚未抵达的未来。',type:1,active:true},{name:'落日温室',owner:'summer',agent:'Codex',description:'在永不落幕的黄昏里，等待一朵花开。',type:2,active:true},{name:'你的世界',owner:'你',agent:'尚未连接',description:'一座尚未亮起的岛，正在等待你的 Agent。',type:0,active:false}].map((meta,id)=>({id,type:meta.type,active:meta.active,meta}));root.innerHTML=`<div class="fallback-sky" aria-hidden="true"></div><div class="fallback-archipelago"></div><div class="fallback-note"><b>群岛漫游模式</b><span>拖动探索 · 按钮缩放 · 仍可继续创造</span></div>`;const sky=root.querySelector('.fallback-sky'),arch=root.querySelector('.fallback-archipelago');const islandButton=(item,i,remote=false)=>{const b=document.createElement('button');b.className=`fallback-island island-${i}${item.active?' is-lit':''}`;if(remote){b.style.left=`${46+(i*13)%43}%`;b.style.top=`${18+(i*19)%55}%`;b.style.transform=`rotate(${i%2?8:-11}deg) scale(.52)`;}b.setAttribute('aria-label',item.meta.name);b.innerHTML=`<i></i><span>${item.meta.name}</span>`;b.onclick=()=>inspect(item);arch.append(b);return b;};items.forEach((item,i)=>islandButton(item,i));let extra=0,panX=0,panY=0,scale=1,drag=null;const render=()=>{sky.style.transform=`translate3d(${panX}px,${panY}px,0) scale(${scale})`;};root.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY,panX,panY];sky.classList.add('is-controlled');root.setPointerCapture?.(e.pointerId);});root.addEventListener('pointermove',e=>{if(!drag)return;panX=drag[2]+e.clientX-drag[0];panY=drag[3]+e.clientY-drag[1];render();});const release=()=>{drag=null;};root.addEventListener('pointerup',release);root.addEventListener('pointercancel',release);const light=(type=0,meta=null)=>{const item=items.find(x=>!x.active);if(!item)return null;item.active=true;item.type=type;item.meta=meta||item.meta;const button=arch.querySelector(`.island-${item.id}`);button.classList.add('is-lit');button.querySelector('span').textContent=item.meta.name;extra++;inspect(item);return item;};const lightRemote=(type=0,meta)=>{const item={id:items.length,type,active:true,meta};items.push(item);islandButton(item,item.id,true);extra++;return item;};return {hero:items[0],lightIsland:light,lightRemoteIsland:lightRemote,focus(id){arch.dataset.focus=id;scale=1.08;render();},overview(){delete arch.dataset.focus;panX=0;panY=0;scale=1;render();},zoom(f){scale=Math.max(1,Math.min(1.5,scale/f));render();},stats(){return {drawCalls:0,worlds:472+extra,mode:'static'};}};}
function startWorld(){const root=document.querySelector('#universe');const lightweight=new URLSearchParams(location.search).has('low3d');try{const scene=cosmosScene(root,inspect,{lightweight});root.dataset.renderMode=lightweight?'light3d':'full3d';return scene;}catch(firstError){console.error('3D scene failed; switching to lightweight mode.',firstError);root.replaceChildren();if(!lightweight){try{const scene=cosmosScene(root,inspect,{lightweight:true});root.dataset.renderMode='light3d';return scene;}catch(secondError){console.error('Lightweight 3D scene failed; switching to the accessible archipelago.',secondError);root.replaceChildren();}}return staticWorld();}}
world=startWorld();inspect(world.hero);document.querySelector('#lit-count').textContent=world.stats().worlds;document.querySelector('.u-loading')?.remove();
function islandType(name=''){return [...name].reduce((sum,char)=>sum+char.codePointAt(0),0)%5;}
function updateDiscoveryStatus(){const control=document.querySelector('#signal-control'),caption=document.querySelector('#join-caption'),count=document.querySelector('#nearby-count');if(!session){count.textContent='—';caption.textContent='登录后，才能看见选择公开的真实岛屿';return;}control.hidden=false;const open=!!ownRecord?.discoverable;control.setAttribute('aria-pressed',String(open));control.innerHTML=open?'<b></b>信号正在宇宙中':'○ 发出我的信号';count.textContent=String(realNeighbors.length);caption.textContent=realNeighbors.length?`发现 ${realNeighbors.length} 座愿意被看见的岛`:open?'信号已发出，等待另一座岛也选择被发现':'你的岛仍是私密的；发出信号后才能参与相遇';}
async function loadDiscovery(){updateDiscoveryStatus();if(!session)return;try{const [me,neighbors]=await Promise.all([api('/me'),api('/world')]);ownRecord=me.island;realNeighbors=neighbors;for(const neighbor of neighbors.slice(0,6)){const meta={name:neighbor.name,owner:'一位真实岛主',agent:'已连接 Agent',description:`契合度 ${neighbor.compatibility}% · 本轮相遇概率 ${Math.round(neighbor.probability*100)}%`,realIslandId:neighbor.id,compatibility:neighbor.compatibility,probability:neighbor.probability};const existing=renderedNeighbors.get(neighbor.id);if(existing)Object.assign(existing.meta,meta);else{const item=world.lightRemoteIsland(islandType(neighbor.name),meta);if(item)renderedNeighbors.set(neighbor.id,item);}}document.querySelector('#lit-count').textContent=world.stats().worlds;updateDiscoveryStatus();if(selected?.meta?.realIslandId)inspect(selected);return true;}catch(error){document.querySelector('#nearby-count').textContent='—';document.querySelector('#join-caption').textContent=error.message;return false;}}
document.querySelector('#signal-control').onclick=async()=>{if(!ownRecord)return;const button=document.querySelector('#signal-control'),next=!ownRecord.discoverable;button.disabled=true;try{ownRecord=await api(`/islands/${ownRecord.id}/visibility`,'POST',{discoverable:next});await loadDiscovery();notify(next?'你的岛已经发出信号。其他公开岛现在可以发现你。':'信号已收回，你的岛不会再出现在别人的云海。');}catch(error){notify(error.message);}finally{button.disabled=false;}};
loadDiscovery();
function openConnect(){if(own){focus(own);return;}document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="connect-modal" role="dialog" aria-modal="true" aria-labelledby="connect-title"><button class="modal-close" aria-label="关闭连接窗口">×</button><div class="m-icon">${icon('plug')}</div><h2 id="connect-title">带上你的 Agent，<br>来创造一个世界。</h2><p>岛屿由你的 Agent 编写。建筑、地形、规则，<br>都可以长成你的想象。</p><div class="agent-options"><button class="agent-option active" data-agent="Codex">${icon('terminal-window')} Codex</button><button class="agent-option" data-agent="Claude Code">${icon('asterisk')} Claude Code</button></div><label class="field-label">API Key</label><div class="key-preview"><span>正式接入时在本地安全配置</span>${icon('lock-key')}</div><label class="field-label" for="vision">你想创造怎样的岛？</label><textarea id="vision" maxlength="240">一座漂浮在星海中的森林图书馆，有树木、暖灯和瀑布。</textarea><button class="gold-button" id="ignite">${icon('sparkle')} 预览连接，点亮我的岛</button><p class="privacy">当前演示不连接真实 Agent，不收集或保存密钥。</p><div class="progress-steps"><span>01 连接 Agent</span><span>02 编写世界</span><span>03 点亮岛屿</span></div></section></div>`;agent='Codex';document.querySelector('.modal-close').onclick=closeConnect;document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{agent=b.dataset.agent;document.querySelectorAll('[data-agent]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelector('#ignite').onclick=ignite;document.querySelector('.modal-close').focus();}
function closeConnect(){if(busy)return;document.querySelector('#modal-root').innerHTML='';document.querySelector('#join').focus();}
async function ignite(){if(busy)return;busy=true;const btn=document.querySelector('#ignite'),vision=document.querySelector('#vision').value.trim()||'森林中的一座岛';btn.disabled=true;document.querySelector('.modal-close').disabled=true;document.querySelectorAll('[data-agent]').forEach(b=>b.disabled=true);document.querySelector('#vision').disabled=true;const steps=document.querySelectorAll('.progress-steps span');for(let i=0;i<3;i++){steps[i].classList.add('done');btn.textContent=['演示：连接你的 Agent…','演示：根据想象生成场景…','你的世界，正在亮起…'][i];await new Promise(r=>setTimeout(r,650));}
let type=/月|未来|极简|城市/.test(vision)?1:/花|温室|落日/.test(vision)?2:/神殿|寺|古/.test(vision)?3:/科技|太空|信号|赛博/.test(vision)?4:0;
own=world.lightIsland(type,{name:'你的第一座岛',owner:'you',agent,description:vision});busy=false;document.querySelector('#modal-root').innerHTML='';if(own){document.querySelector('#join').innerHTML=`${icon('code')} 进入我的世界 ${icon('arrow-up-right')}`;document.querySelector('#lit-count').textContent=world.stats().worlds;notify(`你的岛已点亮 · ${agent} 创作流程演示`);world.focus(own.id);document.body.classList.add('focus');setTimeout(()=>focus(own),1900);}}
function focus(item){const real=!!item.meta.realIslandId;world.focus(item.id);document.body.classList.add('focus');document.querySelector('#inspector').style.display='none';const root=document.querySelector('#workspace-root');root.innerHTML=`<aside class="workspace"><div class="u-kicker">${real?'A REAL ISLAND':item===own?'YOUR AGENT WORKSPACE':'ISLAND PREVIEW'}</div><h2></h2><p class="description"></p><p>${real?'这是一位岛主主动向云海发出的信号。你可以着陆散步，但不会改变对方的世界。':item===own?'Agent 接入后的创作工作区示意。当前场景由本地程序生成，尚未执行 AI 代码。':'示例居民的独立世界。不同代码，可以创造完全不同的空间。'}</p><a class="inspect-button" id="land-visit">${real?'着陆探访这座岛':'着陆探访 · 示例岛'} ↓</a><pre></pre><button class="inspect-button" id="back-world">${icon('arrows-out')} 返回虚空大陆</button>${item===own?'<a href="/?view=island">体验之前的庭院布置玩法</a>':''}</aside>`;root.querySelector('#land-visit').href=real?'/?view=visit&island='+encodeURIComponent(item.meta.realIslandId):'/?view=visit&demo='+(['forest','planet','ocean','society','planet'][item.type]||'forest');root.querySelector('h2').textContent=item.meta.name;root.querySelector('.description').textContent=item.meta.description;root.querySelector('pre').textContent=real?`// 公开岛屿\ncompatibility: ${item.meta.compatibility}%\nencounter: ${Math.round(item.meta.probability*100)}%`:`// 场景定义示意\nisland.create({\n  author: "${item.meta.owner}",\n  agent: "${item.meta.agent}",\n  biome: "${['forest','lunar','garden','temple','signal'][item.type]}",\n  floating: true,\n  light: "warm"\n});`;document.querySelector('#back-world').onclick=overview;}
function overview(){world.overview();document.body.classList.remove('focus');document.querySelector('#workspace-root').innerHTML='';document.querySelector('#inspector').style.display='';}
document.querySelector('#join').onclick=beginJourney;document.querySelector('#overview').onclick=overview;document.querySelector('#u-zoom-in').onclick=()=>world.zoom(.85);document.querySelector('#u-zoom-out').onclick=()=>world.zoom(1.15);document.querySelector('#preview-info').onclick=async()=>{if(!session){notify('登录后，首页会读取真实公开岛屿。眼前发光的岛是世界氛围演示。');return;}const button=document.querySelector('#preview-info');button.disabled=true;const ok=await loadDiscovery();button.disabled=false;if(ok)notify(realNeighbors.length?`刚刚重新感应到 ${realNeighbors.length} 座真实公开岛，点击后可以着陆探访。`:ownRecord?.discoverable?'你的信号已经发出，目前还没有其他岛主公开自己的岛。':'你的岛当前保持私密。点击“发出我的信号”后，才会进入真实发现与相遇。');};
let n=0;document.querySelector('#simulate').onclick=()=>{if(busy)return;overview();const item=world.lightIsland((++n)%5);if(!item){notify('本轮预留岛屿已全部点亮，刷新可重新演示');return;}document.querySelector('#lit-count').textContent=world.stats().worlds;notify(`新世界加入 · ${item.meta.name} 被点亮了`);};
addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.connect-modal')?closeConnect():overview();}if(e.key==='Tab'&&document.querySelector('.connect-modal')){const elements=[...document.querySelector('.connect-modal').querySelectorAll('button:not(:disabled),textarea:not(:disabled)')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.__cosmos={stats:()=>world.stats(),hasOwnIsland:()=>!!own};
