import './cosmos.css';
import './brand.css';
import '@phosphor-icons/web/regular';
import {cosmosScene} from './cosmos-scene.js';
import {brandMark} from './brand.js';
const icon=n=>`<i class="ph ph-${n}" aria-hidden="true"></i>`;
const session=window.__islandSession,journeyPath=session?(session.onboardingComplete?'/?view=studio':'/?view=onboarding'):'/?view=auth';
document.querySelector('#app').innerHTML=`<main id="universe" aria-label="虚空大陆 3D 群岛视图"></main><div id="ui"><div class="vignette"></div><header class="u-header"><a class="logo" href="/" aria-label="我们的岛首页">${brandMark()}<div><strong>我们的岛</strong><small>WORLDS, WRITTEN BY YOU</small></div></a><nav class="u-nav"><a href="${journeyPath}">${session?`${session.user.name}的岛`:'进入我的岛'}</a><span>每座岛，都是一个人的宇宙</span><button id="preview-info"><b></b>交互预览 · 模拟世界</button></nav></header><section class="u-intro"><div class="u-kicker">THE WORLD BEGINS WITH YOU</div><h1>喜欢自己，<br>比喜欢世界<em>更重要。</em></h1><p>把自己慢慢打磨成一座岛。<br>当你愿意发出独属于你的信号，世界会循光而来。</p><div class="small-rule"></div></section><div class="world-meta"><div><strong id="lit-count">472</strong><span>已点亮的示例世界</span></div><div class="sep"></div><div><strong>∞</strong><span>等待发生的想象</span></div></div><aside class="inspector" id="inspector"></aside><div class="u-tools"><button class="wide" id="simulate">${icon('sparkle')} 演示新岛加入</button><button id="u-zoom-in" aria-label="放大">${icon('plus')}</button><button id="u-zoom-out" aria-label="缩小">${icon('minus')}</button><button id="overview" aria-label="返回大陆全景">${icon('arrows-out')}</button></div><div class="join-dock"><div class="agent-icons">${icon('terminal-window')}${icon('asterisk')}</div><button class="gold-button" id="join">${icon('arrow-right')} ${session?'回到我的岛':'进入，点亮我的岛'} ${icon('arrow-up-right')}</button></div><div class="join-caption">先认识这片群岛，再开始书写你的世界</div><footer class="u-footer"><small>VOID ATLAS &nbsp; / &nbsp; 虚空大陆<br>每一处亮光，都始于一个想法。</small><div class="legend"><span><i></i>已点亮</span><span><i class="off"></i>等待加入</span></div><small>拖动探索 · 滚轮缩放 · 点击岛屿查看</small></footer><div class="world-event" role="status" id="world-event"></div><div id="modal-root"></div><div id="workspace-root"></div></div><div class="u-loading">正在展开虚空大陆<small>每一座岛，都是一个尚未说完的故事。</small></div>`;
let world,selected,own=null,agent='Codex',busy=false,noticeTimer;
function notify(text){const el=document.querySelector('#world-event');el.textContent=text;el.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove('visible'),4300);}
function inspect(item){selected=item;const el=document.querySelector('#inspector');el.innerHTML=`<div class="label">${item.active?'A WORLD BY AN AGENT':'AN UNWRITTEN WORLD'}</div><h2></h2><p></p><div class="by"><span class="owner"></span><span class="agent"></span></div><button class="inspect-button" id="inspect-action">${item.active?'靠近这座岛':'点亮我的世界'} ${icon('arrow-up-right')}</button>`;el.querySelector('h2').textContent=item.meta.name;el.querySelector('p').textContent=item.meta.description;el.querySelector('.owner').textContent=`@${item.meta.owner}`;el.querySelector('.agent').textContent=item.meta.agent;el.querySelector('#inspect-action').onclick=()=>item.active?focus(item):beginJourney();}
function beginJourney(){location.href=journeyPath;}
function staticWorld(){const root=document.querySelector('#universe');root.replaceChildren();root.classList.add('cosmos-fallback');const items=[{name:'风栖之地',owner:'mori',agent:'Codex',description:'把读过的书，种成一片会呼吸的森林。',type:0,active:true},{name:'月面档案馆',owner:'yue',agent:'Claude Code',description:'月球背面，收藏一些尚未抵达的未来。',type:1,active:true},{name:'落日温室',owner:'summer',agent:'Codex',description:'在永不落幕的黄昏里，等待一朵花开。',type:2,active:true},{name:'你的世界',owner:'你',agent:'尚未连接',description:'一座尚未亮起的岛，正在等待你的 Agent。',type:0,active:false}].map((meta,id)=>({id,type:meta.type,active:meta.active,meta}));root.innerHTML=`<div class="fallback-sky" aria-hidden="true"></div><div class="fallback-archipelago"></div><div class="fallback-note"><b>群岛轻盈模式</b><span>这台设备暂时无法开启 3D，仍可继续探索与创造。</span></div>`;const arch=root.querySelector('.fallback-archipelago');items.forEach((item,i)=>{const b=document.createElement('button');b.className=`fallback-island island-${i}${item.active?' is-lit':''}`;b.setAttribute('aria-label',item.meta.name);b.innerHTML=`<i></i><span>${item.meta.name}</span>`;b.onclick=()=>inspect(item);arch.append(b);});let extra=0;return {hero:items[0],lightIsland(type=0,meta=null){const item=items.find(x=>!x.active);if(!item)return null;item.active=true;item.type=type;item.meta=meta||item.meta;const button=arch.querySelector(`.island-${item.id}`);button.classList.add('is-lit');button.querySelector('span').textContent=item.meta.name;extra++;inspect(item);return item;},focus(id){arch.dataset.focus=id;},overview(){delete arch.dataset.focus;},zoom(){},stats(){return {drawCalls:0,worlds:472+extra};}};}
function startWorld(){const root=document.querySelector('#universe');const remote=!['localhost','127.0.0.1'].includes(location.hostname);const lightweight=remote||matchMedia('(max-width: 820px)').matches||new URLSearchParams(location.search).has('low3d');try{return cosmosScene(root,inspect,{lightweight});}catch(firstError){console.error('3D scene failed; switching to lightweight mode.',firstError);root.replaceChildren();if(!lightweight){try{return cosmosScene(root,inspect,{lightweight:true});}catch(secondError){console.error('Lightweight 3D scene failed; switching to the accessible archipelago.',secondError);root.replaceChildren();}}return staticWorld();}}
world=startWorld();inspect(world.hero);document.querySelector('#lit-count').textContent=world.stats().worlds;document.querySelector('.u-loading')?.remove();
function openConnect(){if(own){focus(own);return;}document.querySelector('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="connect-modal" role="dialog" aria-modal="true" aria-labelledby="connect-title"><button class="modal-close" aria-label="关闭连接窗口">×</button><div class="m-icon">${icon('plug')}</div><h2 id="connect-title">带上你的 Agent，<br>来创造一个世界。</h2><p>岛屿由你的 Agent 编写。建筑、地形、规则，<br>都可以长成你的想象。</p><div class="agent-options"><button class="agent-option active" data-agent="Codex">${icon('terminal-window')} Codex</button><button class="agent-option" data-agent="Claude Code">${icon('asterisk')} Claude Code</button></div><label class="field-label">API Key</label><div class="key-preview"><span>正式接入时在本地安全配置</span>${icon('lock-key')}</div><label class="field-label" for="vision">你想创造怎样的岛？</label><textarea id="vision" maxlength="240">一座漂浮在星海中的森林图书馆，有树木、暖灯和瀑布。</textarea><button class="gold-button" id="ignite">${icon('sparkle')} 预览连接，点亮我的岛</button><p class="privacy">当前演示不连接真实 Agent，不收集或保存密钥。</p><div class="progress-steps"><span>01 连接 Agent</span><span>02 编写世界</span><span>03 点亮岛屿</span></div></section></div>`;agent='Codex';document.querySelector('.modal-close').onclick=closeConnect;document.querySelectorAll('[data-agent]').forEach(b=>b.onclick=()=>{agent=b.dataset.agent;document.querySelectorAll('[data-agent]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelector('#ignite').onclick=ignite;document.querySelector('.modal-close').focus();}
function closeConnect(){if(busy)return;document.querySelector('#modal-root').innerHTML='';document.querySelector('#join').focus();}
async function ignite(){if(busy)return;busy=true;const btn=document.querySelector('#ignite'),vision=document.querySelector('#vision').value.trim()||'森林中的一座岛';btn.disabled=true;document.querySelector('.modal-close').disabled=true;document.querySelectorAll('[data-agent]').forEach(b=>b.disabled=true);document.querySelector('#vision').disabled=true;const steps=document.querySelectorAll('.progress-steps span');for(let i=0;i<3;i++){steps[i].classList.add('done');btn.textContent=['演示：连接你的 Agent…','演示：根据想象生成场景…','你的世界，正在亮起…'][i];await new Promise(r=>setTimeout(r,650));}
let type=/月|未来|极简|城市/.test(vision)?1:/花|温室|落日/.test(vision)?2:/神殿|寺|古/.test(vision)?3:/科技|太空|信号|赛博/.test(vision)?4:0;
own=world.lightIsland(type,{name:'你的第一座岛',owner:'you',agent,description:vision});busy=false;document.querySelector('#modal-root').innerHTML='';if(own){document.querySelector('#join').innerHTML=`${icon('code')} 进入我的世界 ${icon('arrow-up-right')}`;document.querySelector('#lit-count').textContent=world.stats().worlds;notify(`你的岛已点亮 · ${agent} 创作流程演示`);world.focus(own.id);document.body.classList.add('focus');setTimeout(()=>focus(own),1900);}}
function focus(item){world.focus(item.id);document.body.classList.add('focus');document.querySelector('#inspector').style.display='none';const root=document.querySelector('#workspace-root');root.innerHTML=`<aside class="workspace"><div class="u-kicker">${item===own?'YOUR AGENT WORKSPACE':'ISLAND PREVIEW'}</div><h2></h2><p class="description"></p><p>${item===own?'Agent 接入后的创作工作区示意。当前场景由本地程序生成，尚未执行 AI 代码。':'示例居民的独立世界。不同代码，可以创造完全不同的空间。'}</p><a class="inspect-button" id="land-visit">着陆探访 · 示例岛 ↓</a><pre></pre><button class="inspect-button" id="back-world">${icon('arrows-out')} 返回虚空大陆</button>${item===own?'<a href="/?view=island">体验之前的庭院布置玩法</a>':''}</aside>`;root.querySelector('#land-visit').href='/?view=visit&demo='+(['forest','planet','ocean','society','planet'][item.type]||'forest');root.querySelector('h2').textContent=item.meta.name;root.querySelector('.description').textContent=item.meta.description;root.querySelector('pre').textContent=`// 场景定义示意\nisland.create({\n  author: "${item.meta.owner}",\n  agent: "${item.meta.agent}",\n  biome: "${['forest','lunar','garden','temple','signal'][item.type]}",\n  floating: true,\n  light: "warm"\n});`;document.querySelector('#back-world').onclick=overview;}
function overview(){world.overview();document.body.classList.remove('focus');document.querySelector('#workspace-root').innerHTML='';document.querySelector('#inspector').style.display='';}
document.querySelector('#join').onclick=beginJourney;document.querySelector('#overview').onclick=overview;document.querySelector('#u-zoom-in').onclick=()=>world.zoom(.85);document.querySelector('#u-zoom-out').onclick=()=>world.zoom(1.15);document.querySelector('#preview-info').onclick=()=>notify('这是交互原型：群岛、居民与 Agent 连接均为演示，未接入多人服务器。');
let n=0;document.querySelector('#simulate').onclick=()=>{if(busy)return;overview();const item=world.lightIsland((++n)%5);if(!item){notify('本轮预留岛屿已全部点亮，刷新可重新演示');return;}document.querySelector('#lit-count').textContent=world.stats().worlds;notify(`新世界加入 · ${item.meta.name} 被点亮了`);};
addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.connect-modal')?closeConnect():overview();}if(e.key==='Tab'&&document.querySelector('.connect-modal')){const elements=[...document.querySelector('.connect-modal').querySelectorAll('button:not(:disabled),textarea:not(:disabled)')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.__cosmos={stats:()=>world.stats(),hasOwnIsland:()=>!!own};
