import './mailbox.css';
import {brandMark} from './brand.js';
const token=localStorage.getItem('our-island-owner-token'),urls=new Map();let selected=null,last='';
document.querySelector('#app').innerHTML=`<main class="mailbox"><header><a href="/">${brandMark()} 我们的岛</a><a href="/?view=studio">回到我的岛 ↗</a></header><section class="mail-heading"><small>LETTERS FROM YOUR ISLAND</small><h1>有些回声，<br>只为你而来。</h1><p>你留在岛上的心意，会在这里慢慢被读懂。</p></section><div class="mail-layout"><nav aria-label="岛内信" id="mail-list"></nav><article id="mail-content" aria-live="polite"></article></div><p id="mail-error" role="status"></p></main>`;
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
const names={portrait:'初次来信',change:'岛屿回声',daily:'一日潮汐'},states={queued:'等待写信',processing:'正在写信',waiting_provider:'等待分析服务',failed:'暂未送达',delivered:'已送达'},types=['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];
async function draw(rows){const list=document.querySelector('#mail-list'),body=document.querySelector('#mail-content');list.replaceChildren();body.replaceChildren();if(!rows.length){body.append(el('small','第一封信，还在未来'),el('h2','先让喜欢，长成风景。'),el('p','你的 Agent 完成岛屿代码后，来信会自动开始准备。这里不会展示其他账号或旧模板的报告。'));const a=el('a','去创造我的岛 →','mail-primary');a.href='/?view=studio';body.append(a);const button=el('button','为现在的岛准备一封信');button.onclick=async()=>{button.disabled=true;try{await api('/letters','POST',{});last='';await refresh();}catch(e){error(e);button.disabled=false;}};body.append(button);return;}
 selected=rows.some(r=>r.id===selected)?selected:rows[0].id;
 for(const row of rows){const b=el('button');b.setAttribute('aria-current',String(selected===row.id));b.append(el('small',names[row.kind]),el('strong',row.report?.title||states[row.status]),el('span',new Date(row.created_at).toLocaleString('zh-CN')));b.onclick=()=>{selected=row.id;draw(rows);};list.append(b);}
 const row=rows.find(r=>r.id===selected);body.append(el('small',`${names[row.kind]} · ${new Date(row.created_at).toLocaleDateString('zh-CN')}`));
 if(!row.report){body.append(el('h2',states[row.status]),el('p',row.status==='waiting_provider'?'你的岛屿和记忆已经保存。分析模型还没有配置好，连接后会继续写这封信。':row.status==='failed'?row.error:'先去岛上走走吧。信写好后，会留在这里。'));}
 else{const report=row.report;body.append(el('h2',report.title),el('p',report.portrait,'mail-portrait'));const panels=el('div',null,'mail-panels');for(const [index,theme] of (report.illustrations||report.themes).entries()){const panel=el('section');if(row.images.includes(index)){const img=document.createElement('img');img.alt=theme.title+' · 为这封信生成的插画';panel.append(img);const key=row.id+':'+index;if(urls.has(key))img.src=urls.get(key);else fetch(`/api/letters/${row.id}/images/${index}`,{headers:{Authorization:'Bearer '+token}}).then(r=>{if(!r.ok)throw Error('插画未加载');return r.blob();}).then(blob=>{const url=URL.createObjectURL(blob);urls.set(key,url);img.src=url;}).catch(()=>img.remove());}panel.append(el('h3',theme.title),el('p',theme.text));panels.append(panel);}body.append(panels,el('blockquote',report.letter));const mbti=el('section',null,'mail-mbti'),select=document.createElement('select'),saveType=el('button','按我的选择更正');mbti.append(el('small','MBTI · 一个可修改的猜想'),el('strong',report.mbti.type||'还不急着定义你'),el('p',report.mbti.type?report.mbti.note:'目前的表达还不足以推测完整类型。等岛慢慢生长，我们也会慢慢认识你。'));select.append(new Option('暂不选择',''),...types.map(type=>new Option(type,type)));select.value=report.mbti.source==='self_report'?report.mbti.type:'';saveType.onclick=async()=>{try{saveType.disabled=true;await api('/letters/mbti','PUT',{mbti:select.value||null});last='';await refresh();}catch(e){error(e);saveType.disabled=false;}};mbti.append(select,saveType,el('small','模型只是猜测，你对自己的判断优先。'));body.append(mbti);if(report.illustrationStatus!=='ready')body.append(el('p',report.illustrationStatus==='failed'?row.error:'文字已抵达。专属插画会在生图服务配置好后，通过重试生成。','mail-caption'));const form=document.createElement('form'),input=document.createElement('textarea'),button=el('button','记住我的修正');input.placeholder='有哪里不像你？写下你自己的理解。';input.setAttribute('aria-label','修正这封信对我的理解');input.maxLength=1000;input.required=true;form.append(input,button);form.onsubmit=async e=>{e.preventDefault();try{button.disabled=true;await api(`/letters/${row.id}/correction`,'POST',{content:input.value});button.textContent='已记住，下一封信会参考';}catch(e){error(e);button.disabled=false;}};body.append(form);}
 if(row.status!=='processing'){const retry=el('button',row.report?'重新写信 / 补上插画':'重试');retry.onclick=async()=>{try{retry.disabled=true;await api(`/letters/${row.id}/retry`,'POST',{});last='';await refresh();}catch(e){error(e);retry.disabled=false;}};body.append(retry);}
 const remove=el('button','删除这封信','mail-remove');remove.onclick=async()=>{try{await api(`/letters/${row.id}`,'DELETE');last='';await refresh();}catch(e){error(e);}};body.append(remove);
}
function error(e){document.querySelector('#mail-error').textContent=e.message;}
async function refresh(){try{const rows=await api('/letters'),signature=JSON.stringify(rows);if(signature!==last){last=signature;await draw(rows);}}catch(e){error(e);}}
refresh();const timer=setInterval(refresh,6000);addEventListener('pagehide',()=>{clearInterval(timer);urls.forEach(url=>URL.revokeObjectURL(url));});
