import './style.css';
import './brand.css';
import '@phosphor-icons/web/regular';
import {createWorld} from './world.js';
import {brandMark} from './brand.js';

const KEY='our-island-v1';
const defaults={coins:120,objects:[],weather:'clear',time:'sunset',music:'forest',expansions:0,collected:0,rewards:[],volume:.35};
const catalog={tree:{name:'落樱树',price:25,icon:'tree',tag:'自然 · 温柔'},pine:{name:'山间松',price:15,icon:'tree-evergreen',tag:'自然 · 安静'},bench:{name:'木长椅',price:20,icon:'armchair',tag:'生活 · 留白'},lamp:{name:'庭院灯',price:15,icon:'lamp',tag:'暖光 · 陪伴'},house:{name:'林间小屋',price:60,icon:'house-line',tag:'生活 · 温暖'},rock:{name:'苔石',price:10,icon:'mountains',tag:'自然 · 侘寂'}};
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s)return structuredClone(defaults);return {...defaults,coins:Number.isFinite(s.coins)&&s.coins>=0?Math.min(s.coins,100000):120,objects:Array.isArray(s.objects)?s.objects.filter(o=>catalog[o.type]&&Number.isFinite(o.x)&&Number.isFinite(o.z)&&Math.abs(o.x)<12&&Math.abs(o.z)<12&&typeof o.id==='string').slice(0,100):[],weather:['clear','rain','rainbow'].includes(s.weather)?s.weather:'clear',time:['sunset','night'].includes(s.time)?s.time:'sunset',music:['forest','piano','ambient'].includes(s.music)?s.music:'forest',expansions:Math.max(0,Math.min(3,Math.floor(s.expansions||0))),collected:Math.max(0,Number(s.collected)||0),rewards:Array.isArray(s.rewards)?s.rewards.filter(x=>['collect','build','weather'].includes(x)):[],volume:Math.max(0,Math.min(1,Number(s.volume)||.35))};}catch{return structuredClone(defaults);}}
const state=load();let activePanel=null,selected=null,visit=null,sound=false,toastTimer,weatherTouched=false;
const icon=name=>`<i class="ph ph-${name}" aria-hidden="true"></i>`;
document.querySelector('#app').innerHTML=`<main id="world" aria-label="可旋转与缩放的 3D 浮岛"></main><div class="overlay"><header class="topbar"><div class="brand"><div class="brand-mark">${icon('island')}</div><div><h1>我们的岛</h1><small>SOMEWHERE, TOGETHER</small></div></div><div class="topright"><div class="currency">${icon('sparkle')}<b id="coins">120</b><span>星光</span></div><button class="home" id="home">${icon('house-simple')} 回到我的岛</button><button class="round" id="sound" aria-label="开启环境音乐">${icon('speaker-slash')}</button></div></header><section class="intro"><div class="eyebrow">A LITTLE WORLD OF YOUR OWN</div><h2>在这里，慢一点。</h2><p>把喜欢的事物放在一起，<br>让相似的灵魂，慢慢靠近。</p></section><section class="island-status"><strong id="island-name">未眠岛</strong><span id="weather-caption">微风 · 日落时分</span><br><span id="area-caption">属于你的第 1 块天地</span></section><div class="side-tools"><button id="zoom-in" aria-label="放大">${icon('plus')}</button><button id="zoom-out" aria-label="缩小">${icon('minus')}</button><button id="camera-reset" aria-label="重置视角">${icon('arrows-counter-clockwise')}</button><button id="capture" aria-label="拍摄岛屿照片">${icon('camera')}</button></div><nav class="dock" aria-label="游戏工具"><button data-panel="build"><span class="symbol">${icon('armchair')}</span>布置岛屿</button><button data-panel="weather"><span class="symbol">${icon('sun-horizon')}</span>天气与光</button><button data-panel="music"><span class="symbol">${icon('music-notes')}</span>岛屿声音</button><div class="divider"></div><button data-panel="match"><span class="symbol">${icon('planet')}</span>遇见彼此</button><button data-panel="grow"><span class="symbol">${icon('plant')}</span>岛屿成长</button></nav><div class="hint">拖动环顾 · 滚轮缩放 · 点击漂浮星光收集</div><div class="coordinates">浮岛日记 / 001<br>云海之间，自在生长</div><div id="panel-root"></div><div id="build-root"></div><div id="visit-root"></div><div role="status" class="toast" id="toast"></div></div><div class="loading" id="loading">正在为你升起一座岛<small>树木、微风，还有一点点星光</small></div>`;
document.querySelector('.brand-mark').innerHTML=brandMark();
let world;
try{world=createWorld(document.querySelector('#world'),state,()=>{state.coins+=10;state.collected++;save();toast('拾起一束星光 +10');if(activePanel==='grow')renderPanel();},place);document.querySelector('#loading').remove();}catch(error){console.error(error);document.querySelector('#loading').innerHTML='暂时无法打开 3D 世界<small>请使用支持 WebGL 的浏览器，并开启硬件加速后刷新。</small>';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('浏览器存储已满，当前进度暂未保存');}updateHUD();world?.updateMatches(residents.map(r=>compatibility(r.vector)));}
function updateHUD(){document.body.classList.toggle("night",state.time==="night");document.querySelector('#coins').textContent=state.coins;document.querySelector('#weather-caption').textContent=`${{clear:'微风',rain:'细雨',rainbow:'雨后彩虹'}[state.weather]} · ${state.time==='night'?'星河入梦':'日落时分'}`;document.querySelector('#area-caption').textContent=`${state.expansions+1} 块地皮 · ${state.objects.length} 件心爱之物`;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600);}
function select(type){selected=type;world?.select(type);document.querySelector('#build-root').innerHTML=type?`<div class="build-tip">放置「${catalog[type].name}」 · 点击岛上空地 <button id="rotate">旋转 R</button><button id="cancel">取消 Esc</button></div>`:'';document.querySelector('#rotate')?.addEventListener('click',()=>world.rotate());document.querySelector('#cancel')?.addEventListener('click',()=>{select(null);renderPanel();});renderPanel();}
function place(obj){if(visit!==null)return;if(state.objects.length>=100){toast('岛上已有 100 件物品，请先撤回一些布置');return;}const item=catalog[obj.type];if(state.coins<item.price){toast('星光不足，点击岛上发光的小星星来收集');return;}const radius=obj.type==='house'?1.65:obj.type==='tree'?.85:.5;if(state.objects.some(o=>Math.hypot(o.x-obj.x,o.z-obj.z)<radius)){toast('这里有些拥挤，换一块空地试试');return;}const record={...obj,id:crypto.randomUUID()};state.coins-=item.price;state.objects.push(record);world.addObject(record);save();toast(`「${item.name}」已安放，进度已保存`);select(null);}
const residents=[{name:'南风',island:'慢慢岛',desc:'落樱、木琴与日落',icon:'flower-lotus',vector:[.95,.8,.6,.85,.7]},{name:'阿澈',island:'听雨岛',desc:'松林、细雨与独处',icon:'cloud-rain',vector:[.85,.3,1,.4,.9]},{name:'小满',island:'月亮邮局',desc:'屋灯、琴声与星空',icon:'moon-stars',vector:[.4,1,.7,1,.45]}];
function taste(){const count=t=>state.objects.filter(o=>o.type===t).length;return [Math.min(1,.5+(count('tree')+count('pine')+count('rock'))*.08),Math.min(1,.45+(count('lamp')+count('house'))*.13),state.weather==='rain'?1:state.weather==='rainbow'?.7:.3,state.music==='piano'?1:state.music==='ambient'?.7:.4,state.time==='night'?1:.35];}
function compatibility(v){const a=taste();const cosine=a.reduce((s,x,i)=>s+x*v[i],0)/(Math.hypot(...a)*Math.hypot(...v));return Math.round(cosine*100);}
function renderPanel(){document.querySelectorAll('[data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===activePanel);b.setAttribute('aria-expanded',String(b.dataset.panel===activePanel));});const root=document.querySelector('#panel-root');if(!activePanel){root.innerHTML='';return;}
let content='';
if(activePanel==='build')content=`<h3>心之所向，皆可安放。</h3><p>选一件喜欢的事物，放进你的世界。<br>每一个选择，都让这座岛更像你。</p><div class="object-grid">${Object.entries(catalog).map(([id,o])=>`<button class="object ${selected===id?'active':''}" data-object="${id}"><span class="obj-icon">${icon(o.icon)}</span><b>${o.name}</b><small>${o.tag}<br>${o.price} 星光</small></button>`).join('')}</div><button class="secondary" id="undo" ${!state.objects.length?'disabled':''}>撤回最后一次布置 · 返还星光</button><p style="margin:12px 0 0">布置与设置自动保存在当前浏览器。</p>`;
if(activePanel==='weather')content=`<h3>把天空调成喜欢的样子</h3><p>有些心情，只有天气懂。</p><div class="section-label">今日天气</div><div class="choices">${[['clear','sun','微风晴天'],['rain','cloud-rain','听一场雨'],['rainbow','rainbow','雨后彩虹']].map(([v,i,t])=>`<button class="choice ${state.weather===v?'active':''}" data-weather="${v}"><span>${icon(i)}</span>${t}</button>`).join('')}</div><div class="section-label">光的时间</div><div class="choices" style="grid-template-columns:1fr 1fr">${[['sunset','sun-horizon','日落时分'],['night','moon-stars','星河入梦']].map(([v,i,t])=>`<button class="choice ${state.time===v?'active':''}" data-time="${v}"><span>${icon(i)}</span>${t}</button>`).join('')}</div>`;
if(activePanel==='music')content=`<h3>让世界，轻轻响起。</h3><p>为这座岛挑选一段声音。<br>程序生成的循环音景，无需加载音频。</p><div class="choices">${[['forest','tree','林间风声'],['piano','piano-keys','晚间琴声'],['ambient','waveform','云端漫游']].map(([v,i,t])=>`<button class="choice ${state.music===v?'active':''}" data-music="${v}"><span>${icon(i)}</span>${t}</button>`).join('')}</div><button class="primary" id="toggle-sound">${sound?'暂停声音':'开启声音'}</button><label class="volume" for="volume">音量<span id="volume-label">${Math.round(state.volume*100)}%</span></label><input id="volume" type="range" min="0" max="1" step=".05" value="${state.volume}">`;
if(activePanel==='match')content=`<h3>有人，正在靠近。</h3><p>你的植物、光线和声音，构成独特的品味。<br>相似的人，会在这片云海中相遇。</p><div class="section-label">附近的岛屿 · 示例居民</div>${residents.map((r,i)=>`<div class="resident"><div class="avatar">${icon(r.icon)}</div><div class="info"><b>${r.name} · ${r.island}</b><small>${r.desc}</small><small>相距 ${Math.round(20+(100-compatibility(r.vector))*.7)} 米</small></div><div><span class="score">${compatibility(r.vector)}<small>%</small></span><br><button data-visit="${i}">去看看</button></div></div>`).join('')}<div class="tag-row"><span class="tag">${state.weather==='rain'?'偏爱雨天':'向往晴空'}</span><span class="tag">${state.music==='piano'?'钢琴爱好者':'自然派'}</span><span class="tag">${state.time==='night'?'夜的旅人':'日落收藏家'}</span></div><p style="margin:15px 0 0">契合度由本地品味向量计算。居民为演示数据，暂未连接真实玩家。</p>`;
if(activePanel==='grow'){const tasks=[['collect','收集 3 束星光',state.collected>=3,30],['build','安放 3 件心爱之物',state.objects.length>=3,50],['weather','为岛屿换一次天气',weatherTouched,20]];content=`<h3>小岛，和你一起生长。</h3><p>不用着急，把日子过成喜欢的样子。</p><div class="section-label">岛屿心愿</div>${tasks.map(([id,t,done,reward])=>`<div class="quest"><span>${t}</span><button data-reward="${id}" ${!done||state.rewards.includes(id)?'disabled':''}>${state.rewards.includes(id)?'已领取':`领取 ${reward}`}</button></div>`).join('')}<div class="section-label">拓展天地 · ${state.expansions+1} / 4 块地皮</div><p>向云海借一片地方，种下更多可能。</p><button class="primary" id="expand" ${state.expansions>=3?'disabled':''}>${state.expansions>=3?'已抵达本地岛屿面积上限':`扩建岛屿 · ${100+state.expansions*80} 星光`}</button>`;}
root.innerHTML=`<aside class="panel" aria-label="${activePanel}"><button class="close" aria-label="关闭面板">×</button>${content}</aside>`;
root.querySelector('.close').onclick=()=>{activePanel=null;select(null);renderPanel();};
root.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>{if(visit!==null){toast('先回到自己的岛，再开始布置');return;}select(selected===b.dataset.object?null:b.dataset.object);});
root.querySelector('#undo')?.addEventListener('click',()=>{const o=state.objects.pop();if(!o)return;world.removeObject(o.id);state.coins+=catalog[o.type].price;save();renderPanel();toast('已撤回，星光已返还');});
root.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;weatherTouched=true;world.weather();save();renderPanel();});root.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{state.time=b.dataset.time;world.weather();save();renderPanel();});
root.querySelectorAll('[data-music]').forEach(b=>b.onclick=()=>{state.music=b.dataset.music;save();if(sound)startAudio();renderPanel();});root.querySelector('#toggle-sound')?.addEventListener('click',toggleSound);
root.querySelector('#volume')?.addEventListener('input',e=>{state.volume=Number(e.target.value);if(audioGain)audioGain.gain.setTargetAtTime(state.volume*.3,audioCtx.currentTime,.1);document.querySelector('#volume-label').textContent=`${Math.round(state.volume*100)}%`;save();});
root.querySelectorAll('[data-visit]').forEach(b=>b.onclick=()=>{visit=Number(b.dataset.visit);world.visit(visit);activePanel=null;select(null);document.querySelector('#visit-root').innerHTML=`<div class="visit-banner">正在拜访 ${residents[visit].island} · 示例岛屿</div>`;document.querySelector('#island-name').textContent=residents[visit].island;});
root.querySelectorAll('[data-reward]').forEach(b=>b.onclick=()=>{const id=b.dataset.reward;if(state.rewards.includes(id))return;const eligible=id==='collect'?state.collected>=3:id==='build'?state.objects.length>=3:weatherTouched;if(!eligible)return;state.coins+=({collect:30,build:50,weather:20})[id];state.rewards.push(id);save();renderPanel();toast('心愿达成，星光已收入囊中');});
root.querySelector('#expand')?.addEventListener('click',()=>{const cost=100+state.expansions*80;if(state.expansions>=3)return;if(state.coins<cost){toast('星光还不够，再收集一些或完成岛屿心愿');return;}state.coins-=cost;state.expansions++;world.expand();save();renderPanel();toast('你的岛屿，长大了一点');});
}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{const next=activePanel===b.dataset.panel?null:b.dataset.panel;activePanel=next;select(null);renderPanel();});
function home(){world?.home();visit=null;document.querySelector('#visit-root').innerHTML='';document.querySelector('#island-name').textContent='未眠岛';}
document.querySelector('#home').onclick=home;document.querySelector('#camera-reset').onclick=home;document.querySelector('#zoom-in').onclick=()=>world?.zoom(.88);document.querySelector('#zoom-out').onclick=()=>world?.zoom(1.12);
document.querySelector('#capture').onclick=()=>{activePanel=null;renderPanel();toast('正在拍摄你的岛屿');requestAnimationFrame(()=>{requestAnimationFrame(()=>{const canvas=document.querySelector('canvas');canvas.toBlob(blob=>{if(!blob){toast('照片生成失败，请再试一次');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='我们的岛.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('岛屿照片已保存');});});});};
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='Escape'){selected?select(null):(activePanel=null,renderPanel());}if(e.key.toLowerCase()==='r'&&selected)world.rotate();});
let audioCtx,audioGain,audioTimer,audioNodes=[];
function stopAudio(){clearInterval(audioTimer);audioNodes.forEach(n=>{try{n.stop();}catch{}});audioNodes=[];if(audioGain){audioGain.disconnect();audioGain=null;}}
function startAudio(){stopAudio();audioCtx??=new AudioContext();audioCtx.resume();audioGain=audioCtx.createGain();audioGain.gain.value=state.volume*.3;audioGain.connect(audioCtx.destination);
if(state.music==='forest'){const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.04-.02)/1.02;data[i]=last*3;}const src=audioCtx.createBufferSource();src.buffer=buffer;src.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;src.connect(filter).connect(audioGain);src.start();audioNodes.push(src);}else{let n=0;const notes=state.music==='piano'?[261.63,329.63,392,493.88,440,392,329.63,293.66]:[130.81,196,261.63,293.66];const play=()=>{if(!audioGain)return;const osc=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;osc.type='sine';osc.frequency.value=notes[n++%notes.length];g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.3,now+.06);g.gain.exponentialRampToValueAtTime(.001,now+3);osc.connect(g).connect(audioGain);osc.start();osc.stop(now+3.1);};play();audioTimer=setInterval(play,state.music==='piano'?680:1600);}}
function toggleSound(){sound=!sound;if(sound)startAudio();else stopAudio();document.querySelector('#sound').innerHTML=icon(sound?'speaker-high':'speaker-slash');document.querySelector('#sound').setAttribute('aria-label',sound?'关闭环境音乐':'开启环境音乐');if(activePanel==='music')renderPanel();}
document.querySelector('#sound').onclick=toggleSound;
updateHUD();world?.updateMatches(residents.map(r=>compatibility(r.vector)));window.__island={getState:()=>structuredClone(state),getStats:()=>world?.getStats(),getCollectibleTargets:()=>world?.getCollectibleTargets()};
