import {PROMPTS} from './reflection-prompts.js';
import {createWorld} from './world.js';
import {brandMark} from './brand.js';
import './brand.css';
import './reflection.css';
const root=document.querySelector('#app');root.innerHTML=`<main class="reflection-page"><div id="reflection-world" aria-hidden="true"></div><header class="reflection-header"><a href="/">${brandMark()}我们的岛</a><a href="/?view=studio">回到我的岛 ↗</a></header><section class="reflection-paper"><nav><button id="mirror-tab">我理解的你</button><button id="timeline-tab">岛的来信</button></nav><div id="reflection-body"></div><p id="reflection-status" role="status"></p></section><footer>你拥有解释自己的最后一个字。</footer></main>`;
const body=document.querySelector('#reflection-body'),status=document.querySelector('#reflection-status'),token=localStorage.getItem('our-island-owner-token');
async function api(path,method='GET',data){const r=await fetch('/api'+path,{method,signal:AbortSignal.timeout(60000),headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},...(data?{body:JSON.stringify(data)}:{})});const json=await r.json();if(!r.ok)throw Error(json.error||'暂时没有连接上，请再试一次');return json;}
const el=(tag,text,className)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;};
function button(text,fn,primary=false){const b=el('button',text,primary?'reflection-primary':'');b.type='button';b.onclick=fn;return b;}
let record=null,answers={},step=0,busy=false;
const draftKey='island-reflection-draft-'+window.__islandSession?.user.id;
try{record=await api('/island/profile');answers=record?.answers||{};const me=await api('/me');try{const world=createWorld(document.querySelector('#reflection-world'),{...me.island.scene,objects:[],expansions:0},()=>{},()=>{},{ecosystemOnly:true,lightweight:true});world.setEcology(me.island.scene);}catch{document.querySelector('#reflection-world').hidden=true;}if(record&&!('space' in record.answers))renderMirror();else analyzeIsland();}catch(e){status.textContent=e.message;body.append(button('重新加载',()=>location.reload()));}
function clear(){body.replaceChildren();status.textContent='';}
async function analyzeIsland(){if(busy)return;busy=true;clear();document.querySelector('.reflection-paper nav').hidden=true;body.append(el('small','岛建成以后，Agent 才开始理解'),el('h1','我正在岛上，\n慢慢认识你。'),el('p','我会看你留下的世界、光、住处、动物与风景，把它们放在一起读。'));try{record=await api('/island/analyze-design','POST',{expression:sessionStorage.getItem('island-guided-notes')||''});answers=record.answers;sessionStorage.removeItem('island-guided-notes');renderMirror();}catch(e){status.textContent=e.message;body.append(button('再读一次我的岛',analyzeIsland,true),button('先回岛上',()=>location.href='/?view=studio'));}finally{busy=false;}}
function question(){clear();document.querySelector('.reflection-paper nav').hidden=true;const q=PROMPTS[step];body.append(el('small',`${String(step+1).padStart(2,'0')} / 07 · 慢慢认识你的岛`),el('h1',q.title),el('p',q.hint));const choices=el('div',undefined,'reflection-choices'),input=el('textarea');input.maxLength=400;input.setAttribute('aria-label',q.title);input.placeholder='也可以写下你自己的答案……';input.value=answers[q.key]||'';const next=button(step===6?'让这些喜欢留在岛上 →':'继续 →',()=>{if(!input.value.trim())return;answers[q.key]=input.value.trim();sessionStorage.setItem(draftKey,JSON.stringify(answers));step===6?analyze(): (step++,question());},true);next.disabled=!input.value.trim();for(const value of q.options){const b=button(value,()=>{input.value=value;answers[q.key]=value;input.dispatchEvent(new Event('input'));});b.setAttribute('aria-pressed',String(input.value===value));choices.append(b);}input.oninput=()=>{answers[q.key]=input.value;sessionStorage.setItem(draftKey,JSON.stringify(answers));next.disabled=!input.value.trim();for(const b of choices.children)b.setAttribute('aria-pressed',String(b.textContent===input.value));};body.append(choices,el('label','我自己的想法'),input);const actions=el('div',undefined,'reflection-actions');actions.append(button(step?'← 上一步':'先回岛上',()=>step?(step--,question()):location.assign('/?view=studio')),next);body.append(actions);if(step===0)body.append(el('p','Agent 会根据你留下的想法整理来信，回答与草稿保存在你的账号。你可以随时查看、修改或删除；用于寻找同伴时，会另行询问你。','reflection-note'));const heading=body.querySelector('h1');heading.tabIndex=-1;heading.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
async function analyze(){if(busy)return;busy=true;clear();body.append(el('small','你的话，正在慢慢成为一封信'),el('h1','让我把这些片刻，\n轻轻放在一起。'),el('p','你的选择已经留在这里。通常需要几十秒。'));try{record=await api('/island/analyze-onboarding','POST',{answers,revision:record?.revision||0,analysisConsent:true});renderMirror();}catch(e){status.textContent=e.message;body.append(button('保留回答，再试一次',analyze,true),button('返回修改',()=>{step=6;question();}));}finally{busy=false;}}
function renderMirror(){
 clear();document.querySelector('.reflection-paper nav').hidden=false;if(!record){analyzeIsland();return;}
 const hasReport=!!record.mirror.analysis;
 body.append(el('small',['codex','deepseek'].includes(record.mirror.engine)?'AGENT 个人画像 · 来自你的岛':'岛屿个人画像'),el('h1',hasReport?'你的个人分析报告。':'我理解的你。'));
 if(record.mirror.notice&&!hasReport)body.append(el('p',record.mirror.notice,'reflection-note'));
 if(hasReport){
  const report=el('section',undefined,'reflection-report');report.append(el('small','综合画像'),el('h2',record.mirror.analysis.headline),el('p',record.mirror.analysis.overview));
  const prediction=record.mirror.analysis.measurement?.mbti||record.profile?.mbti_prediction;if(prediction?.type){const card=el('section',undefined,'reflection-mbti'),identity=el('div'),type=el('strong',prediction.type),confidence=el('span',prediction.confidence>=.72?'倾向较清晰':prediction.confidence>=.58?'倾向中等':'轻微倾向'),dimensions=el('div',undefined,'reflection-mbti-axes');identity.append(el('small','MBTI 倾向推测'),type,confidence);for(const dimension of prediction.dimensions||[])dimensions.append(el('span',`${dimension.letter} · ${dimension.label}`));card.append(identity,el('p',prediction.summary),dimensions,el('small','由岛屿设计推测，可以被你改写。'));report.append(card);}
  const lensLabels={environmental_preference:'环境偏好',narrative_identity:'自我叙事',social_imagination:'相遇想象',spatial_boundary:'空间与边界',symbolic_association:'意象联想'};
  const illustrationAlts=['从云端瀑布走向岛屿的小小旅人','在树林中与鸟和独角兽相伴的人','坐在花草间望向浮岛的人','看着路径与植物在岛上生长的人'];
  record.mirror.analysis.themes.forEach((theme,index)=>{const article=el('article',undefined,'reflection-theme'),figure=el('figure',undefined,`reflection-illustration panel-${index%4}`),image=document.createElement('img'),words=el('div');image.src='/images/reflection-storybook.png';image.alt=illustrationAlts[index%4];figure.append(image);words.append(el('small',lensLabels[theme.lens]||'个人画像'),el('h3',theme.title),el('p',theme.reading));article.append(figure,words);report.append(article);});
  if(record.mirror.analysis.measurement)report.append(el('p','这份画像会随着你的岛一起变化，你随时可以改写它。','reflection-measurement'));
  body.append(report);
 }
 const letter=el('div',undefined,'reflection-letter');if(hasReport)letter.append(el('small','写给你'));record.mirror.lines.forEach((line,i)=>{const p=el('p',line.text);p.style.setProperty('--delay',`${i*1.3}s`);letter.append(p);});body.append(letter);
 if(record.mirror.correction)body.append(el('blockquote','以你后来告诉我的为准：'+record.mirror.correction));
 if(record.confirmed){body.append(el('p','那我记住了。以后岛改变了，我也会重新认识现在的你。','reflection-closing'));if(record.mirror.verdict==='corrected')body.append(el('p','你的修正已经成为这份理解里最重要的依据。','reflection-note'));if(record.profile.mbti)body.append(el('p','你为自己选择的类型：'+record.profile.mbti));const actions=el('div',undefined,'reflection-actions');actions.append(button('保存这封信',()=>share('我理解的你',shareText())),button('重新读一次我的岛',analyzeIsland),button('去岛上生活 →',()=>location.href='/?view=studio',true));body.append(actions);settings();return;}
const correction=el('textarea');correction.maxLength=1000;correction.placeholder='不是因为害怕热闹，只是今天想安静一点……';correction.setAttribute('aria-label','我想修正的地方');correction.hidden=true;
const matching=el('label',undefined,'reflection-consent'),check=document.createElement('input');check.type='checkbox';matching.append(check,document.createTextNode('愿意用我确认的品味选择，寻找同样愿意被发现的人。'));body.append(matching,correction);
let verdict='accepted';const agree=button('是我，那就记住吧 →',async()=>{if(busy)return;busy=true;agree.disabled=true;try{record=await api('/island/confirm-mbti','POST',{revision:record.revision,verdict,correction:correction.value,mbti:null,matchingConsent:check.checked});sessionStorage.removeItem(draftKey);renderMirror();}catch(e){status.textContent=e.message;agree.disabled=false;}finally{busy=false;}},true);
body.append(button('不太对，我想改一改',()=>{verdict='corrected';correction.hidden=false;correction.focus();agree.textContent='按我说的记住 →';}),agree,button('这次先不记住',async()=>{try{await api('/island/discard-draft','POST',{revision:record.revision});location.href='/?view=studio';}catch(e){status.textContent=e.message;}}));}
function shareText(){const analysis=record.mirror.analysis,prediction=analysis?.measurement?.mbti||record.profile?.mbti_prediction;const report=analysis?`\n\n${analysis.headline}\n${analysis.overview}${prediction?.type?`\n\nMBTI 倾向推测：${prediction.type}\n${prediction.summary}`:''}`:'';return record.mirror.lines.map(l=>l.text).join('\n\n')+report+(record.mirror.correction?'\n\n我的补充：'+record.mirror.correction:'');}
function settings(){const detail=el('details'),summary=el('summary','由我决定，哪些被记住');detail.append(summary);const observation=el('label',undefined,'reflection-consent'),observe=document.createElement('input');observe.type='checkbox';observe.checked=record.analysisConsent;observation.append(observe,document.createTextNode('记录岛屿变化，为我留下日签'));const sharing=el('label',undefined,'reflection-consent'),match=document.createElement('input');match.type='checkbox';match.checked=record.matchingConsent;sharing.append(match,document.createTextNode('允许双方确认的品味参与匹配'));detail.append(observation,sharing,button('保存选择',async()=>{try{record=await api('/island/profile/settings','PUT',{analysisConsent:observe.checked,matchingConsent:match.checked});status.textContent='已按你的选择保存。';}catch(e){status.textContent=e.message;}}));const erase=button('删除这份画像和日签',()=>{erase.replaceWith(button('确定删除画像、历史与对应记忆',async()=>{try{await api('/island/profile','DELETE');record=null;answers={};sessionStorage.removeItem(draftKey);analyzeIsland();}catch(e){status.textContent=e.message;}}));});detail.append(button('导出完整画像与来信',async()=>{try{const data=await api('/island/profile/export'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='我们的岛-理解与来信.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){status.textContent=e.message;}}),erase);body.append(detail);}
async function timeline(){if(busy)return;clear();document.querySelector('.reflection-paper nav').hidden=false;body.append(el('small','不是每天都有信，只有风景改变的时候'),el('h1','岛的来信。'));try{await api('/island/detect-change','POST',{});const cards=await api('/island/timeline');if(!cards.length)body.append(el('p','暂时没有新的来信。等岛上的天气、声音或生活发生变化，我会留下一笔。'));for(const card of cards){const article=el('article',undefined,'reflection-daily');article.append(el('small',card.day),el('p',card.text));const detail=el('details'),summary=el('summary','这一次，我看见了什么');detail.append(summary);for(const e of card.evidence)detail.append(el('p',`${e.label}：${e.before??'未设置'} → ${e.after??'未设置'}`));article.append(detail);const favorite=button(card.favorite?'已收藏 ♥':'收藏这封信 ♡',async()=>{try{await api('/island/cards/'+card.id,'PUT',{favorite:!card.favorite,response:card.response});card.favorite=!card.favorite;favorite.textContent=card.favorite?'已收藏 ♥':'收藏这封信 ♡';}catch(e){status.textContent=e.message;}});article.append(favorite,button('保存日签',()=>share('岛的来信 · '+card.day,card.text)));body.append(article);}}catch(e){status.textContent=e.message;}}
async function share(title,text){await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1080;const ctx=canvas.getContext('2d');ctx.font='32px "PingFang SC", sans-serif';const lines=[];for(const paragraph of text.split('\n')){let line='';for(const char of paragraph){if(ctx.measureText(line+char).width>870){lines.push(line);line=char;}else line+=char;}lines.push(line);}canvas.height=Math.max(1080,340+lines.length*58);ctx.fillStyle='#f5f3e8';ctx.fillRect(0,0,1080,canvas.height);ctx.fillStyle='#3e6656';ctx.font='26px "PingFang SC", sans-serif';ctx.fillText('我们的岛 / SOMEWHERE, TOGETHER',100,100);ctx.font='52px "PingFang SC", sans-serif';ctx.fillText(title,100,205);ctx.font='32px "PingFang SC", sans-serif';lines.forEach((line,i)=>ctx.fillText(line,100,310+i*58));ctx.font='22px "PingFang SC", sans-serif';ctx.fillText('你拥有解释自己的最后一个字。',100,canvas.height-65);canvas.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='我们的岛-来信.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);});}
document.querySelector('#mirror-tab').onclick=()=>{if(!busy)record?renderMirror():analyzeIsland();};document.querySelector('#timeline-tab').onclick=timeline;
if(new URLSearchParams(location.search).get('tab')==='timeline')timeline();
