if(!['localhost','127.0.0.1','[::1]'].includes(location.hostname))localStorage.setItem('island-agent-route','external');
import {mountAgentConnection} from './agent-connection.js';
import {preferenceDescription} from '../server/preferences.js';
import {mountIslandMusic} from './island-music.js';
import './dream.css';
import '@phosphor-icons/web/regular';
import {createWorld} from './world.js';
import {starterEcosystem} from '../server/ecosystem.js';
const icon=n=>`<i class="ph ph-${n}" aria-hidden="true"></i>`;
let token=localStorage.getItem('our-island-owner-token'),me=null,busy=false,world,jobId=null,pollTimer;
const initial=starterEcosystem(),state={...initial,objects:[],expansions:0};
document.querySelector('#app').innerHTML=`<main id="dream-world" aria-label="由 Agent 创作的完整浮岛生态"></main><div class="dream-ui"><header><a href="/">${icon('arrow-left')} 虚空大陆</a><a href="/?view=visit">探访别人的岛</a><a href="/?view=onboarding">选择世界起点</a><button id="dream-reset" aria-label="恢复岛屿视角">${icon('arrows-out')}</button></header><section class="dream-intro"><small>A WORLD THAT GROWS WITH YOU</small><h1>让这座岛，<br>长成你的样子。</h1><p>你说出想象，Agent 照料整个世界。<br>森林、溪流、微光，还有自由生长的生命。</p></section><section class="dream-chat"><div class="dream-agent">${icon('sparkle')}<span>岛屿创作伙伴</span><small id="agent-state">本机 Codex</small><button type="button" id="connect-agent">连接 Agent</button></div><div id="dream-message" role="status">想让这座岛发生什么变化？</div><form id="dream-form"><label class="sr-only" for="dream-prompt">描述你想要的岛屿</label><textarea id="dream-prompt" maxlength="3000" placeholder="我想要一片雨后的森林，有溪流和萤火虫，不需要房子……" required></textarea><div class="dream-actions"><small>只需描述，不必布置</small><button type="submit" id="dream-submit">让岛屿生长 ${icon('arrow-up')}</button></div></form><div class="dream-suggestions"><button data-idea="把岛变成雨后湿地：溪流连接一片浅水塘，岸边种花，傍晚有萤火虫。不要建筑。">雨后湿地</button><button data-idea="我想要开满粉色小花的春日草甸，散落几棵树，有鸟和兔子，保留溪流和瀑布，不要房子。">春日草甸</button><button data-idea="让这片岛安静下来：增加松林和苔石，保留水系，变成有萤火虫的星夜。不要新增建筑。">星夜松林</button></div><button id="dream-undo" hidden>撤回上次变化</button></section><div class="dream-footnote">拖动环顾 · 滚轮缩放<br><span id="save-state">一座等待与你共同生长的岛</span></div><div class="dream-loading">正在唤醒你的岛…</div></div>`;
try{world=createWorld(document.querySelector('#dream-world'),state,()=>{},()=>{},{ecosystemOnly:true});world.setEcology(initial);document.querySelector('.dream-loading').remove();}catch(e){document.querySelector('.dream-loading').textContent='无法打开 3D 场景，请启用浏览器硬件加速。';console.error(e);}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,signal:AbortSignal.timeout(15000),headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'暂时无法连接'),{status:r.status});return data;}
const programStatus=document.createElement('p');programStatus.className='dream-program-status';programStatus.setAttribute('role','status');document.querySelector('.dream-chat').append(programStatus);
addEventListener('island-program-status',e=>{programStatus.textContent=e.detail;});

function message(s){document.querySelector('#dream-message').textContent=s;}
const externalAgent=()=>localStorage.getItem('island-agent-route')==='external';
function setBusy(v){busy=v;document.querySelector('#dream-submit').disabled=v;document.querySelector('#dream-prompt').disabled=v;document.querySelectorAll('[data-idea]').forEach(b=>b.disabled=v);document.querySelector('#dream-undo').disabled=v;document.querySelector('#agent-state').textContent=v?'等待 Agent 写代码…':externalAgent()?'我的编程 Agent':'本机 Codex';document.querySelector('#dream-submit').innerHTML=v?'正在生长…':`让岛屿生长 ${icon('arrow-up')}`;}
async function refresh(){me=await api('/me');if(!busy&&me.latestCreation?.status==='completed'){message(me.latestCreation.summary);document.querySelector('#dream-undo').hidden=false;}if(!busy&&me.latestCreation?.status==='failed')message(me.latestCreation.error);world?.setEcology(me.island.scene);document.querySelector('#save-state').textContent=`变化已保存 · 第 ${me.island.revision} 次生长`;document.body.classList.toggle('dream-night',me.island.scene.time==='night');}
async function ensureOwner(){if(!token){location.href='/?view=auth';throw new Error('请先登录');}if(!me)await refresh();}
async function poll(){try{const job=await api(`/creations/${jobId}`);if(job.prompt&&!document.querySelector('#dream-prompt').value)document.querySelector('#dream-prompt').value=job.prompt;if(job.status==='running'){const seconds=Math.max(0,Math.floor((Date.now()-Date.parse(job.created_at))/1000));message(`Agent 尚未提交代码 · 已等待 ${Math.floor(seconds/60)} 分 ${seconds%60} 秒。${externalAgent()?'请保持自己的 Agent 运行连接说明，任务最多保留 30 分钟。':'最长等待 5 分钟。'}`);pollTimer=setTimeout(poll,1800);return;}setBusy(false);sessionStorage.removeItem('island-creation-job');if(job.status==='completed'){await refresh();message(job.summary);document.querySelector('#dream-prompt').value='';sessionStorage.removeItem('island-onboarding-draft');sessionStorage.removeItem('island-studio-draft');document.querySelector('#dream-undo').hidden=false;}else message(job.error||'本次创作未完成，你的岛保持原样。');}catch(e){setBusy(false);message('暂时取不到任务状态，岛屿未被本次查询改变。刷新页面可继续查看。');}}
document.querySelector('#dream-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const prompt=document.querySelector('#dream-prompt').value.trim();if(!prompt)return;sessionStorage.setItem('island-studio-draft',prompt);setBusy(true);message('正在把你的想象交给 Agent…');try{await ensureOwner();const status=externalAgent()?{available:true}:await api('/creator');if(!status.available)throw new Error('还没有连接可用的 Agent。你的描述已保留，连接后即可创作。');const job=await api(`/islands/${me.island.id}/${externalAgent()?'request-code':'imagine'}`,'POST',{prompt});jobId=job.jobId;sessionStorage.setItem('island-creation-job',jobId);message(externalAgent()?'等待你连接的 Agent 领取请求并编写代码。':'本机 Codex 正在编写代码，返回后将在隔离环境中运行。');poll();}catch(e){setBusy(false);message(e.message);}};
document.querySelectorAll('[data-idea]').forEach(b=>b.onclick=()=>{document.querySelector('#dream-prompt').value=b.dataset.idea;document.querySelector('#dream-prompt').focus();});document.querySelector('#dream-reset').onclick=()=>world?.home();document.querySelector('#dream-undo').onclick=async()=>{if(busy||!me)return;setBusy(true);try{await api(`/islands/${me.island.id}/undo-creation`,'POST',{});await refresh();message('已经回到上一次的岛。我们可以换一种想法。');document.querySelector('#dream-undo').hidden=true;}catch(e){message(e.message);}finally{setBusy(false);}};
if(token){try{await refresh();const pending=sessionStorage.getItem('island-creation-job');if(pending){jobId=pending;setBusy(true);poll();}}catch(e){if(e.status===401){token=null;localStorage.removeItem('our-island-owner-token');}else message(e.message);}}
addEventListener('pagehide',()=>clearTimeout(pollTimer));

mountIslandMusic(document.querySelector(".dream-ui"));

const arrivalDraft=sessionStorage.getItem('island-studio-draft')||sessionStorage.getItem("island-onboarding-draft");if(arrivalDraft)document.querySelector("#dream-prompt").value=arrivalDraft;
if(sessionStorage.getItem("island-onboarding-create")){sessionStorage.removeItem("island-onboarding-create");document.querySelector("#dream-form").requestSubmit();}

if(token){try{const memory=await api('/preferences');if(memory){const details=document.createElement('details');details.className='dream-memory';const summary=document.createElement('summary');summary.textContent='Agent 记住的偏好';const p=document.createElement('p');p.textContent=preferenceDescription(memory.payload);const button=document.createElement('button');button.textContent='忘记这些偏好';button.onclick=async()=>{button.disabled=true;try{await api('/preferences','DELETE');details.remove();message('已删除偏好记忆，岛屿保持原样。');}catch(e){button.disabled=false;message(e.message);}};details.append(summary,p,button);document.querySelector('.dream-chat').append(details);}}catch{}}

addEventListener('pageshow',e=>{if(e.persisted&&sessionStorage.getItem('island-creation-job')){clearTimeout(pollTimer);jobId=sessionStorage.getItem('island-creation-job');setBusy(true);poll();}});

mountAgentConnection({api,ensureOwner,getMe:()=>me,refresh});

addEventListener('island-agent-route',()=>{if(!busy)setBusy(false);});if(!busy)setBusy(false);
