import {FURNITURE} from './home-interior.js';
import {DEFAULT_AVATAR_CODE} from './player-avatar.js';
import {createWorld} from './world.js';
import {starterEcosystem} from '../server/ecosystem.js';
import {applyPreferences} from '../server/preferences.js';
import './visit.css';
const params=new URLSearchParams(location.search),id=params.get('island'),demo=params.get('demo'),own=params.get('own')==='1';
const names={home:'林间小屋 · 交互体验',forest:'林间来信',ocean:'潮汐停靠站',desert:'风的沙丘',plain:'无边草场',alpine:'雪线之上',society:'晚灯小镇',planet:'星环旅居'};
const root=document.querySelector('#app');root.innerHTML=`<main id="visit-world"></main><header class="visit-header"><a href="/?view=studio">← 回我的岛</a><a href="/?view=universe">返回云海</a></header><section class="visit-panel"><small id="visit-kind">走近另一个人的世界</small><h1 id="visit-title">去远方，停留片刻。</h1><p id="visit-description">选择一座岛，落下来，慢慢走一走。</p><div id="visit-list"></div><button id="land" hidden>着陆到岛上 ↓</button><button id="takeoff" hidden>起飞 · 看看全岛</button><p id="visit-status" role="status"></p></section><div class="walk-hud" hidden><span>拖动环顾 · WASD / 方向键行走 · Esc 起飞</span><div class="walk-pad" aria-label="行走方向"><button data-walk="w" aria-label="向前走">↑</button><button data-walk="a" aria-label="向左走">←</button><button data-walk="s" aria-label="向后走">↓</button><button data-walk="d" aria-label="向右走">→</button></div></div>`;
const status=text=>document.querySelector('#visit-status').textContent=text;
async function api(path,method='GET',body){const token=localStorage.getItem('our-island-owner-token');const response=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw Error(data.error||'暂时无法探访');return data;}
let world,scene,ownedRecord,avatarRecord={revision:0,source:''};
function link(title,href,detail){const a=document.createElement('a');a.href=href;const b=document.createElement('strong'),small=document.createElement('small');b.textContent=title;small.textContent=detail;a.append(b,small);document.querySelector('#visit-list').append(a);}
if(!id&&!demo&&!own){
 for(const [kind,title] of Object.entries(names))link(title,'/?view=visit&demo='+kind,'示例岛 · 可以着陆漫步');
 if(localStorage.getItem('our-island-owner-token')){try{const islands=await api('/world');for(const island of islands)link(island.name,'/?view=visit&island='+encodeURIComponent(island.id),'真实用户 · 已开放发现');status(islands.length?'下面也列出了已开放的用户岛屿。':'目前没有其他已开放的用户岛屿，可以先探访示例岛。');}catch(e){status(e.message);}}
 else status('先体验示例岛；创建自己的岛后，可查看已开放的用户岛屿。');
}else{
 try{
 if(own){const account=await api('/me'),record=account.island;ownedRecord=record;scene=record.scene;document.querySelector('#visit-title').textContent=record.name;document.querySelector('#visit-kind').textContent='我的岛 · 岛主漫游';}
 else if(id){const record=await api('/islands/'+encodeURIComponent(id));scene=record.scene;document.querySelector('#visit-title').textContent=record.name;document.querySelector('#visit-kind').textContent='已开放的用户岛屿 · 只读探访';}
 else{if(!names[demo])throw Error('这座示例岛不存在');scene=applyPreferences(starterEcosystem(),{world:demo,variant:8,animals:'bird',home:'open',landscape:'forest',light:'balanced'});document.querySelector('#visit-title').textContent=names[demo];document.querySelector('#visit-kind').textContent='示例岛 · 非真实用户';}
 document.querySelector('#visit-description').textContent=own?'先在云端看一眼，再落到你刚刚创造的生态里。可以行走，也可以靠近并点击会回应的生命。':'先在云端看一眼，再落到这片风景里。探访不会修改岛主的世界。';
 if(demo==='home'){scene=applyPreferences(starterEcosystem(),{world:'forest',variant:8,animals:'none',home:'open',landscape:'forest',light:'balanced'});scene.rooms=[{id:'demo-room',houseId:'demo-house',name:'林间小屋',width:8,depth:6,height:3.2}];scene.objects.push({id:'demo-house',kind:'house',x:0,y:0,z:-1,rotation:0,color:'cream'},...['sofa','recordPlayer','bookshelf','table','plant','lamp'].map((kind,i)=>({id:'f'+i,kind,roomId:'demo-room',x:[-2.5,2.2,-2.4,-1.5,3,-3][i],y:0,z:[0,-1.5,-2.5,0,1.5,1.7][i],rotation:0,color:'wood'})));}
 const pet=params.get('pet');if(demo&&['cat','dog','bird','rabbit','bear','fox','unicorn'].includes(pet))scene.objects.push({id:'preview-pet',kind:pet,x:1.2,y:0,z:5.2,rotation:.5,color:'cream'});
 world=createWorld(document.querySelector('#visit-world'),{...scene,objects:[],expansions:0},()=>{},()=>{},{ecosystemOnly:true});world.setEcology(scene);if(!demo)try{avatarRecord=await api('/avatar');world.setAvatar(avatarRecord.source);}catch{}document.querySelector('#land').hidden=false;
 }catch(e){status(e.message);document.querySelector('#visit-description').textContent='未进入这座岛。你可以返回，选择另一座开放的岛。';}
}
function takeoff(){world?.takeoff();document.body.classList.remove('walking');document.querySelector('.walk-hud').hidden=true;document.querySelector('#land').hidden=false;document.querySelector('#takeoff').hidden=true;status('已回到空中，可以再次着陆。');}
document.querySelector('#land').onclick=()=>{if(!world?.land()){status('暂时找不到安全的落脚点，等场景加载完成后再试。');return;}document.body.classList.add('walking');document.querySelector('.walk-hud').hidden=false;document.querySelector('#land').hidden=true;document.querySelector('#takeoff').hidden=false;status('正在降落 · 到达后可以自由行走');setTimeout(()=>{if(document.body.classList.contains('walking'))status('已着陆 · 慢慢逛，也可以随时起飞');},1500);};
document.querySelector('#takeoff').onclick=takeoff;addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&document.body.classList.contains('walking'))takeoff();});
for(const button of document.querySelectorAll('[data-walk]')){button.onpointerdown=e=>{button._pressedAt=performance.now();e.preventDefault();button.setPointerCapture(e.pointerId);world?.walkInput(button.dataset.walk,true);};for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>{world?.walkInput(button.dataset.walk,false);});}
// An open page must also stop a visit when access is withdrawn.
if(id&&world){const timer=setInterval(async()=>{try{await api('/islands/'+encodeURIComponent(id));}catch{world.takeoff();document.querySelector('#visit-world').hidden=true;document.querySelector('#land').hidden=true;document.querySelector('#takeoff').hidden=true;document.querySelector('.walk-hud').hidden=true;status('探访权限已不可用，已结束本次探访。');clearInterval(timer);}},15000);addEventListener('pagehide',()=>clearInterval(timer));}
for(const button of document.querySelectorAll('[data-walk]'))button.onclick=()=>{if(button._pressedAt&&performance.now()-button._pressedAt>180)return;world?.walkInput(button.dataset.walk,true);setTimeout(()=>world?.walkInput(button.dataset.walk,false),180);};
window.__visit={stats:()=>world?.getStats()};

const toolbar=document.createElement('div');toolbar.className='visit-actions';toolbar.innerHTML=`<div class="camera-choices" aria-label="切换视角"><button data-camera="third" aria-pressed="true">跟随</button><button data-camera="first" aria-pressed="false">第一人称</button><button data-camera="overhead" aria-pressed="false">俯瞰</button></div><button id="interact" hidden></button><button id="leave-room" hidden>回到岛上</button><button id="decorate" hidden>布置房间</button><button id="avatar-edit">我的形象</button><a href="/?view=animals" target="_blank">动物图鉴</a><p id="walk-message" role="status"></p>`;document.body.append(toolbar);if(demo){const label=document.createElement('label');label.className='pet-preview';label.textContent='看看岛上的邻居 ';const select=document.createElement('select');select.setAttribute('aria-label','选择动物预览');select.add(new Option('选择小动物',''));for(const [id,name] of Object.entries({cat:'猫',dog:'狗',bird:'小鸟',rabbit:'兔子',bear:'熊猫',fox:'狐狸',unicorn:'独角兽'}))select.add(new Option(name,id));select.value=params.get('pet')||'';select.onchange=()=>{const url=new URL(location.href);url.searchParams.set('pet',select.value);location.assign(url);};label.append(select);toolbar.prepend(label);}
const feedback=text=>document.querySelector('#walk-message').textContent=text;
const dialog=document.createElement('dialog');dialog.className='visit-dialog';document.body.append(dialog);
const cameraButtons=[...document.querySelectorAll('[data-camera]')];let cameraMode='third';
function chooseCamera(mode){world?.setView(mode);cameraMode=mode;cameraButtons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.camera===mode)));}
for(const b of cameraButtons)b.onclick=()=>chooseCamera(b.dataset.camera);
const interact=document.querySelector('#interact');let nearbyHouse=null;
const uiTimer=setInterval(()=>{const walking=world?.getStats().walk.active;toolbar.classList.toggle('landed',!!walking);nearbyHouse=world?.nearbyHouse();const room=world?.room();document.querySelector('#leave-room').hidden=!room;document.querySelector('#decorate').hidden=!room||(!own&&demo!=='home');interact.hidden=!walking||(!nearbyHouse&&!world.nearRecord());interact.textContent=nearbyHouse?'走进小屋 · E':world?.recordPlaying()?'暂停唱片 · E':'播放《蝉鸣》· E';},200);
addEventListener('pagehide',()=>clearInterval(uiTimer));
async function patch(actions){if(demo==='home'){for(const a of actions){if(a.type==='object.remove')scene.objects=scene.objects.filter(o=>o.id!==a.id);if(a.type==='object.upsert'){const {checkFurniturePlacement}=await import('../server/furniture-rules.js');const room=scene.rooms.find(r=>r.id===a.value.roomId);checkFurniturePlacement(a.value,room,scene.objects);scene.objects.push(a.value);}}return scene;}if(!ownedRecord)throw Error('只有岛主可以装修');ownedRecord=await api('/islands/'+ownedRecord.id,'PATCH',{revision:ownedRecord.revision,actions});scene=ownedRecord.scene;return scene;}
interact.onclick=async()=>{try{if(nearbyHouse){const house=nearbyHouse;if(own&&!scene.rooms.some(r=>r.houseId===house)){const room={id:'room-'+crypto.randomUUID(),houseId:house,name:'岛上的小屋',width:8,depth:6,height:3.2};await patch([{type:'room.upsert',value:room}]);world.setEcology(scene);}if(!world.enterHouse(house))feedback('这座房屋还没有室内空间，等岛主布置好再来。');else feedback('到家了。靠近家具可以互动。');}else{await world.playRecord();feedback(world.recordPlaying()?'正在播放你的《蝉鸣》':'唱片已暂停');}}catch(e){feedback(e.message);}};
document.querySelector('#leave-room').onclick=()=>{world.leaveHouse();feedback('回到了岛上。');};
addEventListener('keydown',e=>{if(dialog.open||/INPUT|TEXTAREA/.test(e.target?.tagName))return;if(e.key.toLowerCase()==='c')chooseCamera(['third','first','overhead'][(['third','first','overhead'].indexOf(cameraMode)+1)%3]);if(e.key.toLowerCase()==='e'&&!interact.hidden)interact.click();});
function closeButton(){dialog.querySelector('[data-close]').onclick=()=>dialog.close();}
document.querySelector('#avatar-edit').hidden=!!demo;
document.querySelector('#avatar-edit').onclick=()=>{dialog.innerHTML=`<button data-close class="dialog-close">关闭</button><small>属于你的 ID 形象</small><h2>让 Agent 写出你的样子。</h2><p>把下面的代码交给你的 Agent 修改，再粘贴回来。外观跟随你的账号，走到哪座岛都还是你。</p><p>使用 island.mesh / island.onFrame / island.move；最多 48 个网格、6000 顶点。脚底 y=0，高度不超过 2.4 米，左右和前后各不超过 1 米。移动、碰撞和权限由游戏控制。</p><textarea id="avatar-source" aria-label="玩家形象 JavaScript" spellcheck="false"></textarea><p id="avatar-result" role="status"></p><button id="avatar-save">保存并穿上</button> <button id="avatar-reset">恢复初始形象</button>`;dialog.querySelector('textarea').value=avatarRecord.source||DEFAULT_AVATAR_CODE;closeButton();let saving=false;const save=async source=>{if(saving)return;saving=true;const buttons=[...dialog.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{dialog.querySelector('#avatar-result').textContent='正在检查形象代码…';if(world&&!await world.setAvatar(source))throw Error('形象代码未通过运行检查，没有覆盖已保存的形象。');try{avatarRecord=await api('/avatar','PUT',{revision:avatarRecord.revision,source});}catch(e){world?.setAvatar(avatarRecord.source);throw e;}dialog.querySelector('#avatar-result').textContent='形象已保存，并穿好了。';}catch(e){dialog.querySelector('#avatar-result').textContent=e.message;}finally{saving=false;buttons.forEach(b=>b.disabled=false);}};dialog.querySelector('#avatar-save').onclick=()=>save(dialog.querySelector('textarea').value);dialog.querySelector('#avatar-reset').onclick=()=>save('');dialog.showModal();};
document.querySelector('#decorate').onclick=()=>{const room=world.room();if(!room)return;dialog.innerHTML=`<button data-close class="dialog-close">关闭</button><small>${demo?'示例房间 · 刷新后恢复，不写入账号':'屋内的一点心意'}</small><h2>放进你喜欢的东西。</h2><p>也可以回创作页告诉 Agent：在这间房间里放置或移动家具。房间编号：<code></code></p><label>家具 <select id="furniture-kind"></select></label><div class="furniture-coordinate"><label>左右 X <input id="furniture-x" type="number" value="2.5" step=".25"></label><label>前后 Z <input id="furniture-z" type="number" value="-1.5" step=".25"></label><label>朝向 <select id="furniture-angle"><option value="0">朝入口</option><option value="1.570796">向右</option><option value="3.141593">向后</option><option value="-1.570796">向左</option></select></label></div><button id="furniture-add">放在这里</button><p id="furniture-result" role="status"></p><div id="furniture-list"></div>`;dialog.querySelector('code').textContent=room.id;for(const [kind,name] of Object.entries(FURNITURE)){const option=new Option(name,kind);dialog.querySelector('#furniture-kind').add(option);}dialog.querySelector('#furniture-kind').value='recordPlayer';closeButton();const list=()=>{const target=dialog.querySelector('#furniture-list');target.replaceChildren();for(const obj of scene.objects.filter(o=>o.roomId===room.id)){const line=document.createElement('div');line.className='furniture-row';const label=document.createElement('span');label.textContent=(FURNITURE[obj.kind]||obj.kind)+` · (${obj.x}, ${obj.z})`;const remove=document.createElement('button');remove.textContent='收起';remove.onclick=async()=>{try{await patch([{type:'object.remove',id:obj.id}]);world.refreshRoom(scene);list();}catch(e){dialog.querySelector('#furniture-result').textContent=e.message;}};line.append(label,remove);target.append(line);}};dialog.querySelector('#furniture-add').onclick=async()=>{try{const value={id:crypto.randomUUID(),kind:dialog.querySelector('#furniture-kind').value,roomId:room.id,x:Number(dialog.querySelector('#furniture-x').value),z:Number(dialog.querySelector('#furniture-z').value),y:0,rotation:Number(dialog.querySelector('#furniture-angle').value),color:'wood'};await patch([{type:'object.upsert',value}]);world.refreshRoom(scene);dialog.querySelector('#furniture-result').textContent='已放好。';list();}catch(e){dialog.querySelector('#furniture-result').textContent=e.message;}};list();dialog.showModal();};
addEventListener('island-asset-error',e=>feedback(e.detail));

addEventListener('island-program-status',e=>{if(/超限|超出|出错|没有及时响应|未通过/.test(e.detail))status(e.detail+' 可以返回创作页，让 Agent 修正这次代码。');});
